### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by yewero** [aertslab/pySCENIC#1]
pip install .

Processing /test/software/pySCENIC-master
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-eaM7qn-build/setup.py", line 80, in <module>
        install_requires=read_requirements('requirements.txt'),
      File "/tmp/pip-eaM7qn-build/setup.py", line 49, in read_requirements
        with open(fname, 'r', encoding='utf-8') as file:
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-eaM7qn-build/

**Comment by bramvds** [comment]
You are probably using a python 2.7.x interpreter. pySCENIC only works for python 3.x . Hope this helps.
