### ISSUE TITLE
Question: Integrating user derived transcription factor matrix

### ISSUE THREAD

**Issue by Connorr0** [aertslab/pySCENIC#101]
Hello, I have derived my own transcription factor gene relationship matrix but would like to do pyScenic to find the modules. Is there a way to do this?

**Comment by bramvds** [comment]
Hi,

This is not so easy. Creating your own ranking databases is explained in the FAQ: 
https://github.com/aertslab/pySCENIC#can-i-create-my-own-ranking-databases

Unfortunately, the creation of the ranking databases available on cisTargetDB is an elaborate process which is not explained in the FAQ. The process/pipeline uses a large collection of PWMs/motifs and integrates several tools like cluster-buster, LiftOver, OrderStatistics, .... The scripts we use to automate this process are currently not yet available on github.

Kindest regards,
Bram

**Comment by Connorr0** [comment]
Shoot, I'm a little confused after looking at the FAQ and the feather database? What is the meaning behind the rows and columns. I could create a score myself but I do not know what the values are supposed to represent.

**Comment by bramvds** [comment]
Dear,

You need to rank the genes based on the score you generated and store the rank in the database.

Hope this helps,
Bram

**Comment by cflerin** [comment]
It should now be possible to generate custom databases following the scripts here: https://github.com/aertslab/create_cisTarget_databases
