### ISSUE TITLE
How to Input loom file or RDS from seurat

### ISSUE THREAD

**Issue by grimwoo** [aertslab/pySCENIC#109]
Hi, I previously analyzed scRNA data by Seurat (a R-based package) and had many clusters (cell groups).

Here, I want to use pySCENIC to further analyze the data from Seurat. Could I read file from RDS (output of Seurat in R) directly, or could I read the loom file from Seurat? And how to do it? Thanks so much~

**Comment by bramvds** [comment]
Dear,

Your best option is to export the data to loom file format and use pySCENIC's Command Line Interface (CLI). The CLI has direct support for loom files. The attributes of the loom file used to manage metadata can be controlled via the following parameters:
`--cell_id_attribute` - The name of the column attribute that specifies the identifiers of the cells in the loom file.
`--gene_attribute` - The name of the row attribute that specifies the gene symbols in the loom file.

You could of course stick to R and use the original version of SCENIC (in R): https://github.com/aertslab/SCENIC

Kr,
Bram

**Comment by grimwoo** [comment]
Thanks for your early reply~ I'll try this one as soon as possible!

**Comment by grimwoo** [comment]
It worked! Thank you!
