### ISSUE TITLE
Dask issue on large data set

### ISSUE THREAD

**Issue by gharmange** [aertslab/pySCENIC#114]
I have been able to successfully run pySCENIC on a small subset of my data (a 2Mb gene expression matrix), but when I try and run it on my full data set (a 280mb gene expression matrix) I get the following errors:
First:
distributed.utils_perf - WARNING - full garbage collections took 10% CPU time recently (threshold: 10%)
which it seems might get resolved, and then:
distributed.core - INFO - Event loop was unresponsive in Nanny for 4.64s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.

It stayed on this error for a couple days before I decided to kill the job. I am doing this on a computing cluster and I should have plenty of CPU and memory for the job. Any Idea what could be going on?

**Comment by cflerin** [comment]
Recommend trying this using the newest pySCENIC release (0.11.0)
