### ISSUE TITLE
pyscenic aucell  ERROR - Expression matrix should be provided in the loom file format.

### ISSUE THREAD

**Issue by Sophia409** [aertslab/pySCENIC#115]
Hello, aertslab
I run grn and ctx successfully by using expression matrix csv file in CLI(as my screenshot shows) ,but auccell failed and the error showed that expression matrix should be provided in the loom file format. But when I search the  function definition with pyscenic aucell --help, it shows that two file formats are both supported. 
What's the reason?

> expression_mtx_fname  The name of the file that contains the expression matrix for the single cell experiment. Two file formats are
                        supported: csv (rows=cells x columns=genes) or loom (rows=genes x columns=cells).

```
SC_EXP_FNAME = "/public-supool/home/yhzhang/Jupyter/SCENIC/pySCENIC/tmp/1.1_exprMatrix_filtered_t.txt"
EXP_MTX_QC_FNAME = "neu.qc.csv"
ex_matrix = pd.read_csv(SC_EXP_FNAME,sep='\t', header=0, index_col=0)
ex_matrix.shape
(27007, 10367)
adata = sc.read_text(SC_EXP_FNAME, delimiter='\t', first_column_names=True )
adata
AnnData object with n_obs × n_vars = 27007 × 10367 
adata.to_df().to_csv(EXP_MTX_QC_FNAME)
EXP_MTX_QC_FNAME 
'neu.qc.csv'

EXP_MTX_QC_FNAME 
!pyscenic aucell \
    {EXP_MTX_QC_FNAME} \
    reg.csv \
    --output {f_pyscenic_output} \
    --num_workers 32
/public-supool/home/yhzhang/miniconda3/lib/python3.7/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}

2019-12-13 21:40:42,323 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.

2019-12-13 21:45:05,273 - pyscenic.cli.pyscenic - INFO - Loading gene signatures.

2019-12-13 21:46:40,232 - pyscenic.cli.pyscenic - INFO - Calculating cellular enrichment.

2019-12-13 21:47:55,671 - pyscenic.cli.pyscenic - INFO - Writing results to file.

2019-12-13 21:50:25,127 - pyscenic.cli.pyscenic - ERROR - Expression matrix should be provided in the loom file format.
```

![image](https://user-images.githubusercontent.com/30619010/70805823-d7ebc500-1df4-11ea-961b-390dc1d0d0e8.png)

**Comment by bramvds** [comment]
Dear,

What is the extension of `{f_pyscenic_output}`? Try to change it into csv ... If the output extension is defined as `.loom`, Aucell expects the expression matrix to be given as `.loom` file too.

Hope this helps,
Bram
