### ISSUE TITLE
export2loom - regulon name error and taking a long time

### ISSUE THREAD

**Issue by lc822** [aertslab/pySCENIC#116]
Hi,

I am trying to run export2loom so that I can view the results of my command line pySCENIC analysis in SCope.  

I have three questions:
1. Why does it not like regulon names similar to the following?

> Regulon(name='AHCTF1(+)', gene2weight=<frozendict {'NAA25': 7.196456997725309, 'PDS5A': 6.6811370675982324, 'AHCTF1': 6.740688883153564, 'PIP5K1A': 1.0, 'SLK': 6.831961219161978, 'CANX': 9.474825144558618, 'EIF3A': 6.73557067991401, 'RAD50': 9.732132817929097, 'RAB3GAP1': 7.510537651989787, 'NUDT3': 9.929638056014808, 'ACSL4': 9.084245423098496, 'AEBP1': 11.171253205381555, 'APPL1': 8.29387249758021, 'TRIM44': 5.784827913418367}>, transcription_factor='AHCTF1', context=frozenset({'cisbp__M0131.png', 'activating'}), score=2.7740978185475105)

I ran the recommended code:
`regulons = [r.rename(r.name.replace('(+)',' ('+str(len(r))+'g)')) for r in regulons]`

My new regulons are named as follows:

> Regulon(name='AHCTF1 (14g)', gene2weight=<frozendict {'NAA25': 7.196456997725309, 'PDS5A': 6.6811370675982324, 'AHCTF1': 6.740688883153564, 'PIP5K1A': 1.0, 'SLK': 6.831961219161978, 'CANX': 9.474825144558618, 'EIF3A': 6.73557067991401, 'RAD50': 9.732132817929097, 'RAB3GAP1': 7.510537651989787, 'NUDT3': 9.929638056014808, 'ACSL4': 9.084245423098496, 'AEBP1': 11.171253205381555, 'APPL1': 8.29387249758021, 'TRIM44': 5.784827913418367}>, transcription_factor='AHCTF1', context=frozenset({'cisbp__M0131.png', 'activating'}), score=2.7740978185475105)

Is this what they are supposed to look like?

2. How long should I expect export2loom to take?  I am running with num_workers = 12 and my dataset contains ~9000 genes and ~30,000 cells.  It seems to have been running for a long time and I am wondering whether something has gone wrong?

3. Not specifically related to my issue, but how can I find out which regulons are the most important in my dataset?  Is it the score listed in the regulon information as above?

Many thanks,

Lucy

**Comment by bramvds** [comment]
Dear Lucy,

1. Looks good.

2. The amount of time for export2loom is driven by the binarization process. The default method uses the computationally heavy 'Hartigan's Dip test' to discern of AUCell distribution of a regulon across cells is bimodal. Currently, you can use more cores to reduce the wall time of this step.

3. Indeed. It is best to look at the score (This is the score from the GRNBoost2/GENIE3 step).

Kindest regards,
Bram

**Comment by lc822** [comment]
Thank you.

1. What does the "(14g)" in the regulon name mean?

2. Can I use the AUC matrix that I generated using the command-line version to speed up this process?

3. Can I export the regulon information as a simple table?

**Comment by bramvds** [comment]
Dear Lucy,

1. The number of genes in the regulon.
2. Another solution would be to use the other method available - gaussian mixture model fit. However this currently can only be set on the `derive_threshold` method and not from the high-level function `export2loom`. I'll try to find the time to make some code adjustments.

Kr,
Bram

**Comment by lc822** [comment]
Hi Bram,

I am trying to run the export2loom function as follows to convert the results from the CLI into a format that I can import into R.

```
export2loom(exp_mtx, regulons, annotations,
            LOOM_FILE,
            title = "Stimulation data",
            nomenclature = "hg38", 
            auc_mtx = auc_mtx,
            num_workers = 24)
```

This seems to be taking a very long time and I just wanted to check that I have got the command correct?  

I would like to use the aucell matrix that I generated with `pyscenic aucell`.  The output from the CLI is a matrix with cells as rows and regulons as columns.  Am I correct in thinking that this needs to be transposed for the `export2loom` function so that rows are regulons and columns are cells?  

Many thanks,
Lucy

**Comment by cflerin** [comment]
Hi @lc822 ,

For the issue of `export2loom` hanging, I think the root cause is from the `binarize` function (#188), which isn't solved yet. For your goal of creating a working loom file, there is a workaround that I'd suggest you use instead of `export2loom`. From the AUCell output generated from the CLI (loom file), you can run a script that will add a t-SNE and UMAP, and hopefully  get a working loom. Please take a look [here](https://pyscenic.readthedocs.io/en/latest/faq.html#how-can-i-create-a-scope-compatible-loom-file).
