### ISSUE TITLE
why I got regulons with fewer than 20 genes?

### ISSUE THREAD

**Issue by Sophia409** [aertslab/pySCENIC#118]
Hello @bramvds ,

Since all regulons targeting fewer than 20 genes are dropped (in the modules_from_adjacencies function, why I got regulons with fewer than 20 genes?
![image](https://user-images.githubusercontent.com/30619010/71080565-5e731e80-21c8-11ea-8485-6868c80b4861.png)

Hope for your reply

**Comment by bramvds** [comment]
Dear,

the iCisTarget step prunes targets if there are no cis-regulatory motifs present in the associated putative regulatory regions. So, from the initial 20 genes defined from the network inference step (GENIE3/GRNBoost2) you end up with fewer numbers.

Hope this helps,
Bram

**Comment by Sophia409** [comment]
@bramvds  Hello,bramvds
Thank you for your reply, But I'm not fully understand. I use the default parameter to run the pipeline. So is it OK to got regulons with fewer than 20 genes?
Also, do I need to delete these regulons with few genes? Are they of low reliability? Why all these three regulons got the highest Regulon specificity scores in my data?


> adjacencies = grnboost2(ex_matrix, tf_names=tf_names, verbose=True)

**Comment by bramvds** [comment]
Dear,

It's normal to get final regulons with fewer than 20 genes. You start with 20 genes and the false positive ones (i.e. having no cis-regulatory motif evidence) are removed.

Do not discard them, if they have good scores and it makes biological sense you should certainly keep them.

Kr,
Bram

**Comment by Sophia409** [comment]
@bramvds Hello,bramvds

Thank you for your patience, now I understand it. But I still have some other questions.

First, are regulons with different numbers of genes of same importance? Or are regulons with large numbers of potential targets more reliable? 

Second, what is the difference between Average Regulon Activity (SCENIC R version)and Regulon specificity scores(pySCENIC version) among different cell types? Can both them help to find cell type specific regulons? Or, is RSS score more accurate?

I'm really confused. And I couldn't find a function to compute RSS in SCENIC R version. So i'm not sure if i must run pySCENIC pipeline to get it.

![image](https://user-images.githubusercontent.com/30619010/71088974-c5013800-21da-11ea-92a0-ceb9e2c8147c.png)
![image](https://user-images.githubusercontent.com/30619010/71089049-f67a0380-21da-11ea-9c30-5cfb8f4c147b.png)

**Comment by bramvds** [comment]
Hi,

For every cell in the experiment AUcell gives you an activity score for a regulon. The average activity of a regulon in a cell type is just the average of the individual AUCell activity scores for all cells of that cell type in the experiment. You can use this to compare these average AUCell scores across cell types for the same regulon to identify which regulon is cell-type specific.

RSS is only available in pySCENIC for now and uses an information theoretic metric to find regulon specific to a certain cell type.

So yes, both approaches are useful to answer the same question. However, we did not compare these two metrics.

Kindest regards,
Bram

**Comment by Sophia409** [comment]
@bramvds 
 Thank you so much for your help！

**Comment by fbrundu** [comment]
Hi @bramvds. Is there documentation on the specificity score? Is it based on [JSD](https://en.wikipedia.org/wiki/Jensen–Shannon_divergence)? Thanks!

**Comment by bramvds** [comment]
Yes it is based on the JSD - Cf. Suo, S., Zhu, Q., Saadatpour, A., Fei, L., Guo, G., Yuan, G. (2018). Revealing the Critical Regulators of Cell Identity in the Mouse Cell Atlas. Cell Reports  25(6), 1436 1445.e3. https://dx.doi.org/10.1016/j.celrep.2018.10.045
