### ISSUE TITLE
aucell returns EOF error

### ISSUE THREAD

**Issue by TsumaR** [aertslab/pySCENIC#122]
Hi,

I am trying to run aucell.
I use your docker image by singularity, but I got a  EOF error.
pyscenic grn and pyescnic ctx did well.

command
```
singularity run aertslab-pyscenic-0.9.19.sif \
  pyscenic aucell \
  count.tsv \
  regulons.csv \
  -o auc_mtx.csv \
  --num_workers 6 
``` 

Then, I got the below error message.
``` 
/bin/bash: /home/myne812/anaconda3/lib/libtinfo.so.6: no version information available (required by /bin/bash)
/opt/venv/lib/python3.7/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}

2019-12-26 14:42:13,675 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.

2019-12-26 14:42:15,036 - pyscenic.cli.pyscenic - INFO - Loading gene signatures.

2019-12-26 14:42:15,053 - pyscenic.cli.pyscenic - ERROR - Error tokenizing data. C error: EOF inside string starting at row 52
``` 

regulons.csv file 

![image](https://user-images.githubusercontent.com/42291982/71460627-f936b300-27ef-11ea-805d-a2f58604adda.png)

Please help

"Postscripts" 
The file ended unexpectedly and was not output to the end.
The core file was output.

**Comment by cflerin** [comment]
Hi, the screenshot you posted looks like it's from excel, or a similar program. Is it possible that excel over-wrote the regulons.csv with its own format? This would certainly cause a problem when trying to read the file back in at the AUCell step.
