### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by JLiLab** [aertslab/pySCENIC#123]
I had no problem to install and run pySCENIC in my computer, but ran into problem in import pyscenic in the cluster. Here is the error message: 

>>> from pyscenic.rnkdb import FeatherRankingDatabase as RankingDatabase
Illegal instruction
(python3) -bash-4.2$ 

I will appreciate you help.

**Comment by bramvds** [comment]
Dear,

Could you make sure pySCENIC is properly installed (preferably using a new miniconda environment solely for running pySCENIC) and the feather databases you downloaded are not corrupt (verify the checksum)?

Kr,
Bram

**Comment by JLiLab** [comment]
Thank you for your quick reply!

I have repeated installation in a new environment, and verified the feather databases. Unfortunately,  I still have the same problem. I have tried using pip install pyscenic and installing from the source. No issues were flagged during the installation. No sure what is the problem. 
James

**Comment by ghuls** [comment]
Illegal instruction normally means that you try to execute some instructions (in compiled code) which are not supported by your CPU architecture. It could be that miniconda installed a package like numpy, scipy, ... that is incompatible with your CPU architecture on your HPC cluster. In that case you need to find the offending package and compile it from source on your HPC cluster first. If your HPC cluster uses a module system, it might be better to load a correct version of Python with numpy, scipy, ... installed already.

**Comment by JLiLab** [comment]
Is there is quick way to find the offending package?

**Comment by ghuls** [comment]
If you are lucky, yes.

```bash
# Go to the pyscenic dir.
cd src/pyscenic/

# Open python and enter each line separately till it crashes (beginning of https://github.com/aertslab/pySCENIC/blob/master/src/pyscenic/rnkdb.py):
python
```

```python
import os
import pandas as pd
import numpy as np
from typing import Tuple, Set, Type
from abc import ABCMeta, abstractmethod
import sqlite3
from operator import itemgetter
from .genesig import GeneSignature
from cytoolz import memoize
from pyarrow.feather import write_feather, FeatherReader
from tqdm import tqdm
```

**Comment by JLiLab** [comment]
This was the error message that I got:
>>> import numpy as np
>>> from typing import Tuple, Set, Type
>>> from abc import ABCMeta, abstractmethod
>>> import sqlite3
>>> from operator import itemgetter
>>> from .genesig import GeneSignature
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named '__main__.genesig'; '__main__' is not a package

Where is ".genesig" from?

**Comment by ghuls** [comment]
It is in `src/pyscenic`. You can change it to `from genesig import GeneSignature`.

**Comment by JLiLab** [comment]
This is what I got:
>>> from genesig import GeneSignature
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'genesis'

**Comment by ghuls** [comment]
Are you sure that you are in the `src/pyscenic` directory before starting python?

**Comment by JLiLab** [comment]
My mistake: I was no in the src/pyscenic directory.
I restarted python in the correct directory. This is the error message: 
AttributeError: type object 'cytoolz.itertoolz.remove' has no attribute '__reduce_cython__'

**Comment by ghuls** [comment]
Are you sure you are running the same python binary than the one from your first post?

**Comment by JLiLab** [comment]
I could not find the src/pyscenic directory after pip install pyscenic in the newly created conda env. I repeated git clone https://github.com/aertslab/pySCENIC.git
cd pySCENIC/
pip install
Now, I have this error message in importing panda module:
AttributeError: module 'datetime' has no attribute 'datetime_CAPI'

This is confusing.

**Comment by ghuls** [comment]
```python
import os
import pyscenic

pyscenic_dir = os.path.dirname(pyscenic.__file__)

print(pyscenic_dir)

os.chdir(pyscenic_dir)


import pandas as pd
import numpy as np
from typing import Tuple, Set, Type
from abc import ABCMeta, abstractmethod
import sqlite3
from operator import itemgetter
from genesig import GeneSignature
from cytoolz import memoize
from pyarrow.feather import write_feather, FeatherReader
from tqdm import tqdm
```

**Comment by JLiLab** [comment]
Pandas, numpy, and sqlite3 can be imported without problem. But if I run
import os
import pyscenic

pyscenic_dir = os.path.dirname(pyscenic.__file__)

print(pyscenic_dir)

os.chdir(pyscenic_dir)

I got the following error message to import pandas: AttributeError: module 'datetime' has no attribute 'datetime_CAPI'
Numpy: Original error was: PyCapsule_Import could not import module "datetime"
Sqlite3: AttributeError: module 'datetime' has no attribute 'datetime_CAPI'
Genesig: AttributeError: type object 'numpy.random._bit_generator.SeedSequence' has no attribute '__reduce_cython__'
Cytoolz: AttributeError: type object 'cytoolz.itertoolz.remove' has no attribute '__reduce_cython__'
from pyarrow.feather import write_feather, FeatherReader: AttributeError: type object 'numpy.random._bit_generator.SeedSequence' has no attribute '__reduce_cython__'

**Comment by ghuls** [comment]
Does this also give an error:
```python
from pyarrow.feather import write_feather, FeatherReader
```
