### ISSUE TITLE
ValueError in running prune2df and grnboost2

### ISSUE THREAD

**Issue by ghost** [aertslab/pySCENIC#124]
Hi,

So I'm trying to run pySCENIC on the same dataset, however with a subset of genes compared to the whole genome. When I try to run it on the whole genome, I get an error in grnboost2, with the following message: 
ValueError: Metadata mismatch found in `from_delayed`.

Expected partition of type `pandas.core.frame.DataFrame` but got `NoneType`

I've seen that other people have had a similar issue, and I've seen the recommendations about how to fix it. I have made sure that there are no duplicate genes, but that doesn't help. Nothing I've tried to so far helps in fixing the issue.

When I try running it on the subset of genes, grnboost2 seems to work. However, I then get an error when I run the prune2df step. It get sstuck at 0% for a long time until it eventually crashes, yielding the following error: 
ValueError: The columns in the computed data do not match the columns in the provided metadata
  Extra:   []
  Missing: []

I've tried looking into what causes it, but I cannot figure it out. Any suggestions for how to fix both issues?

**Comment by cflerin** [comment]
Please see #163 for some possible solutions to this
