### ISSUE TITLE
Command line pyscenic grn fails at loading matrix

### ISSUE THREAD

**Issue by mehrankr** [aertslab/pySCENIC#127]
Hello,

Thank you for providing an extensive documentation.
I am trying to get the pyscenic tool running with python 3.7.4.

```
pyscenic grn -o pyScenicOutput/tfTargets.csv --seed 42 GSE60361_C1-3005-Expression.txt /h/mkarimza/software/pySCENIC/resources/mm_mgi_tfs.txt

/h/mkarimza/anaconda3/lib/python3.7/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}

2020-01-28 13:30:25,145 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.

2020-01-28 13:30:25,146 - pyscenic.cli.pyscenic - ERROR - Unknown file format "GSE60361_C1-3005-Expression.txt.gz".
```

Trying with -t or using ungzipped version did not help neither.
Output of freeze for relevant packages:
```
dask==1.0.0
numpy==1.17.2
numpy-groupies==0+unknown
numpydoc==0.9.1
pandas==0.25.1
pyscenic==0.9.19+2.gef16250
tornado==6.0.3
```

If you could provide more detailed documentation and the exact data that the docker image requires that would be great too.
Specifying how I should change the command in the docker example would probably clarify this:

```
docker run \
    -v /path/to/data:/scenicdata \
    aertslab/pyscenic pyscenic grn \
        --num_workers 6 \
        -o /scenicdata/expr_mat.adjacencies.tsv \
        /scenicdata/expr_mat.tsv \
        /scenicdata/allTFs_hg38.txt
```

Does pulling the docker image save the data under scenicdata somewhere? How can I access those? How should I modify -v parameter input?

Looking forward to hear back from you.

Best,
Mehran

**Comment by cflerin** [comment]
Hi Mehran,

First, if you're using gene expression data in text file as an input, it needs to have an extension of either "tsv" or "csv" depending on your delimiter. Just using "txt" or gzipped files will not work unfortunately.

Secondly, the docker image doesn't contain any of the reference data. You will need to download these yourself for your specific organism (see "auxilliary datasets" in https://github.com/aertslab/pySCENIC#installation). 

For the docker volume mount question, you have to specify a path on your local machine (containing the data + reference data) to mount inside the container. In the example, `/scenicdata/...` is a path that exists only inside the container (pointing to `/path/to/data` on the host). But I think it's most straightforward if you name the host and container volumes exactly the same. So if your expression data is in:
```/home/me/data/expression_data/GSE60361_C1-3005-Expression.txt```
and your reference data is in:
```/home/me/data/reference_data/```
you could just use `-v /home/me/data:/home/me/data`. Then you can put the full path to each of your files in the `pyscenic grn`, etc. commands. Like so:
```
docker run \
    -v /home/me/data:/home/me/data \
    aertslab/pyscenic pyscenic grn \
        --num_workers 6 \
        -o /home/me/data/expression_data/expr_mat.adjacencies.tsv \
        /home/me/data/expression_data/expr_mat.tsv \
        /home/me/data/reference_data/allTFs_hg38.txt
```

**Comment by yulchen810** [comment]
Hi, @cflerin 
I run pyscenic grn ctx and aucell in singularity, the input counts matrix is as below picture.
The first column of the counts matrix is cell ID, is that ok?

![image](https://github.com/user-attachments/assets/781b3dcd-3759-4014-9b69-edf6d2971ce7)

Thank you!

**Comment by sugiYag** [comment]
@yulchen810 

I have a similar question with mehrankr.
Which type of data should I use as input for PySCENIC: raw count matrix data or normalized matrix data?

**Comment by yulchen810** [comment]
> @yulchen810 
> 
> I have a similar question with mehrankr.
> Which type of data should I use as input for PySCENIC: raw count matrix data or normalized matrix data?

I used counts matrix as input.
