### ISSUE TITLE
TimeoutError: Worker failed to start

### ISSUE THREAD

**Issue by Matthias3033** [aertslab/pySCENIC#129]
I get the following error when i run the function grnboost2:

preparing dask client
distributed.nanny - WARNING - Worker process still alive after 47 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 47 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 47 seconds, killing
distributed.nanny - WARNING - Worker process 25163 was killed by signal 15
distributed.nanny - WARNING - Worker process 25167 was killed by signal 15
distributed.nanny - WARNING - Worker process 25169 was killed by signal 15
distributed.nanny - WARNING - Worker process still alive after 47 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 47 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 47 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 47 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 47 seconds, killing
distributed.nanny - WARNING - Worker process 25173 was killed by signal 15
distributed.nanny - WARNING - Worker process 25177 was killed by signal 15
distributed.nanny - WARNING - Worker process 25181 was killed by signal 15
distributed.nanny - WARNING - Worker process 25186 was killed by signal 15
distributed.nanny - WARNING - Worker process 25189 was killed by signal 15
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "/home/icb/matthias.puchta/miniconda3/lib/python3.7/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "/home/icb/matthias.puchta/miniconda3/lib/python3.7/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/home/icb/matthias.puchta/miniconda3/lib/python3.7/site-packages/distributed/deploy/local.py", line 316, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "/home/icb/matthias.puchta/miniconda3/lib/python3.7/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "/home/icb/matthias.puchta/miniconda3/lib/python3.7/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/home/icb/matthias.puchta/miniconda3/lib/python3.7/site-packages/distributed/deploy/local.py", line 316, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "/home/icb/matthias.puchta/miniconda3/lib/python3.7/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "/home/icb/matthias.puchta/miniconda3/lib/python3.7/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/home/icb/matthias.puchta/miniconda3/lib/python3.7/site-packages/distributed/deploy/local.py", line 316, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "/home/icb/matthias.puchta/miniconda3/lib/python3.7/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "/home/icb/matthias.puchta/miniconda3/lib/python3.7/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/home/icb/matthias.puchta/miniconda3/lib/python3.7/site-packages/distributed/deploy/local.py", line 316, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "/home/icb/matthias.puchta/miniconda3/lib/python3.7/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "/home/icb/matthias.puchta/miniconda3/lib/python3.7/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/home/icb/matthias.puchta/miniconda3/lib/python3.7/site-packages/distributed/deploy/local.py", line 316, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "/home/icb/matthias.puchta/miniconda3/lib/python3.7/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "/home/icb/matthias.puchta/miniconda3/lib/python3.7/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/home/icb/matthias.puchta/miniconda3/lib/python3.7/site-packages/distributed/deploy/local.py", line 316, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
tornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "/home/icb/matthias.puchta/miniconda3/lib/python3.7/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "/home/icb/matthias.puchta/miniconda3/lib/python3.7/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/home/icb/matthias.puchta/miniconda3/lib/python3.7/site-packages/distributed/deploy/local.py", line 316, in _start_worker
    raise gen.TimeoutError("Worker failed to start")
tornado.util.TimeoutError: Worker failed to start
---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
<ipython-input-21-2a39c5430bc1> in <module>
----> 1 adjancencies = grnboost2(expression_data=ex_matrix, tf_names=tf_names, verbose=True)

~/miniconda3/lib/python3.7/site-packages/arboreto/algo.py in grnboost2(expression_data, gene_names, tf_names, client_or_address, early_stop_window_length, limit, seed, verbose)
     39     return diy(expression_data=expression_data, regressor_type='GBM', regressor_kwargs=SGBM_KWARGS,
     40                gene_names=gene_names, tf_names=tf_names, client_or_address=client_or_address,
---> 41                early_stop_window_length=early_stop_window_length, limit=limit, seed=seed, verbose=verbose)
     42 
     43 

~/miniconda3/lib/python3.7/site-packages/arboreto/algo.py in diy(expression_data, regressor_type, regressor_kwargs, gene_names, tf_names, client_or_address, early_stop_window_length, limit, seed, verbose)
    107         print('preparing dask client')
    108 
--> 109     client, shutdown_callback = _prepare_client(client_or_address)
    110 
    111     try:

~/miniconda3/lib/python3.7/site-packages/arboreto/algo.py in _prepare_client(client_or_address)
    155 
    156     if client_or_address is None or str(client_or_address).lower() == 'local':
--> 157         local_cluster = LocalCluster(diagnostics_port=None)
    158         client = Client(local_cluster)
    159 

~/miniconda3/lib/python3.7/site-packages/distributed/deploy/local.py in __init__(self, n_workers, threads_per_worker, processes, loop, start, ip, scheduler_port, silence_logs, dashboard_address, diagnostics_port, services, worker_services, service_kwargs, asynchronous, security, protocol, blocked_handlers, interface, worker_class, **worker_kwargs)
    216         self.worker_class = worker_class
    217 
--> 218         self.start(ip=ip, n_workers=n_workers)
    219 
    220         clusters_to_close.add(self)

~/miniconda3/lib/python3.7/site-packages/distributed/deploy/local.py in start(self, **kwargs)
    254             self._started = self._start(**kwargs)
    255         else:
--> 256             self.sync(self._start, **kwargs)
    257 
    258     @gen.coroutine

~/miniconda3/lib/python3.7/site-packages/distributed/deploy/local.py in sync(self, func, *args, **kwargs)
    247             return future
    248         else:
--> 249             return sync(self.loop, func, *args, **kwargs)
    250 
    251     def start(self, **kwargs):

~/miniconda3/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
    329             e.wait(10)
    330     if error[0]:
--> 331         six.reraise(*error[0])
    332     else:
    333         return result[0]

~/miniconda3/lib/python3.7/site-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

~/miniconda3/lib/python3.7/site-packages/distributed/utils.py in f()
    314             if timeout is not None:
    315                 future = gen.with_timeout(timedelta(seconds=timeout), future)
--> 316             result[0] = yield future
    317         except Exception as exc:
    318             error[0] = sys.exc_info()

~/miniconda3/lib/python3.7/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

~/miniconda3/lib/python3.7/site-packages/tornado/gen.py in run(self)
    740                     if exc_info is not None:
    741                         try:
--> 742                             yielded = self.gen.throw(*exc_info)  # type: ignore
    743                         finally:
    744                             # Break up a reference to itself

~/miniconda3/lib/python3.7/site-packages/distributed/deploy/local.py in _start(self, ip, n_workers)
    282         self.scheduler.start(address)
    283 
--> 284         yield [self._start_worker(**self.worker_kwargs) for i in range(n_workers)]
    285 
    286         self.status = "running"

~/miniconda3/lib/python3.7/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

~/miniconda3/lib/python3.7/site-packages/tornado/gen.py in callback(fut)
    499             for f in children_futs:
    500                 try:
--> 501                     result_list.append(f.result())
    502                 except Exception as e:
    503                     if future.done():

~/miniconda3/lib/python3.7/site-packages/tornado/gen.py in run(self)
    746                             exc_info = None
    747                     else:
--> 748                         yielded = self.gen.send(value)
    749 
    750                 except (StopIteration, Return) as e:

~/miniconda3/lib/python3.7/site-packages/distributed/deploy/local.py in _start_worker(self, death_timeout, **kwargs)
    314         if w.status == "closed" and self.scheduler.status == "running":
    315             self.workers.remove(w)
--> 316             raise gen.TimeoutError("Worker failed to start")
    317 
    318         raise gen.Return(w)

**TimeoutError: Worker failed to start**

**Does someone know how to fix this mistake?**

**Comment by bramvds** [comment]
Hi,

The workers created by dask are killed upon creation - one reason I once encountered myself was too much RAM usage in the absence of a swapfile. Could you reduce the number of workers the reduce the RAM needs of SCENIC?

Kr,
Bram

**Comment by Matthias3033** [comment]
Hi Bram,

how can I do that?

**Comment by bramvds** [comment]
Via CLI you have the parameter `--num_workers N` where N specifies the number of cores to use. Using the API for Jupyter notebooks, a similar parameter is available.

**Comment by Matthias3033** [comment]
Sry, but I can‘t find this parameter. How can I use your approach in Jupyter?

**Comment by bramvds** [comment]
For the prune2df function (cistarget step) the parameter name is `num_workers`. For grnboost, I kindely refer you to the arboreto package documentation:  https://github.com/tmoerman/arboreto . Briefly, you need to use a construct like this
```
from pyscenic.prune import _prepare_client
from arboreto import grnboost2

client, shutdown_callback = _prepare_client('local_host', num_workers=12)
network = grnboost2(expression_data=ex_mtx, tf_names=tf_names, verbose=True, client_or_address=client)
```

**Comment by Matthias3033** [comment]
This proposal unfortunately does not solve this issue

**Comment by millersan** [comment]
You can try to paste the code in jupyter, and run again. I meet the same problem in terminal, but it can be work in jupyter notebook.
