### ISSUE TITLE
Tutorial omission of key idiom

### ISSUE THREAD

**Issue by topherconley** [aertslab/pySCENIC#13]
Hi Bram,

The absence of 

```
if __name__ == '__main__':
```

from the tutorial you posted creates some problems for new users oblivious to its importance: [arboretum issue](https://github.com/tmoerman/arboretum/issues/2)

Best,
Chris

**Comment by bramvds** [comment]
Dear Chris,

Thanks, I'll explicitly mention this in the tutorial. To my knowledge, this is only required if you run this code from a python script. If you run this code from a Jupyter notebook (which I did) this is not the case. Anyhow, I falsely assumed that people would run this from a notebook. Thanks for pointing this out.

FYI: The Command Line Interface properly uses this python construct you mentioned so should not generate this particular error.

Kindest regards,
Bram

**Comment by topherconley** [comment]
Ahh, yes, I understand, you are right.
