### ISSUE TITLE
Importing regulons.csv into scanpy pipeline

### ISSUE THREAD

**Issue by ltosti** [aertslab/pySCENIC#135]
Hi @cflerin @bramvds @ghuls,

I generated a ```regulons.csv``` file as output of the CLI ```pyscenic ctx```. What would be the easiest way to import this file into the scanpy pipeline as to use the ```regulons``` object into the function ```add_scenic_metadata(adata, auc_mtx, regulons)```?

Thank you for your help!

**Comment by cflerin** [comment]
Hi @ltosti 

You could use something like the following to add the regulon data to an anndata object:

```python
from pyscenic.export import add_scenic_metadata
from pyscenic.cli.utils import load_signatures

sig = load_signatures('regulons.csv')
add_scenic_metadata(adata, auc_mtx, sig)
```
