### ISSUE TITLE
AssertionError in add_scenic_metadata(adata, auc_mtx, regulons)

### ISSUE THREAD

**Issue by zehualilab** [aertslab/pySCENIC#144]
I got this error when running the integretion with scanpy notebook with pyscenic V0.10.0 and scanpy V1.4.5.1. 
Here is the error message:---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-27-6899f7e27a8d> in <module>
----> 1 add_scenic_metadata(adata, auc_mtx, regulons)

~\Anaconda3\envs\pyscenic\lib\site-packages\pyscenic\export.py in add_scenic_metadata(adata, auc_mtx, regulons, bin_rep, copy)
    211     #assert isinstance(adata, sc.AnnData)
    212     assert isinstance(auc_mtx, pd.DataFrame)
--> 213     assert len(auc_mtx) == adata.n_obs
    214 
    215     REGULON_SUFFIX_PATTERN = 'Regulon({})'

AssertionError: 
I run len(auc_mtx) and got 23686, which is the adata.n_vars before the filtering step. Is there something wrong here or how should I do to avoid this error?Thanks.

**Comment by zehualilab** [comment]
Oh, the notebook uses exp_mtx to get auc_mtx, btw. I could not find exp_mtx and used the df_tpm to get auc_mtx. I  run exp_mtx = df_tpm.T and fix this...

**Comment by DuaaAlawad** [comment]
Did you solve this issue?

**Comment by realzehuali** [comment]
I chose to use Seurat at last
