### ISSUE TITLE
Celltypes are mixed after running tsne with X_aucell

### ISSUE THREAD

**Issue by zehualilab** [aertslab/pySCENIC#145]
Hi, I met this problem after sc.tl.tsne(adata, use_rep='X_aucell') when running the same notebook pyscenic provides (integretion with scanpy). The results I got differ from the results in the notebook a lot. I did not met any error.  I just wonder  whether i was using pyscenic properly and what might cause this problem.
![tsne X_aucell](https://user-images.githubusercontent.com/47061602/75627075-05802780-5c08-11ea-9463-ce87be11386b.png)
![results in notebook](https://user-images.githubusercontent.com/47061602/75627086-2e082180-5c08-11ea-8106-6d7fa72f0997.png)

**Comment by noorisotoudeh** [comment]
you should reorder  rows of auc_mtx with adata.obs
