### ISSUE TITLE
pyscenic cli supporting sparse data

### ISSUE THREAD

**Issue by nathanin** [aertslab/pySCENIC#153]
I should have searched first. #140 is exactly what I typed out below regarding arboreto and sparse matrices. I think the change to `find_adjacencies_command` is still valid, although it requires arboreto to be patched.

-------

Hi, I recently tried to use the pyscenic cli to run grnboost2 with the `--sparse` flag enabled and found that sparse matrix input from a loom file was not fully supported. 

I installed through conda, and the versions of some packages in my environment are:
```
anndata==0.7.1
arboreto==0.1.5
dask==1.0.0
distributed==1.28.1
numpy==1.18.2
pandas==0.25.3
pyscenic==0.10.0
scanpy==1.4.6
scikit-learn==0.22.1
scipy==1.4.1
```

I wrote out a loom file from scanpy using the `AnnData.write_loom` function, then ran the following command, eventually getting the error below:

```bash
$ pyscenic grn --num_workers 4 \
  --sparse \
  --gene_attribute var_names \
  --cell_id_attribute obs_names \
  -o my_data.adj.csv \
  my_data.loom \
  ./tfs.txt

...
AttributeError: 'tuple' object has no attribute 'shape'
```

Three changes were needed. First, the function `load_exp_matrix` returns a tuple if `sparse=True`, so make a change to how the `ex_mtx` variable is passed into the method if it's sparse. `gene_names` are also required.
 https://github.com/aertslab/pySCENIC/blob/ceaad7d13806c0e4f842efd07543eacf4151f266/src/pyscenic/cli/pyscenic.py#L72

to 
```python
network = method(expression_data=ex_mtx[0] if args.sparse else ex_mtx, 
    gene_names=ex_mtx[1] if args.sparse else None,
    tf_names=tf_names, 
    verbose=True, 
    client_or_address=client, 
    seed=args.seed)
```

In the `arboreto` package I also had to change the innards of `fit_model` to pass the column vector check in scikit-learn otherwise I was getting bad input shape errors.
https://github.com/tmoerman/arboreto/blob/3ff7b6f987b32e5774771751dea646fa6feaaa52/arboreto/core.py#L122
to
```python
# add from scipy.sparse import issparse to the top of this file, then add:
if issparse(target_gene_expression):
    target_gene_expression = target_gene_expression.toarray().ravel()
assert tf_matrix.shape[0] == target_gene_expression.shape[0]
```

The last change is needed because if the target gene is part of the transcription factors list, then `np.delete` is called to remove the TF gene expression from the predictors. I don't think that `np.delete` works on sparse matrices; it gives back a weird `numpy.ndarray` with shape `()`, so I just chop out the TF expression column with a logical mask instead. There may be a more efficient way depending on the type of sparse matrix.

https://github.com/tmoerman/arboreto/blob/3ff7b6f987b32e5774771751dea646fa6feaaa52/arboreto/core.py#L229
to
```python
clean_tf_matrix = tf_matrix[:, np.array(tf_matrix_gene_names) != target_gene_name]
```

Having made these changes, the rest of the `ctx` and `aucell` workflows executed smoothly :+1:

**Comment by cflerin** [comment]
Hi @nathanin , nice work! You're right about the `find_adjacencies_command` update.

Were you able to make sparse matrices work for the `ctx` and `aucell` steps as well? This is something I haven't had time to look at or test, but it would be useful for `aucell` especially as the ranking step uses a lot of memory.

Feel free to create a pull request for this!

**Comment by cflerin** [comment]
There is now support for sparse matrices in pySCENIC 0.11.0 (for the GRN step only, via Arboreto).
