### ISSUE TITLE
Installation of development version

### ISSUE THREAD

**Issue by saeedfc** [aertslab/pySCENIC#159]
Hi,
I tried the following. However, I still see that my pyscenic version is pyscenic==0.9.19 (pip freeze and conda list). However, the homepage says the ltest version is 0.10. Is there something wrong with the way I do?
Kindly advice!

git clone https://github.com/aertslab/pySCENIC.git
cd pySCENIC/
pip install

**Comment by cflerin** [comment]
Hi @saeedfc ,

You're missing a `.` in your install command for the development version:
```
pip install .
```
but if you just want to upgrade to the latest release, you can use:
```
pip install pyscenic==0.10.0
```
