### ISSUE TITLE
Running pySCENIC on Docker

### ISSUE THREAD

**Issue by singcell** [aertslab/pySCENIC#165]
I am trying to run pySCENIC on Docker. I am new to both Docker and python. 
Your instruction says `Note that the **feather databases, transcription factors, and motif annotation databases** need to be accessible to the container. In the below examples, separate mounts are created for the input, output, and databases directories.`

I wanted to know where can I download feather databases, transcription factors, and motif annotation databases? Do they come with Docker image.

If I need to download, where should I download on my local drive and mention its local path in "/path/to/data:/scenicdata"

Additionally, where can I get **scenicdata/expr_mat.adjacencies.tsv** file for my input? and where should I store it? in "/path/to/data:/scenicdata".

**Comment by cflerin** [comment]
Hi @singcell , Sorry if it's not clear. The support databases are not included in the Docker image, so you'll have to download them yourself (see [here](https://pyscenic.readthedocs.io/en/latest/installation.html#auxiliary-datasets)).

To make them available to the running Docker container, you need to create a volume mount when starting the container (the `-v` parameter in `docker run ...`). The easiest thing I have found is to just mount the folder on your OS to the same path within the container. So if your support databases are stored on your computer on the path `/data/cistarget_databases/`, then you could specify a mount like `docker run -v /data:/data ...`. This way you can always refer to the files by their full path whether they are inside or outside the container.

The `adjacencies.tsv` file is the output of GRNBoost2 and it generated during the grn inference step. It's used in the pruning/cistarget step to generate co-expression modules. Likewise, just mount `/data` using `-v /data:/data` (for example), then refer to the file by its full path: `/data/pyscenic/adjacencies.tsv`/
