### ISSUE TITLE
Re-execute pySCENIC

### ISSUE THREAD

**Issue by wangjiawen2013** [aertslab/pySCENIC#166]
Dear,
If I subset my dataset (such as a sub population of cells), must I re-execute pyscenic with the new dataset, or I can still use the AUCell  scores from the whole dataset ?

**Comment by cflerin** [comment]
Hi @wangjiawen2013 ,

I think the comments in this reply to another issue will help you: https://github.com/aertslab/pySCENIC/issues/128#issuecomment-581324499 (see "guidelines on how to interpret AUC" under point 2). Generally no, you shouldn't need to re-run but it's also most interesting to look at cell activity across all cell types for a given regulon. Feel free to re-open if this doesn't answer your question.
