### ISSUE TITLE
pySCENIC for other species

### ISSUE THREAD

**Issue by singcell** [aertslab/pySCENIC#172]
I wanted to use pySCENIC tool in Rat. Both rat and mouse has same motif databases however location of motifs on genomes and genomic coordinates are different. Can I still use pySCENIC for rat samples.
Could you please let me know what modifications I need to make it work in rats, what  kind of files do I need for that.
If I need .bed file containing candidate regulatory regions, where would be the best place to get it for other species.

**Comment by vagabond12** [comment]
I have  the similar problem. Can I use pySCENIC tool to analyse Cynomolgus monkey samples with the human motif database?

**Comment by cflerin** [comment]
Sorry for the lack of reply here, but it's something we are working on, and will update when it's ready. See also: aertslab/SCENICprotocol/issues/23

**Comment by cflerin** [comment]
We now have an initial set of scripts and methods to generate custom databases. The instructions are in the early stages, but they can be found here: https://github.com/aertslab/create_cisTarget_databases. If there are issues with the database creation, you could raise a more specific issue in that repository.
