### ISSUE TITLE
Can I use imputed counts for pySCENIC?

### ISSUE THREAD

**Issue by chansigit** [aertslab/pySCENIC#178]
I noticed the loom file required by pySCENIC contains a read count matrix.
The values in the matrix are integers. 
I imputed my expression matrix and got an adjusted count matrix where the adjusted count values are decimals. Can I use this matrix for pySCENIC? Does its model support this?

**Comment by cflerin** [comment]
The network inference step uses regression trees, and therefore the input matrix can be in any units (CPM, FPKM, raw counts, etc.), and does not need to be scaled. So technically your matrix will certainly work with the GRN algorithm, but I can't say how good the results will be with imputed data (we have not tried this).
