### ISSUE TITLE
[results] Using df2regulon vs auxillary function derive_regulon

### ISSUE THREAD

**Issue by Annika18** [aertslab/pySCENIC#179]
Hi, 
I have followed the [tutorial](https://pyscenic.readthedocs.io/en/latest/tutorial.html) for pySCENIC and am now implementing the [scenic protocol](http://htmlpreview.github.io/?https://github.com/aertslab/SCENICprotocol/blob/master/notebooks/SCENIC%20Protocol%20-%20Case%20study%20-%20Cancer%20data%20sets.html) for my data set. 

I noticed that the Protocol uses the auxillary function derive_regulon to get a list of regulons, while the tutorial (and other examples I've looked at) just seem to use the df2regulon built in function. What is the difference and potential benefit of one over the other? How much would it change the actual resulting list of regulons? (And relatedly, would this have a significant impact on the results of AUCell?) 

Thanks so much for any help.

**Comment by cflerin** [comment]
Hi @Annika18 ,

The `df2regulon` function creates regulons from enriched features. The majority of the work is done prior to this in the main `prune2df` function.

The `derive_regulons ` function in the cancer tutorial has some settings that are specific to that dataset (you can see some of this from the comments in that function).

For a typical analysis, I would start with the standard pySCENIC steps, which use the `prune2df` and `df2regulon`. Then, if you want to apply more filters to the regulons found there, you can do so.
