### ISSUE TITLE
[results] Can I use pySCENIC tool to analyse Cynomolgus monkey samples with the human motif database?

### ISSUE THREAD

**Issue by vagabond12** [aertslab/pySCENIC#184]
Can I use pySCENIC tool to analyse Cynomolgus monkey samples with the human motif database?

**Comment by cflerin** [comment]
Hi @vagabond12 ,

We don't have any motif databases for this species. But, it _might_ work if you replace your gene names in your data with the equivalent orthologous genes in human. This should technically get pySCENIC to run, but this isn't something I've tried, so I can't say how well it would work in terms of results.
