### ISSUE TITLE
 Error in get_regulonsAuc(loom) : The argument 'attrName' is not available in this loom file. Possible values include: RegulonsAUC. 

### ISSUE THREAD

**Issue by charlesgwellem** [aertslab/pySCENIC#195]
Can any one help me with a hint why I cannot read fully in output from pySCENIC in to Rstudio? I used pyCENIC to run the SCENIC workflow and I used the following command

`(base) charles@rahul-SYS-7039A-I:~/Downloads/ssc_Valenzi$ sudo ./nextflow run aertslab/SCENICprotocol -profile docker --loom_input ssc_ECs_Valenzi.loom --loom_outputhttps://github.com/aertslab/pySCENIC/issues/194 pyscenic_integrated-output.loom --TFs hs_hgnc_curated_tfs.txt --motifs motifs-v9-nr.hgnc-m0.001-o0.0.tbl --db hg38__refseq-r80__500bp_up_and_100bp_down_tss.mc9nr.feather --thr_min_genes 1 --threads 26`

But I want to read in results about the regulons in R. So I

```
pyScenicLoomFile <- file.path(getwd(), "pyscenic_integrated-output.loom")
loom <- open_loom(pyScenicLoomFile, mode="r")


# Regulon AUC and thresholds
regulonsAUC <- get_regulonsAuc(loom)

```
But I got the error

```
Error in get_regulonsAuc(loom) : 
  The argument 'attrName' is not available in this loom file. Possible values include: RegulonsAUC.
```

Thanks in advance for your kind help.

**Comment by cflerin** [comment]
Hi @charlesgwellem ,

This is a SCopeLoomR issue, it seems. The default value for the `attrName` was recently changed. Try:
```
regulonsAUC <- get_regulonsAuc(loom, attrName="RegulonsAUC")
```

**Comment by FourAlarmFire** [comment]
I just get  this error:
Error in get_regulons(sce_SCENIC, column.attr.name = "Regulons") : 
  The attribute 'Regulons' is not available in this loom file. The loom doesn't contain regulon information.
 when I tried to get the list of regulons of my pyscenic results
`` regulons_incidMat<- get_regulons(sce_SCENIC, attrName="Regulons")``,
please someone could tell me where the issue is?
thanks!!!

**Comment by apal6** [comment]
Hi, 
I would like to follow up as I am having the same issue. Thank you so much!

**Comment by sunchunming2001** [comment]
Me too!!!

**Comment by linlenfeng** [comment]
Yes, and I have found that, although there were no error messages in any of the three runs, the pyscenic aucell did not write the AUCell results to the loom file.
