### ISSUE TITLE
Error in regulon prediction [results]

### ISSUE THREAD

**Issue by Goultard59** [aertslab/pySCENIC#196]
Hi,

I'm trying to follow the nature protocols with my data but I encountered some difficulty.
I'm using Seurat for control quality and data integration (http://htmlpreview.github.io/?https://github.com/satijalab/seurat-wrappers/blob/master/docs/liger.html) and I save the result and additional information (cell type, phase cycle, etc.). In the loom format using loomR.

For the network inference, I use the latest docker version.

`docker run -it -v /home/:/home/ aertslab/pyscenic:latest \
arboreto_with_multiprocessing.py \
--num_workers 20 \
--output /home/adj.tsv \
--method grnboost2 \
/home/timetemp.loom \
/home/mm_mgi_tfs.txt
`
which giving me the following error but with a complete adj.tsv 

`'infer_data failed for target Star' Retry (1/10). Failure caused by ValueError("Regression for target gene Star failed. Cause ValueError('Found array with 0 feature(s) (shape=(46593, 0)) while a minimum of 1 is required.').").
'infer_data failed for target Star' Retry (2/10). Failure caused by ValueError("Regression for target gene Star failed. Cause ValueError('Found array with 0 feature(s) (shape=(46593, 0)) while a minimum of 1 is required.').").
'infer_data failed for target Star' Retry (3/10). Failure caused by ValueError("Regression for target gene Star failed. Cause ValueError('Found array with 0 feature(s) (shape=(46593, 0)) while a minimum of 1 is required.').").
'infer_data failed for target Star' Retry (4/10). Failure caused by ValueError("Regression for target gene Star failed. Cause ValueError('Found array with 0 feature(s) (shape=(46593, 0)) while a minimum of 1 is required.').").
'infer_data failed for target Star' Retry (5/10). Failure caused by ValueError("Regression for target gene Star failed. Cause ValueError('Found array with 0 feature(s) (shape=(46593, 0)) while a minimum of 1 is required.').").
'infer_data failed for target Star' Retry (6/10). Failure caused by ValueError("Regression for target gene Star failed. Cause ValueError('Found array with 0 feature(s) (shape=(46593, 0)) while a minimum of 1 is required.').").
'infer_data failed for target Star' Retry (7/10). Failure caused by ValueError("Regression for target gene Star failed. Cause ValueError('Found array with 0 feature(s) (shape=(46593, 0)) while a minimum of 1 is required.').").
'infer_data failed for target Star' Retry (8/10). Failure caused by ValueError("Regression for target gene Star failed. Cause ValueError('Found array with 0 feature(s) (shape=(46593, 0)) while a minimum of 1 is required.').").
'infer_data failed for target Star' Retry (9/10). Failure caused by ValueError("Regression for target gene Star failed. Cause ValueError('Found array with 0 feature(s) (shape=(46593, 0)) while a minimum of 1 is required.').").
'infer_data failed for target Star' Retry (10/10). Failure caused by ValueError("Regression for target gene Star failed. Cause ValueError('Found array with 0 feature(s) (shape=(46593, 0)) while a minimum of 1 is required.').").`

For the Candidate regulon generation and regulon prediction, I use no_pruning as I'm not sure with the threshold parameters (default parameters didn't found any regulon) as only one regulon and I'm attempting to find some of Linnarsson_Mouse_Brain regulon.

For the cellular enrichment, I use the 0.9.18 docker version as loomR use the old loom version.

I have tried to add the visualisation following your doc but I got the following error :

`python add_visualization.py \
     --loom_input scenic_outpur.loom \
     --loom_output scenic_visualize.loom
/opt/venv/lib/python3.7/site-packages/umap/nndescent.py:92: NumbaPerformanceWarning: 
The keyword argument 'parallel=True' was specified but no transformation for parallel execution was possible.

To find out why, try turning on parallel diagnostics, see http://numba.pydata.org/numba-doc/latest/user/parallel.html#diagnostics for help.

File "../../../../../../opt/venv/lib/python3.7/site-packages/umap/utils.py", line 409:
@numba.njit(parallel=True)
def build_candidates(current_graph, n_vertices, n_neighbors, max_candidates, rng_state):
^

  current_graph, n_vertices, n_neighbors, max_candidates, rng_state
/opt/venv/lib/python3.7/site-packages/numba/typed_passes.py:271: NumbaPerformanceWarning: 
The keyword argument 'parallel=True' was specified but no transformation for parallel execution was possible.

To find out why, try turning on parallel diagnostics, see http://numba.pydata.org/numba-doc/latest/user/parallel.html#diagnostics for help.

File "../../../../../../opt/venv/lib/python3.7/site-packages/umap/nndescent.py", line 47:
    @numba.njit(parallel=True)
    def nn_descent(
    ^

  state.func_ir.loc))
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/loompy/global_attribute_manager.py", line 48, in __getattr__
    return self.__dict__["storage"][name]
KeyError: 'ds'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "add_visualization.py", line 86, in <module>
    visualize_AUCell(args)
  File "add_visualization.py", line 82, in visualize_AUCell
    scope_loom.export(out_fname=args.loom_output)
  File "/home/adrien.dufour/NeuroDev_ADD/SingleCell/python_single_cell/loom_storage/export_to_loom.py", line 766, in export
    file_attrs=self.global_attrs
  File "/opt/venv/lib/python3.7/site-packages/loompy/loompy.py", line 1057, in create
    with new(filename, file_attrs=file_attrs) as ds:
  File "/opt/venv/lib/python3.7/site-packages/loompy/loompy.py", line 998, in new
    ds.attrs[vals] = file_attrs[vals]
  File "/opt/venv/lib/python3.7/site-packages/loompy/global_attribute_manager.py", line 66, in __setitem__
    return self.__setattr__(name, val)
  File "/opt/venv/lib/python3.7/site-packages/loompy/global_attribute_manager.py", line 88, in __setattr__
    self.ds._file.create_dataset("attrs/" + name, data=normalized, dtype=h5py.special_dtype(vlen=str))
  File "/opt/venv/lib/python3.7/site-packages/loompy/global_attribute_manager.py", line 55, in __getattr__
    raise AttributeError(f"File has no global attribute '{name}'")
AttributeError: File has no global attribute 'ds' `
[adj.xlsx](https://github.com/aertslab/pySCENIC/files/5030288/adj.xlsx)
[reg.xlsx](https://github.com/aertslab/pySCENIC/files/5030289/reg.xlsx)

Thanks a lot for the help

Cordially,
Adrien Dufour.

**Comment by cflerin** [comment]
Hi @Goultard59 ,

My first guess is that both of these issue are related to the loom file created by Seurat, which I believe still uses the loom v2 format (the script to add visualizations in particular I think assumes the loom is v3). It'll be a bit before I'll have time to look at this in detail. If you need something immediately, I'd suggest exporting your data to a text file and running this file through the pySCENIC steps.

**Comment by honghh2018** [comment]
Hi @Goultard59 ,
   I wonder why your seurat object can transfer into loom using as.loom from seurat package v3. as far as i know the as.loom function can not be tranfer v3 object into loom from now on.
   Thanks

**Comment by Goultard59** [comment]
Thanks for the answers.

I found the origins of the problems, the auxiliary files were corrupted. I succesfully run the differents steps which provid much more regulon.
For the visualisation scripts, I found a derived solution using seurat object -> h5data (with seuratdisk) -> loom (with loompy)
but downstream analysis give me a low score for all my regulon (except two).

Thanks.

**Comment by cflerin** [comment]
Hi @Goultard59 ,

Ok, glad you solved your issue. 

For the messages that look like:
```
'infer_data failed for target BRF1' Retry (1/10). Failure caused by ValueError("Regression for target gene BRF1 failed. Cause ValueError('Found array with 0 feature(s) (shape=(100, 0)) while a minimum of 1 is required.').").
```
these are warnings (not errors) from Arboreto that occur when there are no genes remaining to analyze for a particular target gene (after filtering). So as long as you get an output, there's nothing to worry about and these target genes are skipped over.

I wasn't able to get Seurat to produce a valid loom file -- it seems like loomR indeed uses the older format and has not been updated in a while. Seurat-disk seems like a good workaround.
