### ISSUE TITLE
Error triggerred when running docker on step1

### ISSUE THREAD

**Issue by honghh2018** [aertslab/pySCENIC#197]
Hi @all,
   the docker step one using the scRNA normalized data matrix as inputed trigger a error like below,
File "/opt/venv/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 80, in find_adjacencies_command
    extension = PurePath(fname).suffixes
NameError: name 'fname' is not defined
     The matrix format picture showing below,
![image](https://user-images.githubusercontent.com/41668708/89846688-7878cb80-dbb4-11ea-9759-a758659ac211.png)
      What happen on my workflow on the pyscenic docker?
   Best,
   honghanhui

**Comment by cflerin** [comment]
Hi @honghh2018 ,

My guess is that you're using an old version of pySCENIC. Try upgrading to the latest version, and use this image:
```
docker pull aertslab/pyscenic:0.10.3
```
