### ISSUE TITLE
expression matrix

### ISSUE THREAD

**Issue by wangjiawen2013** [aertslab/pySCENIC#20]
Dear, 
Is is necessary to make log transformation on the input expression matrix, as the GENIE3 does ?

**Comment by bramvds** [comment]
Dear Jiawen,

There should be no need to transform the gene expression matrix for the GENIE3 step of SCENIC. GENIE3 is based on a "regression per target gene" strategy using a Random Forest (RF) algorithm under the hood to capture non-linear relationships between factor and target. Features do not need to be scaled or transformed for a RF technique to work properly. See also: https://stats.stackexchange.com/questions/58697/when-to-log-exp-your-variables-when-using-random-forest-models . In fact, the GENIE3 tutorial (https://bioconductor.org/packages/release/bioc/vignettes/GENIE3/inst/doc/GENIE3.html) also mentions: "Note that the expression data do not need to be normalised in any way".

However, defining modules from GENIE3 as input for the cisTarget phase of SCENIC depends on the Pearson correlation coefficient to find modules of which target genes are positively or negatively correlated with the expression of the transcription factor. Pearson correlation is susceptible to a log transformation so you might want to inspect the distribution of gene expression to investigate if a transformation is required. FYI: I plan to change from Pearson to Spearman correlation in later versions of pySCENIC. The latter being invariant to such transformations.

Hope this helps,
Bram

**Comment by wangjiawen2013** [comment]
Do you change Pearson to Sparman correlation now ? There is no need to log transform the expression matrix in grnboost2 either?
