### ISSUE TITLE
Pyscenic installation error on mac os

### ISSUE THREAD

**Issue by rach88** [aertslab/pySCENIC#201]
Hi, 
I am attempting to install pySCENIC on  mac os (10.14.6) but I keep running into the following problem. Any specific guidelines for mac installation would be greatly appreciated!

1. Command run when the error occurred:
pip install pyscenic
```python
...
```

2. Error encountered:
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/jj/l6v20rh92zb8v7vtdzqcxxr00000gp/T/pip-install-7ANV06/pyscenic/setup.py'"'"'; __file__='"'"'/private/var/folders/jj/l6v20rh92zb8v7vtdzqcxxr00000gp/T/pip-install-7ANV06/pyscenic/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/jj/l6v20rh92zb8v7vtdzqcxxr00000gp/T/pip-install-7ANV06/pyscenic/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/jj/l6v20rh92zb8v7vtdzqcxxr00000gp/T/pip-install-7ANV06/pyscenic/setup.py", line 80, in <module>
        install_requires=read_requirements('requirements.txt'),
      File "/private/var/folders/jj/l6v20rh92zb8v7vtdzqcxxr00000gp/T/pip-install-7ANV06/pyscenic/setup.py", line 49, in read_requirements
        with open(fname, 'r', encoding='utf-8') as file:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```pytb
...
```

**Comment by cflerin** [comment]
Are you using the system Python (2.7) for this? pySCENIC needs Python 3.6+. I would recommend using [Conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/macos.html), and following the pySCENIC install instructions for Conda [here](https://github.com/aertslab/SCENICprotocol/blob/master/docs/installation.md#conda) (the Scanpy install is optional).

**Comment by rach88** [comment]
Thanks, it works!
