### ISSUE TITLE
Extract Regulon genes in Pyscenic[results]

### ISSUE THREAD

**Issue by deevdevil88** [aertslab/pySCENIC#202]
Hello,
I was wondering if there is a way to extract the specific genes for regulons of interest in Pyscenic. In the R version, there is command to extract regulon specific genes, However, I cannot seem to find the best way to do that in Pyscenic.

Thanks
Devika

**Comment by cflerin** [comment]
Hi @deevdevil88 ,

I would do something like this (if you're loading the regulons from a file):
```
from pyscenic.cli.utils import load_signatures

sig = load_signatures('reg.csv')

regulon_of_interest = 'EBF1(+)'
regulon = [ x for x in sig if x.name==regulon_of_interest ][0]
```
You can then access the genes with `regulon.genes`

If you want to load from a pySCENIC loom, it's also straightforward to load only the regulon genes into a dictionary:
```
import loompy as lp
import pandas as pd

lf = lp.connect('example.loom', mode='r', validate=False )

regulons = {}
for i,r in pd.DataFrame(lf.ra.Regulons,index=lf.ra.Gene).iteritems():
    regulons[i] =  list(r[r==1].index.values)

regulon_of_interest = 'EBF1_(+)'
regulons[regulon_of_interest]
```

**Comment by deevdevil88** [comment]
Thank you, but what if i have a pickled file which i get after running df2regulons on the motif file generated from CLI version. As df2regulons output is directly saved as a pickled file and not a csv. So how would I extract the regulons and regulon genes from the pickled file or is there a way to save the df2regulon output as a csv.

Thanks
Devika
