### ISSUE TITLE
[results]how to call arboreto_with_multiprocessing.py in the new version?

### ISSUE THREAD

**Issue by chansigit** [aertslab/pySCENIC#203]
I noticed this script was "integrated" into pyscenic CLI. How shall we call it now? still `python arboreto_with_multiprocessing.py  blahblahblah`?

**Comment by cflerin** [comment]
From release `0.10.3` the script is available directly on the path, so there's no need to download it anymore (although this will still work fine). So if your conda or virtual environment is active you can just run from the command line:
```
arboreto_with_multiprocessing.py
```
Likewise with Docker or Singularity:
```
docker run -it --rm aertslab/pyscenic:0.10.3 arboreto_with_multiprocessing.py
```
