### ISSUE TITLE
[results]

### ISSUE THREAD

**Issue by cnrooter** [aertslab/pySCENIC#204]
Hi pySCENIC developers: 
     I got a question: for the time-consuming task of running R GENIE3,  may I use pyscenic grnboost2 reuslts as the input of scenic R pipeline , with the third column value of grnboost2 results divided by  1000? Is that right?

**Comment by cflerin** [comment]
Hi @cnrooter ,

Yes, you can load the grnboost2 results from pySCENIC into the R pipeline. There's no need to scale the importance scores, as the modules are created by a combination of rank-based cutoffs (taking the top N genes, the top N genes by percentile, etc.). One suggestion is that you filter out the edges towards the bottom of the ranking with very low importance scores (below ~0.01, for instance). This will ensure that these edges don't get added into the modules created in the R pipeline.
