### ISSUE TITLE
How to binarize the network activity (regulon on/off) in python ?

### ISSUE THREAD

**Issue by zorrodong** [aertslab/pySCENIC#21]
Dear,

Thanks for the powerful tool.

I have finished the pipeline of pySCENIC successfully. However, I wonder how could I binarize the AUC matrix result, like the pipeline in R ? Since my data have serious batch effect, the binary value might be more useful ?

Looking forward to your reply, thanks very much !

Best,

Zorro
20180916

**Comment by bramvds** [comment]
Dear Zorro,

You could use the 'binarize' function in the module 'binarization'. See https://github.com/aertslab/pySCENIC/blob/84e9ebe6f566342afef61afdd2af780a4b3c5bc2/src/pyscenic/binarization.py#L31

Kindest regards,
Bram

**Comment by zorrodong** [comment]
Oh, I see, thanks very much!

**Comment by wangjiawen2013** [comment]
The how to use binarization.py in jupyter notebook and shell ? I ran
auc_mtx_binary = binarize(auc_mtx,num_workers=15)
Some errors occured:
/home/wangjw/bin/miniconda3/envs/scenic/lib/python3.6/site-packages/pyscenic/diptest.py:30: RuntimeWarning: divide by zero encountered in true_divide
  slopes = (work_cdf[1:] - work_cdf[0]) / distances
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/wangjw/bin/miniconda3/envs/scenic/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/wangjw/bin/miniconda3/envs/scenic/lib/python3.6/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/wangjw/bin/miniconda3/envs/scenic/lib/python3.6/site-packages/pyscenic/binarization.py", line 52, in derive_threshold
    if not isbimodal(data, method):
  File "/home/wangjw/bin/miniconda3/envs/scenic/lib/python3.6/site-packages/pyscenic/binarization.py", line 43, in isbimodal
    _, pval, _ = diptst(np.msort(data))
  File "/home/wangjw/bin/miniconda3/envs/scenic/lib/python3.6/site-packages/pyscenic/diptest.py", line 53, in diptst
    d, (_, idxs, left, _, right, _) = dip_fn(dat, is_hist)
  File "/home/wangjw/bin/miniconda3/envs/scenic/lib/python3.6/site-packages/pyscenic/diptest.py", line 115, in dip_fn
    xl = left_touchpoints[d_left == left_diffs][0]
IndexError: index 0 is out of bounds for axis 0 with size 0
"""

The above exception was the direct cause of the following exception:

IndexError                                Traceback (most recent call last)
<ipython-input-56-3221a48c19c6> in <module>
----> 1 auc_mtx_binary = binarize(auc_mtx,num_workers=15)

~/bin/miniconda3/envs/scenic/lib/python3.6/site-packages/pyscenic/binarization.py in binarize(auc_mtx, threshold_overides, seed, num_workers)
     77             thrs = p.starmap( derive_threshold,  [ (auc_mtx, c, seed) for c in auc_mtx.columns ] )
     78         return pd.Series(index=auc_mtx.columns, data=thrs)
---> 79     thresholds = derive_thresholds(auc_mtx)
     80     if threshold_overides is not None:
     81         thresholds[list(threshold_overides.keys())] = list(threshold_overides.values())

~/bin/miniconda3/envs/scenic/lib/python3.6/site-packages/pyscenic/binarization.py in derive_thresholds(auc_mtx, seed)
     75     def derive_thresholds(auc_mtx, seed=seed):
     76         with Pool( processes=num_workers ) as p:
---> 77             thrs = p.starmap( derive_threshold,  [ (auc_mtx, c, seed) for c in auc_mtx.columns ] )
     78         return pd.Series(index=auc_mtx.columns, data=thrs)
     79     thresholds = derive_thresholds(auc_mtx)

~/bin/miniconda3/envs/scenic/lib/python3.6/multiprocessing/pool.py in starmap(self, func, iterable, chunksize)
    272         `func` and (a, b) becomes func(a, b).
    273         '''
--> 274         return self._map_async(func, iterable, starmapstar, chunksize).get()
    275 
    276     def starmap_async(self, func, iterable, chunksize=None, callback=None,

~/bin/miniconda3/envs/scenic/lib/python3.6/multiprocessing/pool.py in get(self, timeout)
    642             return self._value
    643         else:
--> 644             raise self._value
    645 
    646     def _set(self, i, obj):

~/bin/miniconda3/envs/scenic/lib/python3.6/multiprocessing/pool.py in worker()
    117         job, i, func, args, kwds = task
    118         try:
--> 119             result = (True, func(*args, **kwds))
    120         except Exception as e:
    121             if wrap_exception and func is not _helper_reraises_exception:

~/bin/miniconda3/envs/scenic/lib/python3.6/multiprocessing/pool.py in starmapstar()
     45 
     46 def starmapstar(args):
---> 47     return list(itertools.starmap(args[0], args[1]))
     48 
     49 #

~/bin/miniconda3/envs/scenic/lib/python3.6/site-packages/pyscenic/binarization.py in derive_threshold()
     50             return gmm2.bic(X) <= gmm1.bic(X)
     51 
---> 52     if not isbimodal(data, method):
     53         # For a unimodal distribution the threshold is set as mean plus two standard deviations.
     54         return data.mean() + 2.0*data.std()

~/bin/miniconda3/envs/scenic/lib/python3.6/site-packages/pyscenic/binarization.py in isbimodal()
     41         if method == 'hdt':
     42             # Use Hartigan's dip statistic to decide if distribution deviates from unimodality.
---> 43             _, pval, _ = diptst(np.msort(data))
     44             return (pval is not None) and (pval <= 0.05)
     45         else:

~/bin/miniconda3/envs/scenic/lib/python3.6/site-packages/pyscenic/diptest.py in diptst()
     51     """ diptest with pval """
     52     # sample dip
---> 53     d, (_, idxs, left, _, right, _) = dip_fn(dat, is_hist)
     54 
     55     # simulate from null uniform

~/bin/miniconda3/envs/scenic/lib/python3.6/site-packages/pyscenic/diptest.py in dip_fn()
    113             d = d_right
    114         else:
--> 115             xl = left_touchpoints[d_left == left_diffs][0]
    116             xr = right_touchpoints[right_touchpoints >= xl][0]
    117             d = d_left

IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by wangjiawen2013** [comment]
My dataset have 59847 rows and 401 columns, I can run binarization with 10000 rows and 401 columns successfully, is my dataset too large ?

**Comment by cflerin** [comment]
@wangjiawen2013 , happy to help, but could you please start a new issue for this? It would help to have the output formatted in a code block and a list of your installed packaged (both of these are included in the bug report template for new issues).
