### ISSUE TITLE
[results] Exract regulon blocs from the binarized auc matrix

### ISSUE THREAD

**Issue by akramdi** [aertslab/pySCENIC#211]
Hello, 

This might be a trivial question, but I was wondering how to extract the regulons that form blocs in the binned AUC heatmap, similar to what is shown in Fig13 of the Nature Protocol paper ([here](https://www.nature.com/articles/s41596-020-0336-2))

Here's the figure: 
![Fig13_heatmap](https://user-images.githubusercontent.com/8793228/92623140-2a93d800-f2c6-11ea-8954-496496998ac0.png)

What's the most efficient way to extract those blocs? 

Thanks for the help!

**Comment by bramvds** [comment]
Dear,

This heatmap was generated via a Jupyter notebook -  http://htmlpreview.github.io/?https://github.com/aertslab/SCENICprotocol/blob/master/notebooks/SCENIC%20Protocol%20-%20Case%20study%20-%20Cancer%20data%20sets.html . In summary, the clustered heatmap functionality provided in the seaborn package was used. This revealed blocks of TFs active in certain subset of samples/cells which were visually/manually highlighted in a figure of the Nature Protocols paper. No specific algorithm was used.

Hope this helps.
