### ISSUE TITLE
[results] Running SCENIC after impuation using MAGIC

### ISSUE THREAD

**Issue by saeedfc** [aertslab/pySCENIC#212]
Hi,

I was wondering whether it may be more suited to use an imputed matrix for SCENIC as SCENIC depends on coexpression of genes as a first step. MAGIC, developed at Krishnaswamy Lab seems like an excellent tool for imputation and thereby in correcting the intrinsic sparsity of 10x data. Would you be kind to advise?

https://www.cell.com/cell/fulltext/S0092-8674(18)30724-4
https://github.com/KrishnaswamyLab/MAGIC

Thanks and Kind regards,
Saeed

**Comment by bramvds** [comment]
Dear Saeed,

Although this could technically be done, we did not investigate the effect of imputation on the overall performance of SCENIC. I can only refer to the following publication: Pratapa, A., Jalihal, A., Law, J., Bharadwaj, A., Murali, T. (2020). Benchmarking algorithms for gene regulatory network inference from single-cell transcriptomic data Nature Methods  17(2), 147-154. https://dx.doi.org/10.1038/s41592-019-0690-6 . In this benchmark of GRN inference methods from single-cell transcriptomics data sets, GRNBoost2 was investigated for robustness to dropouts and the assessment was quite good compared to the other methods (Fig 6). To framework BEELINE developed by these authors could be used to investigate the effect of imputation on the performance of GRN inference methods.

Hope this helps,
Bram

**Comment by saeedfc** [comment]
Hi Bram,

Thanks for the suggestion. However, I wanted to know whether pySCENIC can take an input of expression matrix with negative value range? The MAGIC imputation I mentioned generates an imputed matrix with a value range including negative values.
If it does not violate anything fundamental, I could try. 
Thanks and Kind regards,
Saeed
