### ISSUE TITLE
[results] aucell on negative regulons 

### ISSUE THREAD

**Issue by leonard9338** [aertslab/pySCENIC#215]
Hello,
I have a question regarding AUCell scores of negative regulons.
I understand that the higher the expression of the factor targets in the cell, the higher the score.
So for negative regulons, low scores should be considered as marking "active" negative regulons?
Thanks,

Léonard

**Comment by cflerin** [comment]
Hi @leonard9338 ,

I guess you are talking about repressing TFs that are negatively correlated with the target gene expression. But the AUCell score works the same way for all types of regulons: high AUCell scores indicate high biological activity for that regulon in a given cell. The distinction of repressing/activating regulons is done based on the TF-gene expression correlation and doesn't affect the AUCell score.
