### ISSUE TITLE
[BUG] Download reference data directly from web 

### ISSUE THREAD

**Issue by Beyondvisible** [aertslab/pySCENIC#218]
Hello, I want to download reference data directly from scenic web and I followed the following commands as pySCENIC tutorial describes.

feather_database_url='https://resources.aertslab.org/cistarget/databases/homo_sapiens/hg38/refseq_r80/mc9nr/gene_based/hg38__refseq-r80__10kb_up_and_down_tss.mc9nr.feather'
feather_database="${feather_database_url##*/}"
wget "${feather_database_url}"

However, I failed in wget "${feather_database_url}"
When I run the command < wget "${feather_database_url}" >, the error message below popped up.

  File "<ipython-input-75-2a2c070a8125>", line 1
    wget "${feather_database_url}"
                                 ^
SyntaxError: invalid syntax

- pySCENIC version: 0.10.3
- Installation method: Pip
- Run environment: Jupyter notebook
- OS: Windows
- Package versions: 
alabaster==0.7.12
anaconda-client==1.7.2
anaconda-navigator==1.9.12
anaconda-project==0.8.3
anndata==0.7.4
arboreto==0.1.5
asn1crypto==0.24.0
astroid==2.2.5
astropy==3.2.1
atomicwrites==1.3.0
attrs==19.1.0
Babel==2.7.0
backcall==0.1.0
backports.os==0.1.1
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.7.1
bitarray==0.9.3
bkcharts==0.2
bleach==3.1.0
bokeh==1.2.0
boltons==20.2.1
boto==2.49.0
Bottleneck==1.2.1
certifi==2020.6.20
cffi==1.12.3
chardet==3.0.4
Click==7.0
cloudpickle==1.2.1
clyent==1.2.2
colorama==0.4.1
comtypes==1.1.7
conda==4.8.5
conda-build==3.20.2
conda-package-handling==1.3.11
conda-verify==3.1.1
contextlib2==0.5.5
cryptography==2.7
curl==0.0.1
cycler==0.10.0
Cython==0.29.12
cytoolz==0.10.0
dask==1.0.0
decorator==4.4.2
defusedxml==0.6.0
dill==0.3.2
distributed==1.28.1
docutils==0.14
entrypoints==0.3
et-xmlfile==1.0.1
fastcache==1.1.0
feather-format==0.4.1
filelock==3.0.12
Flask==1.1.1
frozendict==1.2
future==0.18.2
get-version==2.1
gevent==1.4.0
glob2==0.7
greenlet==0.4.15
h5py==2.10.0
heapdict==1.0.0
html5lib==1.0.1
idna==2.8
imageio==2.5.0
imagesize==1.1.0
importlib-metadata==2.0.0
interlap==0.2.6
ipykernel==5.1.1
ipython==7.6.1
ipython-genutils==0.2.0
ipywidgets==7.5.0
isort==4.3.21
itsdangerous==1.1.0
jdcal==1.4.1
jedi==0.13.3
Jinja2==2.10.1
joblib==0.16.0
json5==0.8.4
jsonschema==3.0.1
jupyter==1.0.0
jupyter-client==5.3.1
jupyter-console==6.0.0
jupyter-core==4.5.0
jupyterlab==1.0.2
jupyterlab-server==1.0.0
kb-python==0.24.4
keyring==18.0.0
kiwisolver==1.2.0
lazy-object-proxy==1.4.1
legacy-api-wrap==1.2
libarchive-c==2.8
llvmlite==0.34.0
locket==0.2.0
loompy==3.0.6
louvain==0.7.0
lxml==4.3.4
MarkupSafe==1.1.1
matplotlib==3.3.2
mccabe==0.6.1
menuinst==1.4.16
mistune==0.8.4
mkl-fft==1.0.12
mkl-random==1.0.2
mkl-service==2.0.2
mock==3.0.5
more-itertools==7.0.0
mpmath==1.1.0
msgpack==0.6.1
multipledispatch==0.6.0
multiprocessing-on-dill==3.5.0a4
natsort==7.0.1
navigator-updater==0.2.1
nbconvert==5.5.0
nbformat==4.4.0
networkx==2.5
nltk==3.4.4
nose==1.3.7
notebook==6.0.0
numba==0.51.2
numexpr==2.7.1
numpy==1.19.2
numpy-groupies==0.9.13
numpydoc==0.9.1
olefile==0.46
openpyxl==2.6.2
packaging==20.4
pandas==0.25.3
pandocfilters==1.4.2
parso==0.5.0
partd==1.0.0
path.py==12.0.1
pathlib2==2.3.4
patsy==0.5.1
pep8==1.7.1
pickleshare==0.7.5
Pillow==7.2.0
pkginfo==1.5.0.1
pluggy==0.12.0
ply==3.11
prometheus-client==0.7.1
prompt-toolkit==2.0.9
psutil==5.6.3
py==1.8.0
pyarrow==0.16.0
pycodestyle==2.5.0
pycosat==0.6.3
pycparser==2.19
pycrypto==2.6.1
pycurl==7.43.0.3
pyflakes==2.1.1
Pygments==2.4.2
pylint==2.3.1
pyodbc==4.0.26
pyOpenSSL==19.0.0
pyparsing==2.4.7
pyreadline==2.1
pyrsistent==0.14.11
pyscenic==0.10.3
PySocks==1.7.0
pytest==5.0.1
pytest-arraydiff==0.3
pytest-astropy==0.5.0
pytest-doctestplus==0.3.0
pytest-openfiles==0.3.2
pytest-remotedata==0.3.1
python-dateutil==2.8.1
python-igraph==0.8.2
pytz==2020.1
PyWavelets==1.0.3
pywin32==223
pywinpty==0.5.5
PyYAML==5.1.1
pyzmq==18.0.0
QtAwesome==0.5.7
qtconsole==4.5.1
QtPy==1.8.0
requests==2.22.0
rope==0.14.0
ruamel-yaml==0.15.46
scanpy==1.6.0
scikit-image==0.15.0
scikit-learn==0.23.2
scipy==1.5.2
scvelo==0.2.2
seaborn==0.11.0
Send2Trash==1.5.0
setuptools-scm==4.1.2
simplegeneric==0.8.1
sinfo==0.3.1
singledispatch==3.4.0.3
six==1.15.0
snowballstemmer==1.9.0
sortedcollections==1.1.2
sortedcontainers==2.1.0
soupsieve==1.8
Sphinx==2.1.2
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
sphinxcontrib-websupport==1.1.2
spyder==3.3.6
spyder-kernels==0.5.1
SQLAlchemy==1.3.5
statsmodels==0.12.0
stdlib-list==0.7.0
sympy==1.4
tables==3.6.1
tblib==1.4.0
terminado==0.8.2
testpath==0.4.2
texttable==1.6.3
threadpoolctl==2.1.0
toolz==0.10.0
tornado==6.0.3
tqdm==4.50.0
traitlets==4.3.2
umap-learn==0.4.6
unicodecsv==0.14.1
urllib3==1.24.2
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.15.4
widgetsnbextension==3.5.0
win-inet-pton==1.1.0
win-unicode-console==0.5
wincertstore==0.2
wrapt==1.11.2
xlrd==1.2.0
XlsxWriter==1.1.8
xlwings==0.15.8
xlwt==1.3.0
xmltodict==0.12.0
xxx==0.0.1
zict==1.0.0
zipp==3.2.0
Note: you may need to restart the kernel to use updated packages.

**Comment by cflerin** [comment]
I think you're having some kind of problem with variable substitution in your notebook. You should probably be using wget or curl from the command line to do this instead. You can see the [download instructions here](https://resources.aertslab.org/cistarget/help.html) (use the alternate method if you want to just do a simple download with curl).
