### ISSUE TITLE
Why there are many ribosome protein coding genes in the provided TF list (hs_hgnc_tfs.txt)? [results]

### ISSUE THREAD

**Issue by Pentayouth** [aertslab/pySCENIC#222]
In the provided TF list :
[https://github.com/aertslab/pySCENIC/tree/master/resources/hs_hgnc_tfs.txt](url)
I found many ribosome protein coding genes like: 
MRPL1
MRPL2
MRPS25
RPL6
RPL35
RPP25
RPS4X
RPS6KA5
RPS10
...

Are those genes able to function as transcription factor in human too?
I also found  [https://github.com/aertslab/pySCENIC/tree/master/resources/lambert2018.txt](url) and   [https://github.com/aertslab/pySCENIC/tree/master/resources/hs_hgnc_curated_tfs.txt](url) don't have those genes? Is it safe to consider them as better choices of TF lists?

**Comment by cflerin** [comment]
Hi @Pentayouth ,

Indeed it's maybe a bit strange to have these in there. This list of TFs come from the cisTarget databases, taking the set of all genes annotated as a TF.

Technically you could put any gene you want into the TF list for the GRN step and SCENIC will run. But then this regulon would almost certainly not pass the cisTarget pruning step. So I don't think this could negatively affect an analysis, aside from maybe increasing the run time testing these extra genes. I think it's safe to use any of these TF lists, but it might be best to use the Lambert2018 or curated lists.
