### ISSUE TITLE
target genes in GMT file[results]

### ISSUE THREAD

**Issue by zehualilab** [aertslab/pySCENIC#224]
Thanks for this useful tool! Here is my question:
I extracted the target genes in regulon.csv file and combine genes from different databases into one string character. I checked the relationship of the TFs and their target genes in Pubmed but could not find any results that could verify whether the target genes are regulated by related TFs. So I wonder, in this situation, could these 'target genes' in the regulon.csv file really the target genes? Or are they just predicted?

**Comment by Pentayouth** [comment]
Yes, they are just predicted ones.

**Comment by cflerin** [comment]
Indeed, these are predicted targets using the GRN + cisTarget refinement procedures.
