### ISSUE TITLE
Loom file from pySCENIC to R

### ISSUE THREAD

**Issue by s849** [aertslab/pySCENIC#228]
Hello,

Thank you for generating pySCENIC. I was able to generate loom files from pySCENIC; but I would like to work with it in R version SCENIC. Is there a step-by-step example of how this can be accomplished?

Thank you

**Comment by cflerin** [comment]
Hi @s849 ,

Take a look at [this tutorial](https://rawcdn.githack.com/aertslab/SCENIC/0a4c96ed8d930edd8868f07428090f9dae264705/inst/doc/importing_pySCENIC.html) from R SCENIC.
