### ISSUE TITLE
regulons expression plots 

### ISSUE THREAD

**Issue by justinesjw** [aertslab/pySCENIC#23]
Hello, 

Thanks for the great work on pySCENIC! been using R version and pySCENIC is so much faster! 

Though, I can't seem to find some feature (eg. TSNE, histogram plots) for regulons' expressions that are found in R version of SCENIC. Where can I find them? I may have over looked but may I know where to find the documentation of all the functions available? 

Thanks!
Justine

**Comment by bramvds** [comment]
Dear Justine,

Thanks. Unfortunately these features are not yet available in pySCENIC. I'll put them on the todo list (see Projects).

The best alternative is to use the tool SCope (web and standalone versions are available). You export your analysis as a loom file via the `export2loom` function available in the `pyscenic.export` module and subsequently view and explore the regulons via [SCope](http://scope.aertslab.org/).

Another less convenient solution would be to export the data as JSON and use the visualisation features available in R (this feature was requested in the following issue: 
https://github.com/aertslab/pySCENIC/issues/16).

Hope this helps,
Bram

**Comment by lc822** [comment]
Dear Bram,

I am struggling with generating the loom file from the command line output.

The files I have are:
merged_all_expr_mat.adjacencies.csv (output from pyscenic grn)
regulons.csv (output from pyscenic ctx)
auc_mtx.csv (output from pyscenic aucell)

How can I generate the loom file from this using export2loom or another method, so that I can analyse the results using SCope?

Also, where do I find the AUC thresholds in the command line output?

Many thanks,
Lucy

**Comment by yingyonghui** [comment]
> Dear Bram,
> 
> I am struggling with generating the loom file from the command line output.
> 
> The files I have are:
> merged_all_expr_mat.adjacencies.csv (output from pyscenic grn)
> regulons.csv (output from pyscenic ctx)
> auc_mtx.csv (output from pyscenic aucell)
> 
> How can I generate the loom file from this using export2loom or another method, so that I can analyse the results using SCope?
> 
> Also, where do I find the AUC thresholds in the command line output?
> 
> Many thanks,
> Lucy

@lc822 So have you solved the problem?
I just have the same question to find the AUC thresholds from pySCENIC, and any suggestions would be appreciated!
Thank you!
Ying

**Comment by lc822** [comment]
Hi @yingyonghui, 

Unfortunately I haven't found a solution to this yet, as I am having some problems with the earlier stages of the pySCENIC command line workflow.  

Best,
Lucy

**Comment by yingyonghui** [comment]
Hi @lc822 ,
I used pySCENIC in python interface, and I just found the solutions to get the AUC thresholds. Once you get the AUC matrix,  try the following codes:
`
from pyscenic.binarization import binarize
auc_mtx_bi = binarize(auc_mtx)
`
the variable auc_mtx_bi contains the binary matrix and the corresponding thresholds.
Best wishes!
Ying

**Comment by lc822** [comment]
Perfect, thank you.  I will give this a try now that I have the AUC matrix!
