### ISSUE TITLE
Question for pyscenic grn

### ISSUE THREAD

**Issue by jeongdo801** [aertslab/pySCENIC#231]
Hello, I'm running pySCENIC in the jupyter notebook and having an issue in the pyscenic grn step (syntax Error).
Could you help me resolve this problem?

File "<ipython-input-48-8dfbeb25eade>", line 1
    pyscenic grn --num_workers 20 --output adj.tsv --method grnboost2 PBMC10k_filtered.loom hs_hgnc_tfs.txt
               ^
SyntaxError: invalid syntax

**Comment by onionsci** [comment]
Please tell me how to deal this problem?I have the same question.
