### ISSUE TITLE
Question for the pyscenic grn error

### ISSUE THREAD

**Issue by jeongdo801** [aertslab/pySCENIC#232]
[pySCENIC_error.txt](https://github.com/aertslab/pySCENIC/files/5615691/pySCENIC_error.txt)

Hello, I was trying to run pySCENIC grn with the following commend, but I got error messages like the attachment file...
Could you guide me how I can resolve this issue? Thanks in advance!

 !pyscenic grn --num_workers 20 --output adj.tsv --method grnboost2 PBMC10k_filtered.loom hs_hgnc_tfs.txt

**Comment by cflerin** [comment]
Hi @jeongdo801 ,

There's a lot going on in your logs, but it looks like pySCENIC was ultimately killed by something external (cluster resources manager perhaps?). 

You also get:
```
OSError: [Errno 24] Too many open files
```
you could check and increase your ulimit (`ulimit -n`).

I would also suggest using the multiprocessing implementation of GRNBoost2 unless you really need Dask (see #163 ).
