### ISSUE TITLE
Preprocessing Question- Subsetting Genes[results]

### ISSUE THREAD

**Issue by lothm2014** [aertslab/pySCENIC#233]
Hello,

I am currently running pySCENIC with unfiltered counts data (~250 MB). I am experiencing very long run times using a HPC. Would it be appropriate to subset the genes to those only in the TF text file? Are there any general preprocessing steps recommended prior to running pySCENIC?

Sincerely,
Melanie

**Comment by cflerin** [comment]
Hi @lothm2014 ,

No, I would not do this. Then, you will only be testing TFs vs TFs when your goal is to identify TF targets. The basic filters are:
1. Remove cells that have fewer than a minimum number of genes expressed (or more than an upper threshold)
2. Remove genes that are expressed in very few cells (usually a minimum of ~3 cells)

So you could try increasing the stringency of those filters to decrease the dataset size.
