### ISSUE TITLE
run pyscenic ctx error[BUG]

### ISSUE THREAD

**Issue by Zifeng1995** [aertslab/pySCENIC#236]
**Describe the bug**
When running pysceinc ctx, there was something wrong as follows.
![image](https://user-images.githubusercontent.com/53402047/101980256-28fbf680-3c9f-11eb-9fab-9f455ffe525e.png)

It can output the motif file, but this file seemed incomplete and cannot be used in the next step.

**Comment by cflerin** [comment]
Hi @Zifeng1995 ,

This looks like a jupyter error. You could try running directly from a shell prompt instead (without the `!`). Feel free to reopen if you have further problems.
