### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Doraon666** [aertslab/pySCENIC#24]
hi,
I used pip to install pySCENIC, but it is not installed.  The following error is:

Could not find a version that satisfies the requirement pyarrow==0.8.0 (from pyscenic) (from versions: 0.9.0, 0.10.0, 0.11.0, 0.11.1)
No matching distribution found for pyarrow==0.8.0 (from pyscenic)

**Comment by bramvds** [comment]
Dear,

This should be fixed with the latest release.

Kr,
Bram
