### ISSUE TITLE
Could you upgrade the pandas dependency?

### ISSUE THREAD

**Issue by chansigit** [aertslab/pySCENIC#240]
pyscenic 0.10.4 requires pandas<1.0.0,>=0.20.1
That's really an old pandas release.

other single-cell python packages like anndata, scanpy , relies on a much higher pandas version, e.g.
anndata 0.7.5 requires pandas!=1.1,>=1.0

could you team update the pandas dependencies so that installing pyscenic as well as scanpy would not be problematic?

**Comment by cflerin** [comment]
Yes, this is being worked on. If you need an immediate fix, you can try using the pyscenic dev branch (possibly you'll also have to install a fork of Arboreto (`pip install git+https://github.com/cflerin/arboreto@dev`). I'll close this, and keep #242 since it's more descriptive.
