### ISSUE TITLE
pySCENIC with Batch-corrected Integrated data [results]

### ISSUE THREAD

**Issue by hbandukw** [aertslab/pySCENIC#241]
Hello, 
I have integrated 10 scRNAseq datasets with Seurat using the following vignette: https://satijalab.org/seurat/v3.0/integration.html. I was wondering if it is appropriate to use SCtransform normalized and batch-corrected data with SCENIC? 

The output also includes only the 2000-3000 highly variable genes within the "integrated" assay unless I explicitly ask for all common features between the datasets to be included. This ends up being a memory-exhaustive process, so I was also wondering if using just the HVGs with SCENIC would work?

Any advice on how to apply the SCENIC protocol to "integrated" data would be very helpful and appreciated. Thank you.

**Comment by cflerin** [comment]
Hi @hbandukw ,

Good question. I would highly recommend to use the full dataset if at all possible -- you will likely miss a lot of potential regulon target genes if you only use HGVs. If it's a problem for you to export this data, you could even use a merged dataset that is not batch-corrected, it should still give biologically accurate results as the initial regression step is not overly sensitive to normalization and batch effects.

**Comment by hbandukw** [comment]
Hi @cflerin, 

Thanks for the info, I will use either the merged dataset and/or the full integrated dataset.

**Comment by robertzeibich** [comment]
Hi @cflerin, was there a big difference between the merged and the integrated dataset? Which integration method did you use?
