### ISSUE TITLE
Running SCENIC with encode CHIP-seq tracks[results]

### ISSUE THREAD

**Issue by deevdevil88** [aertslab/pySCENIC#244]
Hello,
I wanted to run my SCENIC analysis with additional CHIP-seq based track information from ENCODE for the fruit fly for example. I was wondering, can this be done on the CLI? if so, where do i get the relevant files from ? Do you have any example CHIP-Seq tracks that one can use?

Best,
Devika

**Comment by cflerin** [comment]
Hi @deevdevil88 ,

Yes, this can be done on the CLI in the same way as using the motif-based databases. In the `ctx` step you would just put in the track database and annotation. You can find track databases on https://resources.aertslab.org/cistarget/ but so far only available for human.

You can also find a tutorial for this [here](http://htmlpreview.github.io/?https://github.com/aertslab/SCENICprotocol/blob/master/notebooks/PBMC10k_SCENIC-protocol-CLI-tracks.html).
