### ISSUE TITLE
AttributeError: module 'numba' has no attribute 'jitclass'

### ISSUE THREAD

**Issue by frucelee** [aertslab/pySCENIC#245]
Dear friends,
When I performed the pyscenic analysis, it show the error as follows,
In [159]: !pyscenic grn {f_loom_path_scenic} {f_tfs} -o adj.csv --num_workers 20
/home/lee/miniconda3/lib/python3.8/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
Traceback (most recent call last):
  File "/home/lee/miniconda3/bin/pyscenic", line 5, in <module>
    from pyscenic.cli.pyscenic import main
  File "/home/lee/miniconda3/lib/python3.8/site-packages/pyscenic/cli/pyscenic.py", line 19, in <module>
    from pyscenic.utils import modules_from_adjacencies, add_correlation
  File "/home/lee/miniconda3/lib/python3.8/site-packages/pyscenic/utils.py", line 6, in <module>
    from .math import masked_rho4pairs
  File "/home/lee/miniconda3/lib/python3.8/site-packages/pyscenic/math.py", line 5, in <module>
    from numba import *
AttributeError: module 'numba' has no attribute 'jitclass'

Do you know how to solve this problem? I try to solve this problem through the idea from https://github.com/Roth-Lab/pyclone-vi/issues/7. But it still doesn't work.
Thanks

**Comment by cflerin** [comment]
Hi @frucelee ,

It seems that this is being caused by a recent release of numba. You can try downgrading, it should fix this. In conda:
```
conda install -c anaconda numba=0.46.0
```
Other versions probably work as well, but this one has been tested. The Docker image also has a compatible version if that is a possibility for you.

**Comment by alexpyattaev** [comment]
Would someone please pull the broken version from PYPI to prevent people from shooting themselves in a foot? Thanks!
