### ISSUE TITLE
how to chose and plot the motif of regulon from the pyscenic motifs.csv of outputed file

### ISSUE THREAD

**Issue by honghh2018** [aertslab/pySCENIC#246]
Hi,
    I wonder the different thing about the motif between  Rscenic and Pyscenic. the R running scenic result give me the motif file 
and the picture but the pyscenic just output the motif.csv table but not plotting the motif like below.
   So, how can i plot the motif that i wish and how to process the pyscenic motif.csv file?

![image](https://user-images.githubusercontent.com/41668708/106090886-31809180-6166-11eb-8ae4-4218eb9dbfa7.png)
   Best,
    hanhuihong

**Comment by cflerin** [comment]
Hi @honghh2018 ,

You could try something from [this notebook](http://htmlpreview.github.io/?https://github.com/aertslab/SCENICprotocol/blob/master/notebooks/PBMC10k_downstream-analysis.html), see the section "Display a motifs table with motif logos" for some ideas on how to get the motif logos.
