### ISSUE TITLE
Error shows using singularity

### ISSUE THREAD

**Issue by frucelee** [aertslab/pySCENIC#249]
Hi friends, when I try to perform the pyscenic analysis using singularity, it shows the error as follows. 
$ singularity run aertslab-pyscenic-0.10.0.sif \
>     pyscenic grn \
>         -o expr_mat.adjacencies.loom \
>         /home/lee/scenic/pbmc10k_unfiltered.loom \
>         /home/lee/scenic/allTFs_mm.txt
/opt/venv/lib/python3.7/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the         default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}

2021-02-01 10:46:04,019 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.

2021-02-01 10:46:06,082 - pyscenic.cli.pyscenic - INFO - Inferring regulatory networks.
/opt/venv/lib/python3.7/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the         default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
preparing dask client
parsing input
/opt/venv/lib/python3.7/site-packages/arboreto/algo.py:214: FutureWarning: Method .as_matrix will be removed in a future version. Use .        values instead.
  expression_matrix = expression_data.as_matrix()
creating dask graph
24 partitions
computing dask graph
'infer_data failed for target Star' Retry (1/10). Failure caused by ValueError("Regression for target gene Star failed. Cause ValueError('Found array with 0 feature(s) (shape=(4620, 0)) while a minimum of 1 is required.').").
'infer_data failed for target Star' Retry (2/10). Failure caused by ValueError("Regression for target gene Star failed. Cause ValueError('Found array with 0 feature(s) (shape=(4620, 0)) while a minimum of 1 is required.').").
'infer_data failed for target Star' Retry (3/10). Failure caused by ValueError("Regression for target gene Star failed. Cause ValueError('Found array with 0 feature(s) (shape=(4620, 0)) while a minimum of 1 is required.').").
'infer_data failed for target Star' Retry (4/10). Failure caused by ValueError("Regression for target gene Star failed. Cause ValueError('Found array with 0 feature(s) (shape=(4620, 0)) while a minimum of 1 is required.').").
'infer_data failed for target Star' Retry (5/10). Failure caused by ValueError("Regression for target gene Star failed. Cause ValueError('Found array with 0 feature(s) (shape=(4620, 0)) while a minimum of 1 is required.').").
'infer_data failed for target Star' Retry (6/10). Failure caused by ValueError("Regression for target gene Star failed. Cause ValueError('Found array with 0 feature(s) (shape=(4620, 0)) while a minimum of 1 is required.').").
'infer_data failed for target Star' Retry (7/10). Failure caused by ValueError("Regression for target gene Star failed. Cause ValueError('Found array with 0 feature(s) (shape=(4620, 0)) while a minimum of 1 is required.').").
'infer_data failed for target Star' Retry (8/10). Failure caused by ValueError("Regression for target gene Star failed. Cause ValueError('Found array with 0 feature(s) (shape=(4620, 0)) while a minimum of 1 is required.').").
'infer_data failed for target Star' Retry (9/10). Failure caused by ValueError("Regression for target gene Star failed. Cause ValueError('Found array with 0 feature(s) (shape=(4620, 0)) while a minimum of 1 is required.').").
'infer_data failed for target Star' Retry (10/10). Failure caused by ValueError("Regression for target gene Star failed. Cause ValueError('Found array with 0 feature(s) (shape=(4620, 0)) while a minimum of 1 is required.').").
distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((<function check_meta at 0x2aaac8218f80>, (<function infer_partial_network at 0x2aaac953c440>, 'GBM', (<class 'dict'>, [['learning_rate', 0.01], ['n_estimators', 5000], ['max_features', 0.1], ['subsample', 0.9]]), array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32), ['Star'], 'Star', array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), False, 25, None), Empty DataFrame
Columns: [TF, target, importance]
Index: [], 'from_delayed'))
kwargs:    {}
Exception: ValueError('Metadata mismatch found in `from_delayed`.\n\nExpected partition of type `DataFrame` but got `NoneType`')

distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://127.0.0.1:33719 remote=tcp://127.0.0.1:35867>
not shutting down client, client was created externally
finished
Traceback (most recent call last):
  File "/opt/venv/bin/pyscenic", line 8, in <module>
    sys.exit(main())
  File "/opt/venv/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 420, in main
    args.func(args)
  File "/opt/venv/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 72, in find_adjacencies_command
    network = method(expression_data=ex_mtx, tf_names=tf_names, verbose=True, client_or_address=client, seed=args.seed)
  File "/opt/venv/lib/python3.7/site-packages/arboreto/algo.py", line 41, in grnboost2
    early_stop_window_length=early_stop_window_length, limit=limit, seed=seed, verbose=verbose)
  File "/opt/venv/lib/python3.7/site-packages/arboreto/algo.py", line 135, in diy
    .compute(graph, sync=True) \
  File "/opt/venv/lib/python3.7/site-packages/distributed/client.py", line 2758, in compute
    result = self.gather(futures)
  File "/opt/venv/lib/python3.7/site-packages/distributed/client.py", line 1822, in gather
    asynchronous=asynchronous,
  File "/opt/venv/lib/python3.7/site-packages/distributed/client.py", line 753, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/distributed/utils.py", line 331, in sync
    six.reraise(*error[0])
  File "/opt/venv/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/venv/lib/python3.7/site-packages/distributed/utils.py", line 316, in f
    result[0] = yield future
  File "/opt/venv/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/opt/venv/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/opt/venv/lib/python3.7/site-packages/distributed/client.py", line 1653, in _gather
    six.reraise(type(exception), exception, traceback)
  File "/opt/venv/lib/python3.7/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/opt/venv/lib/python3.7/site-packages/dask/dataframe/utils.py", line 521, in check_meta
    errmsg))
ValueError: Metadata mismatch found in `from_delayed`.

Expected partition of type `DataFrame` but got `NoneType`

Sorry, I don't know what's happens, and how to solve this problem, do you have some suggestions for me? Thanks
lee

**Comment by reberya** [comment]
I'm having the same issue with the same error readout while using Singularity

**Comment by cflerin** [comment]
Hi @frucelee , @reberya ,

This should be fixed in the new release (pySCENIC `0.11.0`, Arboreto `0.1.6`), can you try updating to the latest version (you can build a new singularity container from Docker Hub).
