### ISSUE TITLE
Installation  failure

### ISSUE THREAD

**Issue by Doraon666** [aertslab/pySCENIC#25]
Hello,
I tried install in by using pip install pyscenic==0.8.10,  but it doesn't work. Then I got the following error:

Failed building wheel for llvmlite
Failed building wheel for numba
Command "D:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Doraon\\AppData\\Local\\Temp\\pip-install-bio4th1b\\llvmlite\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Doraon\AppData\Local\Temp\pip-record-126qydwj\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Doraon\AppData\Local\Temp\pip-install-bio4th1b\llvmlite\

Hoping you can help me, thanks

**Comment by bramvds** [comment]
Dear,

I just released a new version. Because you are working on a windows environment, could you make sure to use a miniconda (https://conda.io/miniconda.html) environment specifically for pyscenic:
```
conda create -n pyscenic python=3.6
activate pyscenic
conda install numba
pip install pyscenic
```
Hope this will resolve your installation issue.

Bram
