### ISSUE TITLE
cisTarget: TF ChIP-seq track collection for mouse?

### ISSUE THREAD

**Issue by ddfishbean** [aertslab/pySCENIC#253]
Hi pySCENIC team,

Thank you for developing such a great tool for the community! I have a question related to the cisTarget databases. I am wondering if there is any TF ChIP-seq track collection for the `mouse` from ENCODE or other databases? I found the TF track collections for `human` and ` fly` but not `mouse`. Is it okay to use the `human` track as a substitution for now? If yes, what kind of problems should I pay attention to? 

Thank you so much!

**Comment by cflerin** [comment]
Hi @ddfishbean ,

Sorry but we haven't compiled a ChIP-seq track database for mouse just yet, we only have drosophila and human so far. I would not substitute the human database personally.

We do have a set of scripts and methods to generate your own database, if this is something you want to try. The instructions are in the initial stages, but you can find them here: https://github.com/aertslab/create_cisTarget_databases
