### ISSUE TITLE
regulon dict

### ISSUE THREAD

**Issue by rojinsafavi** [aertslab/pySCENIC#257]
# creating a dictionary of regulons:
regulons = {}
for i,r in pd.DataFrame(lf.ra.Regulons,index=lf.ra.Gene).iteritems():
    regulons[i] =  list(r[r==1].index.values)

Could you please specify how this regulons dict should look like? I am trying to build it from the regulon file produced by pyscenic.

<img width="903" alt="Screen Shot 2021-02-10 at 8 09 29 AM" src="https://user-images.githubusercontent.com/19545198/107537053-5538d400-6b77-11eb-883b-330e7105e605.png">

I assume that it's a dict with TFs as keys, and targets as a list, but wanted to make sure :-)

**Comment by rojinsafavi** [comment]
I assume that it's a dict with TFs as keys, and targets as a list, but wanted to make sure :-)

**Comment by cflerin** [comment]
The particular table from the screenshot you attached was generated by:
```
from pyscenic.utils import load_motifs

df_motifs = load_motifs('reg.csv')
```

The regulons dictionary from your code snippet is indeed in the format of TF: [target gene 1, target gene 2, ...]
