### ISSUE TITLE
Visualize the result with iregulon

### ISSUE THREAD

**Issue by rojinsafavi** [aertslab/pySCENIC#259]
Hello,
I followed the tutorial, and made the following files:
<img width="694" alt="Screen Shot 2021-02-10 at 8 52 18 AM" src="https://user-images.githubusercontent.com/19545198/107542689-4ce39780-6b7d-11eb-942a-aad5df97e364.png">

Now I would like to visualize this output with iregulon. I looked at the Iregulon tutorial page, but I couldn't find how to visualize pyscenic output there. I uploaded files here. thank you very much!

[ZXDB_module_1.txt](https://github.com/aertslab/pySCENIC/files/5959881/ZXDB_module_1.txt)
[ZXDB_module_2.txt](https://github.com/aertslab/pySCENIC/files/5959882/ZXDB_module_2.txt)
[ZXDB_module_3.txt](https://github.com/aertslab/pySCENIC/files/5959883/ZXDB_module_3.txt)
[ZXDB_module_0.txt](https://github.com/aertslab/pySCENIC/files/5959884/ZXDB_module_0.txt)
[ZXDB_module_4.txt](https://github.com/aertslab/pySCENIC/files/5959885/ZXDB_module_4.txt)
[ZXDB_module_5.txt](https://github.com/aertslab/pySCENIC/files/5959886/ZXDB_module_5.txt)
[ZXDB_regulon.txt](https://github.com/aertslab/pySCENIC/files/5959887/ZXDB_regulon.txt)

**Comment by cflerin** [comment]
Did the link in the tutorial help at all? iRegulon is a separate program that you need to load the cisTarget databases and module file into, then you can explore the TF-target genes interactively.

http://iregulon.aertslab.org/tutorial.html

**Comment by robertzeibich** [comment]
Hi @rojinsafavi, were you able to visualize your results with iregulon?
