### ISSUE TITLE
create() got an unexpected keyword argument 'matrix'

### ISSUE THREAD

**Issue by saeedfc** [aertslab/pySCENIC#26]
I was trying to export my scenic output to Scope using export2loom function. I am hitting an error here. Any help is appreciated!
Thanks in advance

input: 
`export2loom(ex_mtx = ex_matrix, auc_mtx = auc_mtx, regulons = regulons,cell_annotations = cell_anno, out_fname = "myloomfile.loom")`

output

`Traceback (most recent call last):

  File "<ipython-input-50-194535bab4da>", line 2, in <module>
    export2loom(ex_mtx = ex_matrix, auc_mtx = auc_mtx, regulons = regulons,cell_annotations = cell_anno, out_fname = "myloomfile.loom")

  File "C:\Users\r0700093\AppData\Roaming\Python\Python36\site-packages\pyscenic\export.py", line 144, in export2loom
    file_attrs=general_attrs)

TypeError: create() got an unexpected keyword argument 'matrix'`

**Comment by bramvds** [comment]
Dear,

I just released a new version of pyscenic. Could you check if this resolves your issue?

Thanks,
Bram
