### ISSUE TITLE
infer_data failed for target *** during GRN while using Singularity[BUG]

### ISSUE THREAD

**Issue by reberya** [aertslab/pySCENIC#262]
Hello,

First off, thank you for putting out a really interesting program. I'm excited to get this up and running and see what conclusions can be drawn from my data. The issue I am having is similar to #108 where I am unable to complete the GRN step while using Singularity starting with either a loom or csv file. Like was suggested in #108 I have tried downloading the newest docker image, and switching from a loom to csv file. Both of these files were generated in R from a Seurat object using either the `as.loom()` or the `write.csv()` functions.

UPDATE:
While the GRN step does complete - the output adjacencies file is contains only the heading and no subsequent data. I created a [subset of 100 cells](https://drive.google.com/file/d/1NDUJfQ47l8LlIrbYPONktYesYb4MdRHz/view?usp=sharing) of my data that replicates the error.

**Steps to reproduce the behavior**
1. Command run when the error occurred:

```
# Create GRN with loom (not working)
singularity run aertslab-pyscenic-0.11.0.sif \
    pyscenic grn \
        --num_workers 2 \
        -o int/expr_mat.adjacencies.tsv \
	-m grnboost2 \
	--seed 123 \
	--gene_attribute Gene \
	--cell_id_attribute CellID \
        data/loom/spleen_h_d14.loom \
        data/supportFiles/mm_mgi_tfs.txt

# Create GRN with csv (not working)
singularity run aertslab-pyscenic-0.11.0.sif \
    pyscenic grn \
        --num_workers 2 \
        -o int/expr_mat.adjacencies.s_h_14.tsv \
	-m grnboost2 \
	--seed 123 \
	-t \
        data/csv/spleen_h_d14.csv \
        data/supportFiles/mm_mgi_tfs.txt

```

2. Error encountered:

```
2021-02-15 08:16:17,600 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.

2021-02-15 08:16:18,726 - pyscenic.cli.pyscenic - INFO - Inferring regulatory networks.
preparing dask client
parsing input
creating dask graph
2 partitions
computing dask graph
'WARNING: infer_data failed for target Star' Retry (1/10). Failure caused by ValueError('Cleaned TF matrix is empty, skipping inference of target Star.').
'WARNING: infer_data failed for target Star' Retry (2/10). Failure caused by ValueError('Cleaned TF matrix is empty, skipping inference of target Star.').
'WARNING: infer_data failed for target Star' Retry (3/10). Failure caused by ValueError('Cleaned TF matrix is empty, skipping inference of target Star.').
'WARNING: infer_data failed for target Star' Retry (4/10). Failure caused by ValueError('Cleaned TF matrix is empty, skipping inference of target Star.').
'WARNING: infer_data failed for target Star' Retry (5/10). Failure caused by ValueError('Cleaned TF matrix is empty, skipping inference of target Star.').
'WARNING: infer_data failed for target Star' Retry (6/10). Failure caused by ValueError('Cleaned TF matrix is empty, skipping inference of target Star.').
'WARNING: infer_data failed for target Star' Retry (7/10). Failure caused by ValueError('Cleaned TF matrix is empty, skipping inference of target Star.').
'WARNING: infer_data failed for target Star' Retry (8/10). Failure caused by ValueError('Cleaned TF matrix is empty, skipping inference of target Star.').
'WARNING: infer_data failed for target Star' Retry (9/10). Failure caused by ValueError('Cleaned TF matrix is empty, skipping inference of target Star.').
'WARNING: infer_data failed for target Star' Retry (10/10). Failure caused by ValueError('Cleaned TF matrix is empty, skipping inference of target Star.').
not shutting down client, client was created externally
finished
...
```

**Expected behavior**
Completion of the GRN step.

**Please complete the following information:**
- pySCENIC version: 0.11.0
- Installation method: Singularity
- Run environment: Command line on interactive HPC session
- OS: CentOS 7

Thank you very much,
Ryan

**Comment by cflerin** [comment]
Hi @reberya ,

I don't see any errors here actually, unless there is something you've left out. Your update does suggest that you got an output from this step, if that's the case then I think it completed correctly. These messages that you see are just warnings that no inference could be completed for a particular TF that you've put in the TFs file. I've seen this issue most frequently in very small datasets, or where you are requesting inference to be performed on only a single TF.
