### ISSUE TITLE
cell type specific regulator analysis: Z-score heatmap

### ISSUE THREAD

**Issue by s849** [aertslab/pySCENIC#263]
Hi,

Thank you for generating pySCENIC, I have found it very useful in my studies. I have a question with regards to the heat map generated by cell type specific regulator analysis. In the heat map containing Z-score (below), what is the white value mean? How to interpret this white color?
<img width="1034" alt="Screen Shot 2021-02-15 at 4 00 28 PM" src="https://user-images.githubusercontent.com/47041278/108003286-240d3900-6fa7-11eb-8948-9293b94afc0f.png">

**Comment by cflerin** [comment]
Hi @s849 ,

You don't include the code you are using to generate this plot, but it seems that your lowest value shown here is 3.0 -- so it would make sense that only those scores >= 3.0 are being shown on the plot.
