### ISSUE TITLE
prune2df

### ISSUE THREAD

**Issue by rojinsafavi** [aertslab/pySCENIC#264]
Hello!
I am losing some important TFs after running prune2df. I was wondering if you have any suggestions of what hyper parameters I should tune?

Thank you!

**Comment by c5creative** [comment]
Not sure if related, but 0.11.0 was just released and I saw this in the release notes:
```
Updated cisTarget:
   * Fix for metadata mismatch in ctx prune2df step
```
Good luck!

**Comment by cflerin** [comment]
Hi @rojinsafavi,

You could try lowering the NES threshold in the `prune2df` function. I would first make the threshold very permissive to see what kind of score your TFs get, then investigate further why they are low. For testing you could do this with only the modules associated with your interesting TFs.

For more of a manual approach you could load the modules for each of your TFs into iRegulon and explore the targets and enrichment that way (see the very bottom of [this notebook](http://htmlpreview.github.io/?https://github.com/aertslab/SCENICprotocol/blob/master/notebooks/PBMC10k_downstream-analysis.html) for an example on this).

**Comment by rojinsafavi** [comment]
Thank you very much @cflerin 
I lowered the NES value, and for that specific TF I got the following results ( I attached here).

As it is clear the NES score is lower than 3 for this TF. Could you please elaborate on how I can investigate this low score?
Thank you very much

<img width="477" alt="Screen Shot 2021-02-17 at 8 52 08 AM" src="https://user-images.githubusercontent.com/19545198/108238142-7b252200-70fd-11eb-8bf4-5e7e3a045685.png">
<img width="176" alt="Screen Shot 2021-02-17 at 8 52 21 AM" src="https://user-images.githubusercontent.com/19545198/108238152-7d877c00-70fd-11eb-8bb2-a71bf96e4647.png">
