### ISSUE TITLE
annotation databases used for the run[results]

### ISSUE THREAD

**Issue by deevdevil88** [aertslab/pySCENIC#266]
Hi!
i was wondering, if i include two different ranking databases during the pySCENIC ctx step, which have either 10kb UP and down of TSS or 500bp up and 100 down annotations, then does pySCENIC incorporate both sets of annotations when it does the motif enrichment and target pruning, or choses the best option? 

if it chooses the best option, how exactly is that done or if both sets of annotations are used , how exactly is the decision made if the target gene is enriched for a particular TF motif or not and is this information written out as part of the analysis?

Thanks
Devika

**Comment by rojinsafavi** [comment]
@cflerin I was wondering if you could elaborate in the question above?

**Comment by cflerin** [comment]
The regulons are created for each enriched and annotated feature for each database, and then subsequently aggregated. The most enriched annotated motif (by NES) is taken for the overall score. The target genes are merged if there are multiple modules with the same TF. You can find this information in the regulons file (if written to disk) or table, in the 'Context' column. For each TF, it will list the database used, how this module was generated from the grn (top50, etc.) and whether this is activating or repressing (only activating kept by default). Hope that helps...
