### ISSUE TITLE
cli pyscenic ctx error [BUG]

### ISSUE THREAD

**Issue by rlittman16** [aertslab/pySCENIC#275]
I am trying to run CLI pcyscenic ctx, and have run into some problems. Once I added no_pruning, the tool ran for a while, but had the following error. 

**Steps to reproduce the behavior**
1. Command run when the error occurred:
2. 
```
pyscenic ctx test.tsv \
        data/feather_databases/mm9-500bp-upstream-10species.mc9nr.feather data/feather_databases/mm9-500bp-upstream-7species.mc9nr.feather data/feather_databases/mm9-tss-centered-10kb-10species.mc9nr.feather data/feather_databases/mm9-tss-centered-10kb-7species.mc9nr.feather data/feather_databases/mm9-tss-centered-5kb-10species.mc9nr.feather data/feather_databases/mm9-tss-centered-5kb-7species.mc9nr.feather \
        --annotations_fname data/motifs-v9-nr.hgnc-m0.001-o0.0.tbl \
        --expression_mtx_fname data/dge.1.MG.csv \
        --output reg.csv \
        --mask_dropouts \
        -t \
        --no_pruning
...
```

2. Error encountered:

```
Traceback (most recent call last):
  File "/home/russell/miniconda3/envs/scenic/bin/pyscenic", line 8, in <module>
    sys.exit(main())
  File "/home/russell/miniconda3/envs/scenic/lib/python3.8/site-packages/pyscenic/cli/pyscenic.py", line 485, in main
    args.func(args)
  File "/home/russell/miniconda3/envs/scenic/lib/python3.8/site-packages/pyscenic/cli/pyscenic.py", line 191, in prune_targets_command
    df_motifs = calc_func(dbs, modules, motif_annotations_fname,
  File "/home/russell/miniconda3/envs/scenic/lib/python3.8/site-packages/pyscenic/prune.py", line 379, in find_features
    return add_motif_url(prune2df(rnkdbs, signatures, motif_annotations_fname,
  File "/home/russell/miniconda3/envs/scenic/lib/python3.8/site-packages/pyscenic/utils.py", line 326, in add_motif_url
    df[("Enrichment", COLUMN_NAME_MOTIF_URL)] = list(map(partial(urljoin, base=base_url), df.index.get_level_values(COLUMN_NAME_MOTIF_ID)))
TypeError: urljoin() got multiple values for argument 'base'
...
```

**Comment by cflerin** [comment]
Please include the requested information from the bug report template, it's difficult to help without this:

- pySCENIC version: [e.g. 0.10.0, use `pyscenic -h` at the command line]
- Installation method: [e.g. Conda, Pip, Docker, Singularity]
- Run environment: [e.g. Jupyter notebook, CLI, Nextflow, HPC script]
- OS: [e.g. Ubuntu]
- Package versions: [obtain using `pip freeze`, `conda list`, or skip this if using Docker/Singularity]:

```
...
```

**Comment by rlittman16** [comment]
sorry about that!

I am using pyscenic 0.11.0 on ubuntu CLI using conda. 

Here are the packages versions:

# packages in environment at /home/russell/miniconda3/envs/scenic:
#
# Name                    Version                   Build  Channel
aiohttp                   3.7.4                    pypi_0    pypi
arboreto                  0.1.6                    pypi_0    pypi
argon2-cffi               20.1.0           py38h7b6447c_1    anaconda
async-timeout             3.0.1                    pypi_0    pypi
async_generator           1.10                       py_0    anaconda
attrs                     20.2.0                     py_0    anaconda
backcall                  0.2.0                      py_0    anaconda
bleach                    3.2.1                      py_0    anaconda
boltons                   20.2.1                   pypi_0    pypi
ca-certificates           2020.10.14                    0    anaconda
cached-property           1.5.2                    pypi_0    pypi
certifi                   2020.6.20                py38_0    anaconda
cffi                      1.14.3           py38he30daa8_0    anaconda
chardet                   4.0.0                    pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
cloudpickle               1.6.0                    pypi_0    pypi
cytoolz                   0.11.0                   pypi_0    pypi
dask                      2.11.0                   pypi_0    pypi
dbus                      1.13.18              hb2f20db_0    anaconda
decorator                 4.4.2                      py_0    anaconda
defusedxml                0.6.0                      py_0    anaconda
dill                      0.3.2                    pypi_0    pypi
distributed               2.11.0                   pypi_0    pypi
entrypoints               0.3                      py38_0    anaconda
expat                     2.2.10               he6710b0_2    anaconda
fontconfig                2.13.0               h9420a91_0    anaconda
freetype                  2.10.4               h5ab3b9f_0    anaconda
frozendict                1.2                      pypi_0    pypi
fsspec                    0.8.4                    pypi_0    pypi
glib                      2.56.2               hd408876_0    anaconda
gst-plugins-base          1.14.0               hbbd80ab_1    anaconda
gstreamer                 1.14.0               hb453b48_1    anaconda
h5py                      3.0.0                    pypi_0    pypi
heapdict                  1.0.1                    pypi_0    pypi
icu                       58.2                 he6710b0_3    anaconda
idna                      2.10                     pypi_0    pypi
importlib-metadata        2.0.0                      py_1    anaconda
importlib_metadata        2.0.0                         1    anaconda
interlap                  0.2.7                    pypi_0    pypi
ipykernel                 5.3.4            py38h5ca1d4c_0    anaconda
ipython                   7.18.1           py38h5ca1d4c_0    anaconda
ipython_genutils          0.2.0                    py38_0    anaconda
ipywidgets                7.5.1                      py_1    anaconda
jedi                      0.17.2                   py38_0    anaconda
jinja2                    2.11.2                     py_0    anaconda
joblib                    0.17.0                   pypi_0    pypi
jpeg                      9b                   habf39ab_1    anaconda
jsonschema                3.2.0                      py_2    anaconda
jupyter                   1.0.0                    py38_7    anaconda
jupyter_client            6.1.7                      py_0    anaconda
jupyter_console           6.2.0                      py_0    anaconda
jupyter_core              4.6.3                    py38_0    anaconda
jupyterlab_pygments       0.1.2                      py_0    anaconda
ld_impl_linux-64          2.33.1               h53a641e_7    anaconda
libedit                   3.1.20191231         h14c3975_1    anaconda
libffi                    3.3                  he6710b0_2    anaconda
libgcc-ng                 9.1.0                hdf63c60_0    anaconda
libpng                    1.6.37               hbc83047_0    anaconda
libsodium                 1.0.18               h7b6447c_0    anaconda
libstdcxx-ng              9.1.0                hdf63c60_0    anaconda
libuuid                   1.0.3                h1bed415_2    anaconda
libxcb                    1.14                 h7b6447c_0    anaconda
libxml2                   2.9.10               hb55368b_3    anaconda
llvmlite                  0.34.0                   pypi_0    pypi
loompy                    3.0.6                    pypi_0    pypi
markupsafe                1.1.1            py38h7b6447c_0    anaconda
mistune                   0.8.4           py38h7b6447c_1000    anaconda
msgpack                   1.0.0                    pypi_0    pypi
multidict                 5.1.0                    pypi_0    pypi
multiprocessing-on-dill   3.5.0a4                  pypi_0    pypi
nbclient                  0.5.1                      py_0    anaconda
nbconvert                 6.0.7                    py38_0    anaconda
nbformat                  5.0.8                      py_0    anaconda
ncurses                   6.2                  he6710b0_1    anaconda
nest-asyncio              1.4.1                      py_0    anaconda
networkx                  2.5                      pypi_0    pypi
notebook                  6.1.4                    py38_0    anaconda
numba                     0.51.2                   pypi_0    pypi
numpy                     1.19.3                   pypi_0    pypi
numpy-groupies            0.9.13                   pypi_0    pypi
openssl                   1.1.1h               h7b6447c_0    anaconda
packaging                 20.4                       py_0    anaconda
pandas                    0.25.3                   pypi_0    pypi
pandoc                    2.11                 hb0f4dca_0    anaconda
pandocfilters             1.4.2                    py38_1    anaconda
parso                     0.7.0                      py_0    anaconda
pcre                      8.44                 he6710b0_0    anaconda
pexpect                   4.8.0                    py38_0    anaconda
pickleshare               0.7.5                 py38_1000    anaconda
pip                       20.2.4                   py38_0    anaconda
prometheus_client         0.8.0                      py_0    anaconda
prompt-toolkit            3.0.8                      py_0    anaconda
prompt_toolkit            3.0.8                         0    anaconda
psutil                    5.7.3                    pypi_0    pypi
ptyprocess                0.6.0                    py38_0    anaconda
pyarrow                   0.16.0                   pypi_0    pypi
pycparser                 2.20                       py_2    anaconda
pygments                  2.7.1                      py_0    anaconda
pyparsing                 2.4.7                      py_0    anaconda
pyqt                      5.9.2            py38h05f1152_4    anaconda
pyrsistent                0.17.3           py38h7b6447c_0    anaconda
pyscenic                  0.11.0                   pypi_0    pypi
python                    3.8.5                h7579374_1    anaconda
python-dateutil           2.8.1                      py_0    anaconda
pytz                      2020.1                   pypi_0    pypi
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     19.0.2           py38he6710b0_1    anaconda
qt                        5.9.7                h5867ecd_1    anaconda
qtconsole                 4.7.7                      py_0    anaconda
qtpy                      1.9.0                      py_0    anaconda
readline                  8.0                  h7b6447c_0    anaconda
requests                  2.25.1                   pypi_0    pypi
scikit-learn              0.23.2                   pypi_0    pypi
scipy                     1.5.3                    pypi_0    pypi
send2trash                1.5.0                    py38_0    anaconda
setuptools                50.3.0           py38hb0f4dca_1    anaconda
sip                       4.19.24          py38he6710b0_0    anaconda
six                       1.15.0                     py_0    anaconda
sortedcontainers          2.2.2                    pypi_0    pypi
sqlite                    3.33.0               h62c20be_0    anaconda
tblib                     1.7.0                    pypi_0    pypi
terminado                 0.9.1                    py38_0    anaconda
testpath                  0.4.4                      py_0    anaconda
threadpoolctl             2.1.0                    pypi_0    pypi
tk                        8.6.10               hbc83047_0    anaconda
toolz                     0.11.1                   pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
tqdm                      4.51.0                   pypi_0    pypi
traitlets                 5.0.5                      py_0    anaconda
typing-extensions         3.7.4.3                  pypi_0    pypi
umap-learn                0.4.6                    pypi_0    pypi
urllib3                   1.26.3                   pypi_0    pypi
wcwidth                   0.2.5                      py_0    anaconda
webencodings              0.5.1                    py38_1    anaconda
wheel                     0.35.1                     py_0    anaconda
widgetsnbextension        3.5.1                    py38_0    anaconda
xz                        5.2.5                h7b6447c_0    anaconda
yarl                      1.6.3                    pypi_0    pypi
zeromq                    4.3.3                he6710b0_3    anaconda
zict                      2.0.0                    pypi_0    pypi
zipp                      3.3.1                      py_0    anaconda
zlib                      1.2.11               h7b6447c_3    anaconda

**Comment by cflerin** [comment]
@rlittman16, thanks for the info. I don't usually use `--no_pruning`, but it seems that there was a previous bug causing this that somehow got regressed in the latest release. It should now be fixed in the `dev` branch, you could install this and try running your command again.

**Comment by rlittman16** [comment]
Without no_pruning I don't get any results. I tried the new branch, and after an hour it still said 0% complete. Does that make sense?

**Comment by rlittman16** [comment]
Ok its working now. Thanks!

**Comment by whtns** [comment]
do you have any advice about running this dev branch with docker?
