### ISSUE TITLE
getting the coexpression matrix

### ISSUE THREAD

**Issue by rojinsafavi** [aertslab/pySCENIC#277]
Is it possible to obtain the co-expression matrix calculated by pyscenic?

**Comment by cflerin** [comment]
Hi @rojinsafavi ,

The co expression matrix is the result of the first step of pySCENIC (GRN inference). If you run the command line version it is written to a file (`adj.tsv` or similar), if you run interactively it is stored in a variable and you'll have to write it to disk yourself.
