### ISSUE TITLE
[BUG]'AttributableError <class 'loompy.attribute_manager.AttributeManager'>' object has no attribute 'Celltype_Garnett'

### ISSUE THREAD

**Issue by olaush** [aertslab/pySCENIC#280]
**Describe the bug**
I was trying to repoduce the results of the Pyscenic tutorial and after getting the "intergrated-output.loom" file, I tried to continue with the downstream analysis in the second  tutorial but I encountered this error  **<class 'loompy.attribute_manager.AttributeManager'>' object has no attribute 'Celltype_Garnett'** 

When I tried to read the integrated_output.loom file, I didn't see the the Celltype_Garnett and I'm worried because I followed the steps of the tutorial in toto. 

**Steps to reproduce the behavior**
# cell annotations from the loom column attributes:
cellAnnot = pd.concat(
    [
        pd.DataFrame( lf.ca.Celltype_Garnett, index=lf.ca.CellID ),
        pd.DataFrame( lf.ca.ClusterID, index=lf.ca.CellID ),
        pd.DataFrame( lf.ca.Louvain_clusters_Scanpy, index=lf.ca.CellID ),
        pd.DataFrame( lf.ca.Percent_mito, index=lf.ca.CellID ),
        pd.DataFrame( lf.ca.nGene, index=lf.ca.CellID ),
        pd.DataFrame( lf.ca.nUMI, index=lf.ca.CellID ),
    ],
    axis=1
)
cellAnnot.columns = [
 'Celltype_Garnett',
 'ClusterID',
 'Louvain_clusters_Scanpy',
 'Percent_mito',
 'nGene',
 'nUMI']

```python
...
```

2. Error encountered:

```pytb
...'AttributableError <class 'loompy.attribute_manager.AttributeManager'>' object has no attribute 'Celltype_Garnett'
```

**Please complete the following information:**
- pySCENIC version: 0.11.0
- Installation method: pip
- Run environment:  Jupyter notebook
- Package versions: [obtain using `pip freeze`, `conda list`, or skip this if using Docker/Singularity]:

**Comment by cflerin** [comment]
Hi @olaush ,

Take a look at the discussion here: aertslab/SCENICprotocol/issues/16 -- I think this will cover your question. The Garnett tool was run separately (for PBMCs). You can either skip it, or download the annotation file and add it yourself. Feel free to reopen if you still have problems.

**Comment by olaush** [comment]
Thanks. It worked. However, the heatmap is entirely black


[PBMC10k_cellType-heatmap-top5.pdf](https://github.com/aertslab/pySCENIC/files/6212776/PBMC10k_cellType-heatmap-top5.pdf)
