### ISSUE TITLE
[results] Is using a sparse count matrix more time intensive than a dense one during the GRN inference step?

### ISSUE THREAD

**Issue by fbrundu** [aertslab/pySCENIC#281]
Hi,

I have a large matrix of counts (55k cells per 20k genes), which is taking the `grn` step several days to run.
Since the sparse matrix support has been added to pyscenic, I used it during this step to reduce memory consumption.
However, I wanted to understand if this has been found to add a considerable computing overhead (like a 1.5-2x increase in runtime) with respect to dense matrices.

Thanks,
Francesco

**Comment by cflerin** [comment]
Hi @fbrundu ,

Yes, actually I have noticed this, although not as severe as you report. I should add a note on this to the docs. In a matrix of 10280 cells and 20292 genes, I get a run time for GRNBoost2 (using 20 workers) of:
- 95 minutes (dense)
- 102 minutes (sparse)

So about a 10% increase. It could be that it depends on the number of non-zero values in your matrix. In this case I have ~90% zero values.

**Comment by fbrundu** [comment]
Thanks, @cflerin. I wonder if time complexity increases linearly with the number of cells.
For now, I think I can close my question. Thanks.
