### ISSUE TITLE
How to run pyscenic with RDS file

### ISSUE THREAD

**Issue by olaush** [aertslab/pySCENIC#282]
How can I use RDS file containing annotated cells to run pyscenic  analysis. I have tried to look for a way to convert the RDS file to a loom file but nothing is forthcoming. Thanks

**Comment by cflerin** [comment]
Hi @olaush ,

Did you already find [SCopeLoomR](https://github.com/aertslab/SCopeLoomR)? I think you should be able to do a conversion to loom following the methods in [the tutorial](http://htmlpreview.github.io/?https://github.com/aertslab/SCopeLoomR/blob/master/vignettes/SCopeLoomR_tutorial.nb.html).
