### ISSUE TITLE
saving of regulons as txt files

### ISSUE THREAD

**Issue by jk86754** [aertslab/pySCENIC#29]
Hi,

What is the easiest way to save the modules/regulons generated by pyscenic as a txt file? Eventually, I would like to export them in some way so i can read them into R.

thank you!

Joe

**Comment by bramvds** [comment]
Hi Joe,

Can I refer you to this solved issue: https://github.com/aertslab/pySCENIC/issues/16 ?

The command line option for regulon export as JSON is already available. You can use the following R code snippet to load these regulons into your R environment:

```
library(jsonlite)
regs <- read_json('regulons.json', simplify = T)
```

Kindest regards,
Bram
