### ISSUE TITLE
The dockerfile question

### ISSUE THREAD

**Issue by honghh2018** [aertslab/pySCENIC#293]
Hi, Developer
     I want to build the pyscenic docker myself, and i confuse how to set the initial parameter when get start with pyscenic docker like you post in docker hub line command lying below:
    docker run -it --rm \
    -v /path/to/data:/scenicdata \
    aertslab/pyscenic:[version] pyscenic ctx \
        /scenicdata/expr_mat.adjacencies.tsv \
        /scenicdata/hg19-tss-centered-5kb-7species.mc9nr.feather \
        /scenicdata/hg19-tss-centered-10kb-7species.mc9nr.feather \
        --annotations_fname /scenicdata/motifs-v9-nr.hgnc-m0.001-o0.0.tbl \
        --expression_mtx_fname /scenicdata/expr_mat.tsv \
        --mode "dask_multiprocessing" \
        --output /scenicdata/regulons.csv \
        --num_workers 6
how to write the dockerfile to put the  --annotations_fname and --mode and --output parameter  into realization as in the docker startup.
Best,
hanhuihong

**Comment by cflerin** [comment]
Hi @honghh2018 ,

To build the docker image yourself, you would clone the github repo, change to the pyscenic directory, and do something like `docker build -t mypyscenicbuild:0.11.2 .  --build-arg version=0.11.2` (the build arg points pip to the correct pySCENIC version in the Dockerfile).

But I don't know what you mean about the parameters you mention and the Dockerfile. If you're asking about the volume mounts, it's much easier to just map your host path to the same path inside the container. This way you can just use the normal paths to files on your machine (i.e. `-v /data:/data`).

See [here](https://pyscenic.readthedocs.io/en/latest/installation.html#docker), or below...
```
docker run -it --rm \
    -v /data:/data \
    aertslab/pyscenic:0.11.2 pyscenic ctx \
        /data/expr_mat.adjacencies.tsv \
        /data/hg19-tss-centered-5kb-7species.mc9nr.feather \
        /data/hg19-tss-centered-10kb-7species.mc9nr.feather \
        --annotations_fname /data/motifs-v9-nr.hgnc-m0.001-o0.0.tbl \
        --expression_mtx_fname /data/expr_mat.tsv \
        --mode "dask_multiprocessing" \
        --output /data/regulons.csv \
        --num_workers 6
```

**Comment by honghh2018** [comment]
Sorry to this ambiguous questioning.
      To be blunt, i saw you docker startup with the command parameter "--expression_mtx_fname or --annotations_fname" and so on. i am wonder how can i make docker images myself also add the "--expression_mtx_fname or --annotations_fname"  to accept a data that i want to. Do the --build-arg can realize this work? 
  Hope the advice.
Best,
hanhuihong

**Comment by cflerin** [comment]
@honghh2018 ,

Ah ok I think I see what you mean now. These parameters don't have anything to do with Docker, they are pySCENIC parameters. We are just using the Docker image as a way to package the pySCENIC code and dependencies. So you run pySCENIC exactly the same way in a Conda environment as with Docker, except that you don't need the `docker run -it --rm -v /data:/data aertslab/pyscenic:0.11.2` prefix with Conda. 

You can already pass in your own input files to any of the pySCENIC parameters like `--expression_mtx_fname`, and you don't need to build your own Docker image to do this. For example, you have an expression matrix on your local machine at `/mnt/data/expression.tsv`, you might run this (leaving out some params here):
```
docker run -it --rm \
    -v /mnt/data:/mnt/data \
    aertslab/pyscenic:0.11.2 pyscenic ctx \
        ...
        --expression_mtx_fname /mnt/data/expression.tsv \
        ...
```
