### ISSUE TITLE
[BUG] error importing export2loom

### ISSUE THREAD

**Issue by saeedfc** [aertslab/pySCENIC#303]
**Describe the bug**
while importing export2loom, error appears which is about probably a version change with scikit.learn
**Steps to reproduce the behavior**
1. Command run when the error occurred:
from pyscenic.export import export2loom```python
...
```

2. Error encountered:
Traceback (most recent call last):

  File "<ipython-input-23-8fc67d17df74>", line 1, in <module>
    from pyscenic.export import export2loom

  File "/home/luna.kuleuven.be/u0119129/anaconda3/envs/pyscenic_11/lib/python3.7/site-packages/pyscenic/export.py", line 7, in <module>
    from sklearn.manifold.t_sne import TSNE

ModuleNotFoundError: No module named 'sklearn.manifold.t_sne'


import pyscenic.export
Traceback (most recent call last):

  File "<ipython-input-24-57c947a0421d>", line 1, in <module>
    import pyscenic.export

  File "/home/luna.kuleuven.be/u0119129/anaconda3/envs/pyscenic_11/lib/python3.7/site-packages/pyscenic/export.py", line 7, in <module>
    from sklearn.manifold.t_sne import TSNE

ModuleNotFoundError: No module named 'sklearn.manifold.t_sne'```pytb
...
```

**Expected behavior**
Load export2loom module without error
**Please complete the following information:**
- pySCENIC version: 0.11.0; scikit-learn version 0.24.1
- Installation method: Conda
- Run environment: spyder within a conda environment.
- OS:Ubuntu
- Package versions: [obtain using `pip freeze`, `conda list`, or skip this if using Docker/Singularity]:
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
aiohttp                   3.7.3                    pypi_0    pypi
alabaster                 0.7.12                   pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
arboreto                  0.1.6                    pypi_0    pypi
astroid                   2.5                      pypi_0    pypi
async-generator           1.10                     pypi_0    pypi
async-timeout             3.0.1                    pypi_0    pypi
atomicwrites              1.4.0                    pypi_0    pypi
attrs                     20.3.0                   pypi_0    pypi
autopep8                  1.5.5                    pypi_0    pypi
babel                     2.9.0                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
black                     20.8b1                   pypi_0    pypi
bleach                    3.3.0                    pypi_0    pypi
bokeh                     2.3.0                    pypi_0    pypi
boltons                   20.2.1                   pypi_0    pypi
ca-certificates           2021.1.19            h06a4308_0  
cached-property           1.5.2                    pypi_0    pypi
certifi                   2020.12.5        py37h06a4308_0  
cffi                      1.14.5                   pypi_0    pypi
chardet                   3.0.4                    pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
cloudpickle               1.6.0                    pypi_0    pypi
cryptography              3.4.6                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
cytoolz                   0.11.0                   pypi_0    pypi
dask                      2021.2.0                 pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
defusedxml                0.6.0                    pypi_0    pypi
diff-match-patch          20200713                 pypi_0    pypi
dill                      0.3.3                    pypi_0    pypi
distributed               2021.2.0                 pypi_0    pypi
docutils                  0.16                     pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
flake8                    3.8.4                    pypi_0    pypi
frozendict                1.2                      pypi_0    pypi
fsspec                    0.8.7                    pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
heapdict                  1.0.1                    pypi_0    pypi
helpdev                   0.7.1                    pypi_0    pypi
idna                      2.10                     pypi_0    pypi
imagesize                 1.2.0                    pypi_0    pypi
importlib-metadata        3.7.0                    pypi_0    pypi
interlap                  0.2.7                    pypi_0    pypi
intervaltree              3.1.0                    pypi_0    pypi
ipykernel                 5.5.0                    pypi_0    pypi
ipython                   7.20.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
isort                     5.7.0                    pypi_0    pypi
jedi                      0.17.2                   pypi_0    pypi
jeepney                   0.6.0                    pypi_0    pypi
jinja2                    2.11.3                   pypi_0    pypi
joblib                    1.0.1                    pypi_0    pypi
jsonschema                3.2.0                    pypi_0    pypi
jupyter-client            6.1.11                   pypi_0    pypi
jupyter-core              4.7.1                    pypi_0    pypi
jupyterlab-pygments       0.1.2                    pypi_0    pypi
keyring                   22.0.1                   pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
lazy-object-proxy         1.5.2                    pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
llvmlite                  0.35.0                   pypi_0    pypi
locket                    0.2.1                    pypi_0    pypi
loompy                    3.0.6                    pypi_0    pypi
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.3.4                    pypi_0    pypi
mccabe                    0.6.1                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
msgpack                   1.0.2                    pypi_0    pypi
multidict                 5.1.0                    pypi_0    pypi
multiprocessing-on-dill   3.5.0a4                  pypi_0    pypi
mypy-extensions           0.4.3                    pypi_0    pypi
nbclient                  0.5.2                    pypi_0    pypi
nbconvert                 6.0.7                    pypi_0    pypi
nbformat                  5.1.2                    pypi_0    pypi
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.5.1                    pypi_0    pypi
networkx                  2.5                      pypi_0    pypi
numba                     0.52.0                   pypi_0    pypi
numpy                     1.20.1                   pypi_0    pypi
numpy-groupies            0.9.13                   pypi_0    pypi
numpydoc                  1.1.0                    pypi_0    pypi
openssl                   1.1.1j               h27cfd23_0  
packaging                 20.9                     pypi_0    pypi
pandas                    1.2.2                    pypi_0    pypi
pandocfilters             1.4.3                    pypi_0    pypi
parso                     0.7.0                    pypi_0    pypi
partd                     1.1.0                    pypi_0    pypi
pathspec                  0.8.1                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    8.1.0                    pypi_0    pypi
pip                       21.0.1           py37h06a4308_0  
pluggy                    0.13.1                   pypi_0    pypi
prompt-toolkit            3.0.16                   pypi_0    pypi
psutil                    5.8.0                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pyarrow                   0.16.0                   pypi_0    pypi
pycodestyle               2.6.0                    pypi_0    pypi
pycparser                 2.20                     pypi_0    pypi
pydocstyle                5.1.1                    pypi_0    pypi
pyflakes                  2.2.0                    pypi_0    pypi
pygments                  2.8.0                    pypi_0    pypi
pylint                    2.7.1                    pypi_0    pypi
pyls-black                0.4.6                    pypi_0    pypi
pyls-spyder               0.3.2                    pypi_0    pypi
pynndescent               0.5.2                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyqt5                     5.12.3                   pypi_0    pypi
pyqt5-sip                 12.8.1                   pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.17.3                   pypi_0    pypi
pyscenic                  0.11.0                   pypi_0    pypi
python                    3.7.9                h7579374_0  
python-dateutil           2.8.1                    pypi_0    pypi
python-jsonrpc-server     0.4.0                    pypi_0    pypi
python-language-server    0.36.2                   pypi_0    pypi
pytz                      2021.1                   pypi_0    pypi
pyxdg                     0.27                     pypi_0    pypi
pyyaml                    5.4.1                    pypi_0    pypi
pyzmq                     22.0.3                   pypi_0    pypi
qdarkstyle                2.8.1                    pypi_0    pypi
qtawesome                 1.0.2                    pypi_0    pypi
qtconsole                 5.0.2                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
readline                  8.1                  h27cfd23_0  
regex                     2020.11.13               pypi_0    pypi
requests                  2.25.1                   pypi_0    pypi
rope                      0.18.0                   pypi_0    pypi
rtree                     0.9.7                    pypi_0    pypi
scikit-learn              0.24.1                   pypi_0    pypi
scipy                     1.6.1                    pypi_0    pypi
secretstorage             3.3.1                    pypi_0    pypi
setuptools                52.0.0           py37h06a4308_0  
six                       1.15.0                   pypi_0    pypi
snowballstemmer           2.1.0                    pypi_0    pypi
sortedcontainers          2.3.0                    pypi_0    pypi
sphinx                    3.5.1                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    1.0.3                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.4                    pypi_0    pypi
spyder                    4.2.2                    pypi_0    pypi
spyder-kernels            1.10.2                   pypi_0    pypi
sqlite                    3.33.0               h62c20be_0  
tblib                     1.7.0                    pypi_0    pypi
testpath                  0.4.4                    pypi_0    pypi
textdistance              4.2.1                    pypi_0    pypi
threadpoolctl             2.1.0                    pypi_0    pypi
three-merge               0.1.1                    pypi_0    pypi
tk                        8.6.10               hbc83047_0  
toml                      0.10.2                   pypi_0    pypi
toolz                     0.11.1                   pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
tqdm                      4.57.0                   pypi_0    pypi
traitlets                 5.0.5                    pypi_0    pypi
typed-ast                 1.4.2                    pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
ujson                     4.0.2                    pypi_0    pypi
umap-learn                0.5.1                    pypi_0    pypi
urllib3                   1.26.3                   pypi_0    pypi
watchdog                  1.0.2                    pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0  
wrapt                     1.12.1                   pypi_0    pypi
wurlitzer                 2.0.1                    pypi_0    pypi
xz                        5.2.5                h7b6447c_0  
yapf                      0.30.0                   pypi_0    pypi
yarl                      1.6.3                    pypi_0    pypi
zict                      2.0.0                    pypi_0    pypi
zipp                      3.4.0                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3  ```
...
```

**Comment by cflerin** [comment]
At some point, this import from sklearn changed from
```
from sklearn.manifold.t_sne import TSNE
```
to
```
from sklearn.manifold import TSNE
```
pySCENIC requires `scikit-learn>=0.22.2`, which should be compatible with the new import.
