### ISSUE TITLE
[BUG]pyscenic ctx: error: argument database_fname: can't open ' --annotations_fname': [Errno 2] No such file or directory: ' --annotations_fname'

### ISSUE THREAD

**Issue by lxwang326** [aertslab/pySCENIC#307]
when run the command
!pyscenic ctx {ADJACENCIES_FNAME} {DBS_PARAM} \ --annotations_fname {MOTIF_ANNOTATIONS_FNAME} \ --expression_mtx_fname {COUNTS_QC_MTX_FNAME} \ --output {MOTIFS_FNAME} \ --num_workers 26

encount the error 
usage: pyscenic ctx [-h] [-o OUTPUT] [-n] [--chunk_size CHUNK_SIZE]
                    [--mode {custom_multiprocessing,dask_multiprocessing,dask_cluster}]
                    [-a] [-t] [--rank_threshold RANK_THRESHOLD]
                    [--auc_threshold AUC_THRESHOLD]
                    [--nes_threshold NES_THRESHOLD]
                    [--min_orthologous_identity MIN_ORTHOLOGOUS_IDENTITY]
                    [--max_similarity_fdr MAX_SIMILARITY_FDR]
                    --annotations_fname ANNOTATIONS_FNAME
                    [--num_workers NUM_WORKERS]
                    [--client_or_address CLIENT_OR_ADDRESS]
                    [--thresholds THRESHOLDS [THRESHOLDS ...]]
                    [--top_n_targets TOP_N_TARGETS [TOP_N_TARGETS ...]]
                    [--top_n_regulators TOP_N_REGULATORS [TOP_N_REGULATORS ...]]
                    [--min_genes MIN_GENES]
                    [--expression_mtx_fname EXPRESSION_MTX_FNAME]
                    [--mask_dropouts] [--cell_id_attribute CELL_ID_ATTRIBUTE]
                    [--gene_attribute GENE_ATTRIBUTE] [--sparse]
                    module_fname database_fname [database_fname ...]
pyscenic ctx: error: argument database_fname: can't open ' --annotations_fname': [Errno 2] No such file or directory: ' --annotations_fname'

can anyone help？

**Comment by c5creative** [comment]
Not pySCENIC maintainer, but the error is telling you that it's attempting to read a file called `--annotations_fname`, instead of using that as a parameter name and opening `{MOTIF_ANNOTATIONS_FNAME}`. 

Have you tried converting your command to hard-coded values and running that directly on command line?
```
!pyscenic ctx {ADJACENCIES_FNAME} {DBS_PARAM} \ --annotations_fname {MOTIF_ANNOTATIONS_FNAME} \ --expression_mtx_fname {COUNTS_QC_MTX_FNAME} \ --output {MOTIFS_FNAME} \ --num_workers 26
```

**Comment by xiandxing** [comment]
I got the same problem above.
And finally I found that we just need to change every `\ --` like `\ --annotations_fname` into `\--annotations_fname`, it works. Every blank space Deletion. I hope my advice make sense to u too.

**Comment by ghuls** [comment]
`\` at the end of the line allow you to split one line over multiple lines (bash feature).

This is the same as:
```
pyscenic ctx {ADJACENCIES_FNAME} {DBS_PARAM} \
 --annotations_fname {MOTIF_ANNOTATIONS_FNAME} \
 --expression_mtx_fname {COUNTS_QC_MTX_FNAME} \
 --output {MOTIFS_FNAME} \
 --num_workers 26
```

This:
```
pyscenic ctx {ADJACENCIES_FNAME} {DBS_PARAM} --annotations_fname {MOTIF_ANNOTATIONS_FNAME} --expression_mtx_fname {COUNTS_QC_MTX_FNAME}  --output {MOTIFS_FNAME}  --num_workers 26
```

**Comment by cflerin** [comment]
In the original question (@lxwang326 ), running:
```
!pyscenic ctx {ADJACENCIES_FNAME} {DBS_PARAM} \ --annotations_fname {MOTIF_ANNOTATIONS_FNAME} \ --expression_mtx_fname {COUNTS_QC_MTX_FNAME} \ --output {MOTIFS_FNAME} \ --num_workers 26
```
gives:
```
pyscenic ctx: error: argument database_fname: can't open ' --annotations_fname': [Errno 2] No such file or directory: ' --annotations_fname'
```
I think that the `DBS_PARAM` variable in the notebook must have been set to an empty string, so it was interpreting `--annotations_fname` as the file name for the db.
