### ISSUE TITLE
Differences between R and python versions

### ISSUE THREAD

**Issue by jk86754** [aertslab/pySCENIC#31]
Hi,

I have a general question about the python version of the SCENIC workflow. I have been using the R version for several months now and recently started using pySCENIC. If i interpret the output of pySCENIC correctly, it generates several regulons for the same transcription factor. As far as i can tell, this is not the case in the R version (regulon-transcription factor pairs are unique). Would you guys mind explaining this difference please? I am just curious as to how to interpret pySCENIC output.

Additionally, related: what is the relationship between 'importance' generated by grnboost2 and 'weight' generated by GENIE3?

Thank you,

Joe

**Comment by bramvds** [comment]
Dear Joe,

Thank you for your questions.

Regarding your first question, pySCENIC adheres to the same maxim "one TF - one regulon". Maybe you are referring to the results you get after running the command line version of pyscenic (or using the function ```pyscenic.prune2df```)? This table gives you multiple enriched motifs (and their associated target genes) for a transcription factor. You need to apply the function ```transform.df2regulons``` to combine them into regulons. You can also use the command line version setting ```--output_type``` to ```json```. Hope this helps.

This code snippet might also help to transform the CSV output to regulon objects in python.
```
import os
from pyscenic.utils import load_motifs
from pyscenic.transform import df2regulons

RESOURCES_FOLDER = "/resources/zeisel_et_al/"
MOTIFS_FNAME = os.path.join(RESOURCES_FOLDER, "zeisel_et_al.motifs.csv")
motifs = load_motifs(MOTIFS_FNAME)
regulons = df2regulons(motifs)
```

For the second question, I kindly request you to best this question on the arboreto package (https://github.com/tmoerman/arboreto). pySCENIC relies on this package for GRNBoost2. GENIE3 and GRNBoost2 both implement a tree-based regression per target gene approach. GENIE3 relies on Random Forests while GRNBoost2 uses Gradient Boosted Trees. For more information on the 'variable importance measure' I kindly refer you to the eponymous section in: Huynh-Thu, V. A., Irrthum, A., Wehenkel, L. & Geurts, P. Inferring regulatory networks from expression data using tree-based methods. PLoS ONE 5, (2010). The manuscript that covers GRNBoost2 has recently been published in Bioinformatics: Moerman, T. et al. GRNBoost2 and Arboreto: efficient and scalable inference of gene regulatory networks. Bioinformatics (2018). doi:10.1093/bioinformatics/bty916

Kindest regards,
Bram
