### ISSUE TITLE
Error in Proceeding with Dimensionality Reduction Plots

### ISSUE THREAD

**Issue by strawberry789** [aertslab/pySCENIC#310]
According to this tutorial for downstream pyScenic analyses:
https://github.com/aertslab/SCENICprotocol/blob/master/notebooks/PBMC10k_downstream-analysis.ipynb

I followed the steps as written in the section "Extract relevant data from the integrated loom file"

Then I continued with the section "Dimensionality reduction plots."  However, `adata` is needed, so I went back to the section "Alternately, we can load this data into a scanpy.AnnData object," but I'm getting an error after:
`adata.obs.drop( ['Embedding','Embeddings_X','Embeddings_Y','RegulonsAUC'], axis=1, inplace=True )`, which gives:

`TypeError                                 Traceback (most recent call last)
<ipython-input-35-8e6673e2c6a8> in <module>
      2 
      3 # drop the embeddings and extra attributes from the obs object
----> 4 adata.obs.drop( ['Embedding','Embeddings_X','Embeddings_Y','RegulonsAUC'], axis=1, inplace=True )

/expt/joyce/tools/miniconda3/lib/python3.8/site-packages/pandas/util/_decorators.py in wrapper(*args, **kwargs)
    309                     stacklevel=stacklevel,
    310                 )
--> 311             return func(*args, **kwargs)
    312 
    313         return wrapper

/expt/joyce/tools/miniconda3/lib/python3.8/site-packages/pandas/core/frame.py in drop(self, labels, axis, index, columns, level, inplace, errors)
   4899                 weight  1.0     0.8
   4900         """
-> 4901         return super().drop(
   4902             labels=labels,
   4903             axis=axis,

/expt/joyce/tools/miniconda3/lib/python3.8/site-packages/pandas/core/generic.py in drop(self, labels, axis, index, columns, level, inplace, errors)
   4145         for axis, labels in axes.items():
   4146             if labels is not None:
-> 4147                 obj = obj._drop_axis(labels, axis, level=level, errors=errors)
   4148 
   4149         if inplace:

/expt/joyce/tools/miniconda3/lib/python3.8/site-packages/pandas/core/generic.py in _drop_axis(self, labels, axis, level, errors)
   4181             else:
   4182                 new_axis = axis.drop(labels, errors=errors)
-> 4183             result = self.reindex(**{axis_name: new_axis})
   4184 
   4185         # Case for non-unique axis

/expt/joyce/tools/miniconda3/lib/python3.8/site-packages/pandas/util/_decorators.py in wrapper(*args, **kwargs)
    322         @wraps(func)
    323         def wrapper(*args, **kwargs) -> Callable[..., Any]:
--> 324             return func(*args, **kwargs)
    325 
    326         kind = inspect.Parameter.POSITIONAL_OR_KEYWORD

/expt/joyce/tools/miniconda3/lib/python3.8/site-packages/pandas/core/frame.py in reindex(self, *args, **kwargs)
   4765         kwargs.pop("axis", None)
   4766         kwargs.pop("labels", None)
-> 4767         return super().reindex(**kwargs)
   4768 
   4769     @deprecate_nonkeyword_arguments(version=None, allowed_args=["self", "labels"])

/expt/joyce/tools/miniconda3/lib/python3.8/site-packages/pandas/core/generic.py in reindex(self, *args, **kwargs)
   4807 
   4808         # perform the reindex on the axes
-> 4809         return self._reindex_axes(
   4810             axes, level, limit, tolerance, method, fill_value, copy
   4811         ).__finalize__(self, method="reindex")

/expt/joyce/tools/miniconda3/lib/python3.8/site-packages/pandas/core/frame.py in _reindex_axes(self, axes, level, limit, tolerance, method, fill_value, copy)
   4584         columns = axes["columns"]
   4585         if columns is not None:
-> 4586             frame = frame._reindex_columns(
   4587                 columns, method, copy, level, fill_value, limit, tolerance
   4588             )

/expt/joyce/tools/miniconda3/lib/python3.8/site-packages/pandas/core/frame.py in _reindex_columns(self, new_columns, method, copy, level, fill_value, limit, tolerance)
   4629             new_columns, method=method, level=level, limit=limit, tolerance=tolerance
   4630         )
-> 4631         return self._reindex_with_indexers(
   4632             {1: [new_columns, indexer]},
   4633             copy=copy,

/expt/joyce/tools/miniconda3/lib/python3.8/site-packages/pandas/core/generic.py in _reindex_with_indexers(self, reindexers, fill_value, copy, allow_dups)
   4872 
   4873             # TODO: speed up on homogeneous DataFrame objects
-> 4874             new_data = new_data.reindex_indexer(
   4875                 index,
   4876                 indexer,

/expt/joyce/tools/miniconda3/lib/python3.8/site-packages/pandas/core/internals/managers.py in reindex_indexer(self, new_axis, indexer, axis, fill_value, allow_dups, copy, consolidate, only_slice)
    670 
    671         if axis == 0:
--> 672             new_blocks = self._slice_take_blocks_ax0(
    673                 indexer, fill_value=fill_value, only_slice=only_slice
    674             )

/expt/joyce/tools/miniconda3/lib/python3.8/site-packages/pandas/core/internals/managers.py in _slice_take_blocks_ax0(self, slice_or_indexer, fill_value, only_slice)
    813                             blocks.append(nb)
    814                     else:
--> 815                         nb = blk.take_nd(taker, axis=0, new_mgr_locs=mgr_locs)
    816                         blocks.append(nb)
    817 

/expt/joyce/tools/miniconda3/lib/python3.8/site-packages/pandas/core/internals/blocks.py in take_nd(self, indexer, axis, new_mgr_locs, fill_value)
   1143             allow_fill = True
   1144 
-> 1145         new_values = algos.take_nd(
   1146             values, indexer, axis=axis, allow_fill=allow_fill, fill_value=fill_value
   1147         )

/expt/joyce/tools/miniconda3/lib/python3.8/site-packages/pandas/core/array_algos/take.py in take_nd(arr, indexer, axis, fill_value, allow_fill)
    106 
    107     arr = np.asarray(arr)
--> 108     return _take_nd_ndarray(arr, indexer, axis, fill_value, allow_fill)
    109 
    110 

/expt/joyce/tools/miniconda3/lib/python3.8/site-packages/pandas/core/array_algos/take.py in _take_nd_ndarray(arr, indexer, axis, fill_value, allow_fill)
    123         indexer = ensure_platform_int(indexer)
    124 
--> 125     indexer, dtype, fill_value, mask_info = _take_preprocess_indexer_and_fill_value(
    126         arr, indexer, fill_value, allow_fill
    127     )

/expt/joyce/tools/miniconda3/lib/python3.8/site-packages/pandas/core/array_algos/take.py in _take_preprocess_indexer_and_fill_value(arr, indexer, fill_value, allow_fill)
    524 
    525     if not allow_fill:
--> 526         dtype, fill_value = arr.dtype, arr.dtype.type()
    527         mask_info = None, False
    528     else:

TypeError: void() takes exactly 1 positional argument (0 given)`

How can I solve this situation and return to dimensionality reduction plots?

Thanks.

**Comment by cflerin** [comment]
hey @strawberry789 ,

This is describing how to load the pySCENIC output with Scanpy, and generate new dimensionality reductions from the AUC matrix instead of the standard approach using highly variable genes. So it's necessary to do some trickery to make that happen (dropping the existing embeddings, forcing it to use the AUC matrix). If you're not starting from the pySCENIC output loom, you probably won't have these columns and will get this error. You can check with `adata.obs.columns`, for instance.
