### ISSUE TITLE
AUCell error: no 'split' - Seurat loom file conversion 

### ISSUE THREAD

**Issue by strawberry789** [aertslab/pySCENIC#311]
I created a loom file from a Seurat object.  I ran the pyScenic commands successfully (GRNBoost2 and Regulon prediction) until I reach the AUCell step.  

My command was: 
`!pyscenic aucell \
    file.loom \
    reg.csv \
    --output pyscenic_output.loom \
    --num_workers 20`

And the error is:
`AttributeError: 'numpy.ndarray' object has no attribute 'split'`

My original seurat object is already clustered.  So can I actually skip the AUCell step?  And how to generate the SCope compatible file?

Thank you!

**Comment by owenwilkins** [comment]
were you able to find a solution for this. I am experiencing the same issue with the most current version of pyscenic, run using singukarity, and using a loom object created in seurat (v4.1.1)
