### ISSUE TITLE
adata from seurat object

### ISSUE THREAD

**Issue by strawberry789** [aertslab/pySCENIC#312]
I converted a seurat object into a loom file using `as.loom()`

I successfully performed grn, ctx and aucell using this loom file, but whenever there are functions that require adata (e.g. concatenate embeddings), I don't have this adata, aka `name 'adata' is not defined`

How do I generate this adata with a seurat object?

Thanks.

**Comment by strawberry789** [comment]
I successfully converted a Seurat object to a h5ad file to use as adata.  I tried one dataset, and things ran smoothly.  However, when I tried to repeat with another dataset (object), I get an error:

`AttributeError: 'NoneType' object has no attribute 'CellID'`

(I got this error after running the `concatenate embeddings` commands.  I removed tsne because my Seurat object didn't run tsne.  Here is the code:

umapDF = pd.DataFrame(adata.obsm['X_umap'], columns=['_X', '_Y'])

Embeddings_X = pd.DataFrame( index=lf.ca.CellID )
Embeddings_X = pd.concat( [
        pd.DataFrame(adata.obsm['X_umap'],index=adata.obs.index)[0] ,
        #pd.DataFrame(adata.obsm['X_pca'],index=adata.obs.index)[0] ,
        #dr_tsne['X'] ,
        dr_umap['X']
    ], sort=False, axis=1, join='outer' )
Embeddings_X.columns = ['1','2']  #,'3','4'

Embeddings_Y = pd.DataFrame( index=lf.ca.CellID )
Embeddings_Y = pd.concat( [
        pd.DataFrame(adata.obsm['X_umap'],index=adata.obs.index)[1] ,
        #pd.DataFrame(adata.obsm['X_pca'],index=adata.obs.index)[1] ,
        #dr_tsne['Y'] ,
        dr_umap['Y']
    ], sort=False, axis=1, join='outer' )
Embeddings_Y.columns = ['1','2']   #,'3','4'

**Comment by cflerin** [comment]
Hey @strawberry789 , You should be able to load the pySCENIC loom file in Scanpy with `sc.read_loom`.
