### ISSUE TITLE
[BUG] Issues with workers/dask - pySCENIC not working

### ISSUE THREAD

**Issue by fouerghi** [aertslab/pySCENIC#314]
I am having issues running pySCENIC. I have attempted to set up a conda environment to use it, as well as using the Docker and Singularity images. I am still getting the following errors when running the grn part of the script.

2021-08-05 17:04:15,761 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.

2021-08-05 17:04:24,956 - pyscenic.cli.pyscenic - INFO - Inferring regulatory networks.
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.scheduler - ERROR - Couldn't gather keys {'finalize-dc3dc6e36a9e8076a3b034d8407946e5': ['tcp://127.0.0.1:41234']} state: ['waiting'] workers: ['tcp://127.0.0.1:41234']
NoneType: None
distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://127.0.0.1:41234'], finalize-dc3dc6e36a9e8076a3b034d8407946e5
NoneType: None
distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {'finalize-dc3dc6e36a9e8076a3b034d8407946e5': ('tcp://127.0.0.1:41234',)}
distributed.nanny - WARNING - Restarting worker
preparing dask client
parsing input
creating dask graph
20 partitions
computing dask graph
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.scheduler - ERROR - Couldn't gather keys {'finalize-dc3dc6e36a9e8076a3b034d8407946e5': ['tcp://127.0.0.1:46797']} state: ['waiting'] workers: ['tcp://127.0.0.1:46797']
NoneType: None
distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://127.0.0.1:46797'], finalize-dc3dc6e36a9e8076a3b034d8407946e5
NoneType: None
distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {'finalize-dc3dc6e36a9e8076a3b034d8407946e5': ('tcp://127.0.0.1:46797',)}
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.scheduler - ERROR - Couldn't gather keys {'finalize-dc3dc6e36a9e8076a3b034d8407946e5': ['tcp://127.0.0.1:45718']} state: ['waiting'] workers: ['tcp://127.0.0.1:45718']
NoneType: None
distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://127.0.0.1:45718'], finalize-dc3dc6e36a9e8076a3b034d8407946e5
NoneType: None
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {'finalize-dc3dc6e36a9e8076a3b034d8407946e5': ('tcp://127.0.0.1:45718',)}
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.scheduler - ERROR - Couldn't gather keys {'finalize-dc3dc6e36a9e8076a3b034d8407946e5': ['tcp://127.0.0.1:33865']} state: ['waiting'] workers: ['tcp://127.0.0.1:33865']
NoneType: None
distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://127.0.0.1:33865'], finalize-dc3dc6e36a9e8076a3b034d8407946e5
NoneType: None
distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {'finalize-dc3dc6e36a9e8076a3b034d8407946e5': ('tcp://127.0.0.1:33865',)}
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.scheduler - ERROR - Couldn't gather keys {'finalize-dc3dc6e36a9e8076a3b034d8407946e5': ['tcp://127.0.0.1:43295']} state: ['waiting'] workers: ['tcp://127.0.0.1:43295']
NoneType: None
distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://127.0.0.1:43295'], finalize-dc3dc6e36a9e8076a3b034d8407946e5
NoneType: None
distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {'finalize-dc3dc6e36a9e8076a3b034d8407946e5': ('tcp://127.0.0.1:43295',)}
distributed.nanny - WARNING - Restarting worker

Any help with solving this?

**Comment by dandata123-tech** [comment]
I meet the same problems,if  you get some idea ,please tell me

**Comment by fouerghi** [comment]
@dandata123-tech I have not been able to resolve this issue but I found a workaround. I use [this script](https://github.com/aertslab/pySCENIC/blob/master/src/pyscenic/cli/arboreto_with_multiprocessing.py) that they provided but I had to make changes when it came to the dask and arboreto versions I was using to make them compatible and I also removed the workers part where they create adjs and just used a regular map instead of an imap.

**Comment by dandata123-tech** [comment]
Thanks a lot,I will have a try



发自我的iPhone


------------------ Original ------------------
From: fouerghi ***@***.***&gt;
Date: Thu,Aug 12,2021 3:22 AM
To: aertslab/pySCENIC ***@***.***&gt;
Cc: Dan ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [aertslab/pySCENIC] [BUG] Issues with workers/dask - pySCENIC not working (#314)





 
@dandata123-tech I have not been able to resolve this issue but I found a workaround. I use this script that they provided but I had to make changes when it came to the dask and arboreto versions I was using to make them compatible and I also removed the workers part where they create adjs and just used a regular map instead of an imap.

**Comment by fouerghi** [comment]
I was able to get the script to work with multiprocessing which cuts down the running time by a lot. I used starmap instead of imap and made sure to include the necessary arguments to feed into the run partial inference function. 

`    target_gene_indices_1 = target_gene_indices(gene_names,target_genes='all')
    with Pool(args.num_workers) as p:
          adjs = list(
              tqdm.tqdm(
                  p.starmap(run_infer_partial_network, zip(target_gene_indices_1,repeat(gene_names),repeat(ex_matrix),repeat(tf_matrix),repeat(tf_matrix_gene_names))),
                  total=len(gene_names),
              )
          )`


and in the run infer partial network function, I added the arguments gene_names, ex_matrix, tf_matrix and tf_matrix_gene_names.

It works!

**Comment by cflerin** [comment]
The original error seems to be a memory limitation. Try lowering the number of workers. Alternately, use the multiprocessing script as mentioned above. Feel free to re-open if there are still issues.

**Comment by hyjforesight** [comment]
hello @fouerghi 
Appreciate it if you could share your codes with us. I didn't get it how to revise the codes based on your responses above. We met the dask error when running `pyscenic grn` and switched to `arboreto_with_multiprocessing.py', but met the `NameError: name 'gene_names' is not defined`.
```python
!arboreto_with_multiprocessing.py \
    {f_loom_path_scenic} \
    {Mouse_TFS_FNAME} \
    --method grnboost2 \
    --output {ADJACENCIES_FNAME} \
    --num_workers 16

Loaded expression matrix of 14081 cells and 14881 genes in 2.6268911361694336 seconds...
Loaded 1721 TFs...
starting grnboost2 using 16 processes...
Wall time: 24.3 s

  0%|          | 0/14881 [00:00<?, ?it/s]
  0%|          | 0/14881 [00:13<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\Park_Lab\anaconda3\envs\HYJ_py38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Park_Lab\anaconda3\envs\HYJ_py38\Scripts\arboreto_with_multiprocessing.py", line 101, in run_infer_partial_network
    target_gene_name = gene_names[target_gene_index]
NameError: name 'gene_names' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Park_Lab\anaconda3\envs\HYJ_py38\Scripts\arboreto_with_multiprocessing.py", line 147, in <module>
    adjs = list(
  File "C:\Users\Park_Lab\anaconda3\envs\HYJ_py38\lib\site-packages\tqdm\std.py", line 1180, in __iter__
    for obj in iterable:
  File "C:\Users\Park_Lab\anaconda3\envs\HYJ_py38\lib\multiprocessing\pool.py", line 868, in next
    raise value
  File "C:\Users\Park_Lab\anaconda3\envs\HYJ_py38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Park_Lab\anaconda3\envs\HYJ_py38\Scripts\arboreto_with_multiprocessing.py", line 101, in run_infer_partial_network
    target_gene_name = gene_names[target_gene_index]
NameError: name 'gene_names' is not defined
```
