### ISSUE TITLE
[results] Ranking regulons for importance/significance <--> what do values in add.csv mean?

### ISSUE THREAD

**Issue by Jintram** [aertslab/pySCENIC#320]
Many thanks for the nice work. I just finished reading the Van de Sande paper, and have performed a regulon analysis on our data. 

One thing I would like to do is to assess which regulons are most important in our dataset. I don't really have prior knowledge that can be used to do this (except e.g. linking regulons to clustering of cells by other methods). 

Currently, since we have five independent samples, I'm ranking regulons by giving more importance to regulons that come up in multiple samples. But presumably there is also some scoring of the signifance of the regulons in the algorithm, to determine whether something is considered a regulon or not in the first place (or is this solely based on whether TF-related genes, ie NES>3, can be found?). In the vd Sande paper, it's well described how genes are linked to regulons, but this aspect doesn't really become clear to me.

I was hoping you can answer some questions relating to this:

[QUESTION1] As described in your paper, TF<>gene interactions are determined using multiple settings/strategies, e.g. varying the DNA region used for motif detection, or filtering genes based on their rank vs. based on weights ("topXperTarget", "weight>90%" resp). These methods lead to different sets of genes, as I can see from my add.csv file. How are the final gene sets determined for the regulons given that there are multiple options?  

[QUESTION2] add.csv lists the parameters

- AUC
- NES
- RankAtMax
- MotifSimilarityQvalue

According to your paper, NES are normalized AUC values. If I understand correctly, AUC/NES is used to gauge the confidence of linking the gene set to a specific TF. I assume MotifSimilarityQvalue does something similar (reflects false discovery tendency of the motif?). I'm not sure about RankAtMax, but I'm guessing it also values TF<>gene set linkage, as Box2 in vd Sande describes the ranking process of genes identified by CHIP to underly the AUC scoring. 
So my question is: am I correct in saying all these measures aim to quantify the validity of linking a specific TF to a specific set of genes?

[QUESTION 3] Is there any way to rank regulons themselves by supposed importance or significance? E.g. the % variance in the data they describe.

Many thanks in advance!!
Martijn.

**Comment by SeppeDeWinter** [comment]
Hi Martijn

Thank you for your kind words.

I've broken down your questions below and tried to provide an answer.

> _One thing I would like to do is to assess which regulons are most important in our dataset. I don't really have prior knowledge that can be used to do this (except e.g. linking regulons to clustering of cells by other methods)._

Have you looked at the Regulon Specificity Score (RSS) which is included in the pySCENIC package, this method tries to score all regulons for their specificity for each cluster. You can find an example of this in the downstream analysis tutorial: http://htmlpreview.github.io/?https://github.com/aertslab/SCENICprotocol/blob/master/notebooks/PBMC10k_downstream-analysis.html

> _Currently, since we have five independent samples, I'm ranking regulons by giving more importance to regulons that come up in multiple samples. But presumably there is also some scoring of the signifance of the regulons in the algorithm, to determine whether something is considered a regulon or not in the first place (or is this solely based on whether TF-related genes, ie NES>3, can be found?). In the vd Sande paper, it's well described how genes are linked to regulons, but this aspect doesn't really become clear to me._

Genes are linked to regulons using the following procedure:
First genes are linked to TFs solely based on gene expression. This is done using gradient boosting (GRNBoost) or random forrest (Genie3). You can think of this like a non-linear regression in which we try to predict the expression of the TF (across cells) by the expression of all genes (across cells). Using this method each gene gets an importance for their ability to predict the TF's expression.

Next, these links are binarised/thresholded using several methods (e.g. taking the top target genes per TF by importance score, ...).

Finaly, regulons are build by running motif enrichment analysis on the set of target genes (cistarget, see: http://nar.oxfordjournals.org/content/early/2015/04/28/nar.gkv395.long and http://nar.oxfordjournals.org/content/40/15/e114.long for more information). After this only the genes with the highest motif score are kept (called the leading edge).  This is the pruning step of pySCENIC.

> _[QUESTION1] As described in your paper, TF<>gene interactions are determined using multiple settings/strategies, e.g. varying the DNA region used for motif detection, or filtering genes based on their rank vs. based on weights ("topXperTarget", "weight>90%" resp). These methods lead to different sets of genes, as I can see from my add.csv file. How are the final gene sets determined for the regulons given that there are multiple options?_ 

This is indeed correct, like I stated above as well. The motif enrichment analysis is run independently on all of these gene sets, afterwards regulons of the same TF (but different thresholding methods) are simply merged.

>_[QUESTION2] add.csv lists the parameters (AUC, NES, RankAtMax, MotifSimilarityQvalue)
According to your paper, NES are normalized AUC values. If I understand correctly, AUC/NES is used to gauge the confidence of linking the gene set to a specific TF. I assume MotifSimilarityQvalue does something similar (reflects false discovery tendency of the motif?). I'm not sure about RankAtMax, but I'm guessing it also values TF<>gene set linkage, as Box2 in vd Sande describes the ranking process of genes identified by CHIP to underly the AUC scoring.
So my question is: am I correct in saying all these measures aim to quantify the validity of linking a specific TF to a specific set of genes?_

Your not entirely about these metrics. All of these metrics are in fact related to the motif enrichment analysis.

To explain these I have to explain how the motif enrichment analysis works.

For cistarget we have a big database which contains scores for a large sets of motifs and or TF-ChIP-seq peaks (features) in regions surrounding the TSS of all genes.  To asses wether a feature is enriched in a set of genes a ranking is build for that feature over all genes (using the scores mentioned above). Than the amount of genes, from the set, that can be recovered by walking down the ranking is counted (very similar to gene set enrichment analysis). This generates a recovery curve (see screenshot: cumulative recovery of input regions for feature X, blue line). At some point this curve reaches a maximum (see screenshot: dotted line). The ranking at which this occurs (x-axis) is the RankAtMax. An AUC (Area Under the recovery Curve) is then calculated by measuring the area under this curve. The NES (Normalised Enrichment Score) is obtained by dividing this AUC value by the AUC value obtained from an average recovery curve across all features  (see screenshot: red line). This normalisation allows the comparison of enrichment scores between different features. 
Finally MotifSimilarityQvalue is a measurement for the similarity between motifs. This is used in the cases where a motif is not directly annotated to a TF, in this case we can annotate this motif by looking at motifs which are very similar which do have an annotation.
![image](https://user-images.githubusercontent.com/5092871/144814195-f0bf0bba-ebb4-4e31-bf50-434d5c49513a.png)


>_[QUESTION 3] Is there any way to rank regulons themselves by supposed importance or significance? E.g. the % variance in the data they describe._

One way is using the RSS method as mentioned above. But there can be many other ways of doing this, depending on your specific question. 

I hope this answers your questions. Let me know if it does so I can close the issue.

Best,

Seppe

**Comment by Jintram** [comment]
Many thanks Seppe, for your extensive answer!

If I may, just to make sure I understood correctly:

- AUC and NES are indeed quantifying how sure SCENIC is the TF (aka feature) can be linked to the supposed target genes (gene set). As you point out, more specifically, this draws solely from motif/CHIP data, and this score is determined for each of the databases from which SCENIC draws separately.
- RankAtMax also aims to quantify how "quickly" (along the X-axis) the gene set is recovered, and thus how representative the TF is for this gene set. I guess this is similar to AUC but has a somewhat different relation to the shape of the curve. (I guess in combination with AUC it also says something about the shape of the recovery curve.)
- MotifSimilarityQvalue quantifies similarity to the TF's motif.

> One way is using the RSS method as mentioned above. 

Thanks for pointing this out! I should look into this.

> But there can be many other ways of doing this, depending on your specific question.

I have a dataset with one cell type only, and there are not necessarily extremely clear boundaries for sub populations. This is why I don't necessary "trust" the clustering algorithm completely (it's informative, but not the only way to look at the data). So to me, the advantage of running SCENIC is that it is an "independent" way of of looking at the data, that might substantiate or expand on the clustering analysis. In my case, SCENIC outputs a huge list of regulons, so it would be very convenient is to have a metric that quantifies the perceived regulon's importance (in terms of contribution to driving gene expression differences between the cells). 

I understand there might be many ways to quantify this. Right now we're plotting regulon's expression on UMAPs (which despite what I said before does aim to "quantify" consistency with other cellular classification like UMAP and clustering) and as mentioned we also look at consistency between my five samples. I think this is an OK way to approach it, but if you would have some additional pointers that would be great. (But maybe that's a too extensive/broad topic for this forum.)

Feel free to close the topic, if I'm horribly misunderstanding things it would be great if you could let me know though :)

Thanks again!

**Comment by SeppeDeWinter** [comment]
No problem :)

> _AUC and NES are indeed quantifying how sure SCENIC is the TF (aka feature) can be linked to the supposed target genes (gene set). As you point out, more specifically, this draws solely from motif/CHIP data, and this score is determined for each of the databases from which SCENIC draws separately. RankAtMax also aims to quantify how "quickly" (along the X-axis) the gene set is recovered, and thus how representative the TF is for this gene set. I guess this is similar to AUC but has a somewhat different relation to the shape of the curve. (I guess in combination with AUC it also says something about the shape of the recovery curve.) MotifSimilarityQvalue quantifies similarity to the TF's motif._

Yes, that's correct!

Indeed one of the challenging parts in a post-SCENIC analysis is finding the TFs you are actually interested in, given that its output is so vast (as you mentioned). Certainly in very homogeneous datasets where making contrasts is less easy.

Some ideas:
- Variance driven by the TF (its target genes or AUC value), as you mentioned
- use a metric for cell specificity/ celltype specificity (like described in this paper: https://academic.oup.com/bib/article/18/2/205/2562739)
- look at network properties (between centrality, eigenvector centrality). The python package networkx is great for this
- ... 

Visualising your data (e.g. by plotting on a UMAP) and checking for consistency are indeed always very good ideas I would say and a good starting point.

Hope this helps,

Seppe

**Comment by Jintram** [comment]
Awesome, thanks, this was a very helpful conversation!
