### ISSUE TITLE
[BUG]When I run GRN, an ERROR may be about dask muti-processing occurs.

### ISSUE THREAD

**Issue by wangkpro** [aertslab/pySCENIC#321]
`!pyscenic grn {loom_path} {tfs} -o adj.csv --num_workers 20`
2021-08-23 19:13:38,051 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.

2021-08-23 19:13:38,171 - pyscenic.cli.pyscenic - INFO - Inferring regulatory networks.
/home/wangk/miniconda3/envs/pyscenic/lib/python3.7/site-packages/distributed/node.py:161: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 33385 instead
  f"Port {expected} is already in use.\n"
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
distributed.diskutils - INFO - Found stale lock file and directory '/mnt/data1/wangk/IPython/202005-E-MTAB-7427-7417-Mus-Melanoma-TME/dask-worker-space/worker-guqx80_c', purging
preparing dask client
parsing input
creating dask graph
20 partitions
computing dask graph
'WARNING: infer_data failed for target Star' Retry (1/10). Failure caused by ValueError('Cleaned TF matrix is empty, skipping inference of target Star.').
'WARNING: infer_data failed for target Star' Retry (2/10). Failure caused by ValueError('Cleaned TF matrix is empty, skipping inference of target Star.').
'WARNING: infer_data failed for target Star' Retry (3/10). Failure caused by ValueError('Cleaned TF matrix is empty, skipping inference of target Star.').
'WARNING: infer_data failed for target Star' Retry (4/10). Failure caused by ValueError('Cleaned TF matrix is empty, skipping inference of target Star.').
'WARNING: infer_data failed for target Star' Retry (5/10). Failure caused by ValueError('Cleaned TF matrix is empty, skipping inference of target Star.').
'WARNING: infer_data failed for target Star' Retry (6/10). Failure caused by ValueError('Cleaned TF matrix is empty, skipping inference of target Star.').
'WARNING: infer_data failed for target Star' Retry (7/10). Failure caused by ValueError('Cleaned TF matrix is empty, skipping inference of target Star.').
'WARNING: infer_data failed for target Star' Retry (8/10). Failure caused by ValueError('Cleaned TF matrix is empty, skipping inference of target Star.').
'WARNING: infer_data failed for target Star' Retry (9/10). Failure caused by ValueError('Cleaned TF matrix is empty, skipping inference of target Star.').
'WARNING: infer_data failed for target Star' Retry (10/10). Failure caused by ValueError('Cleaned TF matrix is empty, skipping inference of target Star.').
not shutting down client, client was created externally
finished
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing

2021-08-23 19:26:01,901 - pyscenic.cli.pyscenic - INFO - Writing results to file.
Exception in thread AsyncProcess Dask Worker process (from Nanny) watch process join:
Traceback (most recent call last):
  File "/home/wangk/miniconda3/envs/pyscenic/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/wangk/miniconda3/envs/pyscenic/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wangk/miniconda3/envs/pyscenic/lib/python3.7/site-packages/distributed/process.py", line 234, in _watch_process
    assert exitcode is not None
AssertionError

Exception in thread AsyncProcess Dask Worker process (from Nanny) watch process join:
Traceback (most recent call last):
  File "/home/wangk/miniconda3/envs/pyscenic/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/wangk/miniconda3/envs/pyscenic/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wangk/miniconda3/envs/pyscenic/lib/python3.7/site-packages/distributed/process.py", line 234, in _watch_process
    assert exitcode is not None
AssertionError

Exception in thread AsyncProcess Dask Worker process (from Nanny) watch process join:
Traceback (most recent call last):
  File "/home/wangk/miniconda3/envs/pyscenic/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/wangk/miniconda3/envs/pyscenic/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wangk/miniconda3/envs/pyscenic/lib/python3.7/site-packages/distributed/process.py", line 234, in _watch_process
    assert exitcode is not None
AssertionError

Exception in thread AsyncProcess Dask Worker process (from Nanny) watch process join:
Traceback (most recent call last):
  File "/home/wangk/miniconda3/envs/pyscenic/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/wangk/miniconda3/envs/pyscenic/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wangk/miniconda3/envs/pyscenic/lib/python3.7/site-packages/distributed/process.py", line 234, in _watch_process
    assert exitcode is not None
AssertionError

**Comment by wangkpro** [comment]
I've solved this problem. I downloaded the tfs file by the way "Link save as" and got the wrong file. This is the reason for the ERROR.

**Comment by cflerin** [comment]
This message indicates that the TFs matrix is empty:
```
'WARNING: infer_data failed for target Star' Retry (1/10). Failure caused by ValueError('Cleaned TF matrix is empty, skipping inference of target Star.').
```
Still, I am surprised that there was no error on the reading-in step if the file was corrupt/empty.
