### ISSUE TITLE
docker error for invalid reference format 

### ISSUE THREAD

**Issue by junjunjing** [aertslab/pySCENIC#322]
H, I am trying to use CLI and have been encountering the docker error for invalid reference format and can not figure it out:

docker run -it --rm \ -v /home/me/single_cell/scenic:/home/me/single_cell/scenic \ aertslab/pyscenic:0.11.2 pyscenic grn \ --num_workers 6 \ -o /home/me/single_cell/scenic/expression_data/expr_mat.adjacencies.tsv \ /home/me/single_cell/scenic/expression_data/scenic.loom  \ /home/me/single_cell/scenic/reference_data/mm_mgi_tfs.txt

docker: invalid reference format.
See 'docker run --help'.

Anyone has any suggestions? Thanks ahead.

**Comment by cflerin** [comment]
Something is wrong with your command... it's hard to tell, but try to break it down a bit, first:
```
docker run -it --rm aertslab/pyscenic:0.11.2
```
and you should get a python prompt. Then start adding the other options. You can try removing the backslashes (`\`) between lines, that could cause problems if there are spaces after the slash on a line you intend to continue, for instance.

**Comment by cflerin** [comment]
```
AttributeError: 'str' object has no attribute 'columns'
```
is your `auc_mtx` a pandas data frame?

**Comment by cflerin** [comment]
Closing since the original issue seems to be solved.
