### ISSUE TITLE
what type of the matrix take as inputted in pyscenic workflow

### ISSUE THREAD

**Issue by honghh2018** [aertslab/pySCENIC#324]
Hi guys,
     I want to analyize the pyscenic, so which matrix should be take as inputted in  pyscenic workflow?
     The normlized matrix or the raw count?  which matrix should be take as inputted in pyscenic?
Any advice would  be appreciated.
Best,
Hanhuihong

**Comment by cflerin** [comment]
You can use any matrix as input but I usually prefer to use the raw counts.
