### ISSUE TITLE
pySCENIC ctx--ERROR: No columns to parse from file

### ISSUE THREAD

**Issue by agolfinos** [aertslab/pySCENIC#328]
**Describe the bug**
Hello! Thank you so much for this great package. After running pyscenic ctx, I have empty regulons.csv and auc_mtx.csv files, and I run into an error: No columns to parse from file. 

**Steps to reproduce the behavior**
1. Command run when the error occurred:

```python
docker run -it --rm \
    -v ${DOCKER_LINK}:/scenicdata \
    aertslab/pyscenic:0.11.2 pyscenic ctx \
    /scenicdata/adjacencies.tsv \
    /scenicdata/mm9-500bp-upstream-10species.mc9nr.feather \
    /scenicdata/mm9-500bp-upstream-7species.mc9nr.feather \
    /scenicdata/mm9-tss-centered-10kb-10species.mc9nr.feather \
    /scenicdata/mm9-tss-centered-10kb-7species.mc9nr.feather \
    /scenicdata/mm9-tss-centered-5kb-10species.mc9nr.feather \
    /scenicdata/mm9-tss-centered-5kb-7species.mc9nr.feather \
    --annotations_fname /scenicdata/motifs-v9-nr.mgi-m0.001-o0.0.tbl \
    --expression_mtx_fname /scenicdata/counts.tsv \
    --mode "dask_multiprocessing" \
    --output /scenicdata/regulons.csv \
    --num_workers $THREADS
```

2. Error encountered:

```pytb
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

2021-09-10 15:35:57,376 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

2021-09-10 15:43:06,973 - pyscenic.cli.pyscenic - INFO - Creating modules.

2021-09-10 15:43:06,985 - pyscenic.cli.pyscenic - ERROR - No columns to parse from file
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

2021-09-10 15:43:29,706 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.
```

**Expected behavior**
I believe my counts file is formatted according to the documentation, with the gene names as gene symbols as column names, and the cell names as row indexes. Here is an example of a small snippet of my matrix. 
<img width="1043" alt="Screen Shot 2021-09-10 at 11 29 28 AM" src="https://user-images.githubusercontent.com/38253106/132886657-78008d06-9258-421c-a97a-e365c260e779.png">

So, I'm not really sure why I'm running into this error. I've tried a couple things according to previous issues, such as issue #252, however I still run into the same error in this step.  I don't believe it has anything to do with the files that I have in my DOCKER_LINK folder, they are shown below (some are not necessary for pySCENIC, but I need them in there for another step in the future)

<img width="893" alt="Screen Shot 2021-09-10 at 11 44 48 AM" src="https://user-images.githubusercontent.com/38253106/132888528-46fb9fc1-53b3-4647-95a9-964ac2afd94e.png">

**Please complete the following information:**
- pySCENIC version: 0.11.2
- Installation method: Docker
- Run environment: CLI
- OS: Mac OS Big Sur Version 11.4
- Package versions: N/A (Docker)

I also want to note--I have a very large dataset (the original matrix is stored as a Seurat file that has ~19,000 cells and 16,000 genes).

**Comment by cflerin** [comment]
@agolfinos , the error in "Creating modules" comes from trying to read the GRNBoost2 output, not the expression matrix. Check to make sure it hasn't been modified and it's not empty. In fact, I see in your screenshot that `adjacencies.tsv` is zero bytes, so that is the problem. Go back to the GRN step and make sure that completes first.

I don't think #252 or numba applies here.
