### ISSUE TITLE
GRNboost worker memory usage

### ISSUE THREAD

**Issue by Beatzekatze** [aertslab/pySCENIC#33]
I might be somewhat out of place here, so I apologise for this. I am using GRNboost from the arboretum package (python). But since GRNboost github is rather centered around the scala version and GRNboost is also part of pyScenic , I give it a try here.

When running 
``` 
from arboretum import algo
import pandas as pd

geneData = pd.read_csv("my-count-data.csv",index_col=[0],header=0)
network = algo.grnboost2(expression_data=geneData.T)```

among multiple warnings I get the following message:
``` 
Worker is at 89% memory usage. Pausing worker.  Process memory: 5.04 GB -- Worker memory limit: 5.62 GB
```

as far as I understand it, this message comes from dask and can be alleviated by changing dask limit settings. But I am not sure how to do that... Shall I import dask prior to GRNboost and change the settings first? Are there any hidden options how to access dask options via GRNboost itself?
Thanks in advance!

P.S. I am running python 3.7, arboretum 0.1.3 on Ubuntu 16.04.

**Comment by bramvds** [comment]
Dear,

Could you post this issue at the arboreta package https://github.com/tmoerman/arboreto . The version mentions in the Nature Methods paper about SCENIC is indeed based on scala, but this package is a pure python implementation. 

Many thanks,
Bram
