### ISSUE TITLE
The pyscenic predicted regulons without expression levels in mRNA counts matrix

### ISSUE THREAD

**Issue by honghh2018** [aertslab/pySCENIC#331]
Hi @cflerin ,
     It so very weird that regulon , for instance the SP1 TF, was be selected for a significant regulon using the pyscenic. Nonetheless, i can not found the SP1 expression on the mRNA counts matrix. its expression almost was zero in all cells. 
     I am wonder that if the TF expression can not be detected, can it regulate its target genes?

Best,
Hanhuihong

**Comment by cflerin** [comment]
hi @honghh2018 ,

First, lowly-expressed TFs can give meaningful results: [see this comment](https://github.com/aertslab/pySCENIC/issues/341#issuecomment-984806276). But it depends on what you mean by "expression almost was zero" in this case. Ultimately pySCENIC can only make predictions based on the data given, and you have to make the interpretation based on the characteristics of your dataset.
