### ISSUE TITLE
Can we aggregate different samples results through scenic_multiruns?[results]

### ISSUE THREAD

**Issue by Zifeng-L** [aertslab/pySCENIC#333]
Hi there!
I found that in your work on VSN-Pipelines, we can use bbknn_scenic or harmony_scenic to aggregate different samples. I also found a single sample pipeline called single_sample_scenic_multiruns. I wonder what's the differences between these two kinds of methods? Can I just run single_sample_scenic and aggregate multi results? If it works, it seems to be a multi-thread way for saving time. Many thanks in advance.

**Comment by cflerin** [comment]
Hi @Zifeng-L ,

It should be possible to use bbknn with multiple scenic runs. [Here](https://vsn-pipelines-examples.readthedocs.io/en/latest/PBMC10k_multiruns.html) you can find an example that uses the `single_sample_scenic` pipeline, but the approach is similar (add `scenic_multiruns` profile in addition to `bbknn_scenic` for instance).

**Comment by Zifeng-L** [comment]
> Hi @Zifeng-L ,
> 
> It should be possible to use bbknn with multiple scenic runs. [Here](https://vsn-pipelines-examples.readthedocs.io/en/latest/PBMC10k_multiruns.html) you can find an example that uses the `single_sample_scenic` pipeline, but the approach is similar (add `scenic_multiruns` profile in addition to `bbknn_scenic` for instance).

So you mean that we can not just run single_sample_scenic and aggregate multi results?

**Comment by cflerin** [comment]
Hi @Zifeng-L , I guess it's not clear to me what you want to do. 

If you have one sample to run, you can run `single_sample_scenic`... this will run the single sample pipeline plus a single pass of the SCENIC steps and output an integrated loom file. The `multiruns` part of this is for running the SCENIC steps multiple times (10x, 100x, etc.), and integrating the results. You can do this as I explained above. Be aware that this can take an excessive amount of computational resources depending on your dataset size, so be very sure that's what you want. In every case, you should at least run single-pass SCENIC before trying multiruns.

If you have multiple samples and want to do batch effect correction, you can use `bbknn` or `bbknn_scenic`. SCENIC will be run after the integration. Again, it should be possible to add multiruns (repeating SCENIC multiple times) here if that's what you want.
