### ISSUE TITLE
pruning

### ISSUE THREAD

**Issue by rojinsafavi** [aertslab/pySCENIC#334]
As mentioned here and in the paper, the modules are created based on 
```
Targets with importance > the 50th percentile.
Targets with importance > the 75th percentile
Targets with importance > the 90th percentile.
The second method is to select the top targets for a given TF:

Top 50 targets (targets with highest weight)
The alternative way to create the TF-modules is to select the best regulators for each gene (this is actually how GENIE3 internally works). Then, these targets can be assigned back to each TF to form the TF-modules. In this way we will create three more gene-sets:

Targets for which the TF is within its top 5 regulators
Targets for which the TF is within its top 10 regulators
Targets for which the TF is within its top 50 regulators
```

My question is given that you are making multiple modules, how do you do the pruning? do you combine all the modules in order to prune?

df = prune2df(dbs, modules, MOTIF_ANNOTATIONS_FNAME)

Thank you!

**Comment by cflerin** [comment]
Hi @rojinsafavi ,

Yes, the co-expression modules are created with these multiple methods. Each module is evaluated independently in the cisTarget step and is outputted to separate entries in the `prune2df` output (here "pruning" happens wherein module targets are only kept if they have a cis-regulatory footprint). Following this, these pruned modules / enriched motifs are combined into a single "regulon" with the [`df2regulons`](https://github.com/aertslab/pySCENIC/blob/c66455cdc0d736d67963b218a8ebce61dc4eef82/src/pyscenic/transform.py#L389) function (which uses in turn `_regulon4group`), which combines the scores, target genes, and assigns the "most enriched motif" to the regulon,
