### ISSUE TITLE
Could I use pySCENIC for fly?

### ISSUE THREAD

**Issue by fangge-Li** [aertslab/pySCENIC#34]
Hi there,
I have used SCENIC R package. Now, I want to use pySCENIC for Drosophila.
I find that pySCENIC is for Human and mouse only. Can I use pySCENIC for Drosophila?
If yes, where could I find the reference files?

Thank you very much!

FG

**Comment by bramvds** [comment]
Dear,

You can use the "dm6-5kb-upstream-full-tx-11species.mc8nr" ranking database (downloadable from https://resources.aertslab.org/cistarget/) in combination with mc8nr version of motif annotations (https://resources.aertslab.org/cistarget/motif2tf/motifs-v8-nr.flybase-m0.001-o0.0.tbl).

Hope this helps,
Bram
