### ISSUE TITLE
Why CD59 list as a TF in pySENIC[results]

### ISSUE THREAD

**Issue by MiMiroot** [aertslab/pySCENIC#342]
Hi,

I am confused about a gene CD59 in the TF list used in pySENIC. My result shows CD59 as an active TF and it has many targets. However, CD59 seems not to be a TF, but a membrance protein. Could you please tell me how to explain this?

thanks,
MiMiroot

**Comment by cflerin** [comment]
Hi @MiMiroot ,

We provide this list of TFs as a guideline of a "reasonable" or complete list of TFs to start with for your analysis. Our list comes partially from [doi:10.1016/j.cell.2018.01.029](https://doi.org/10.1016/j.cell.2018.01.029).

In principle you can put any list of genes to be considered as a TF within pySCENIC's analysis paradigm. Therefore you have to be a bit careful with the interpretation based on your specific dataset and setup.
