### ISSUE TITLE
[results] What does the plus sign mean in the CSV format output of AUCell analysis

### ISSUE THREAD

**Issue by gangcai** [aertslab/pySCENIC#343]
In the output of the AUCell matrix header, the gene name was followed by a plus sign, what does this sign mean? Thanks very much.
Example:
Hdac6(+),Hes1(+),Hes7(+),Hey1(+)

**Comment by cflerin** [comment]
Hi @gangcai . The `+` denotes "positive" regulons (i.e. there is a positive correlation between the TF and target gene expression values (dependent on whether dropouts are masked in the correlation calculation, option `--mask_dropouts`)). By default pySCENIC keeps only these positive regulons (see `--all_modules` option in the CLI if you're interested in keeping both, but generally the negatives are harder to detect and interpret).
