### ISSUE TITLE
pyscenic   ctx 10% (pyscenic   ctx), the machine can't move [BUG]

### ISSUE THREAD

**Issue by jiangzh-coder** [aertslab/pySCENIC#344]
When the computational regulons of Python CTX is about 10% (pyscenic   ctx), the machine can't move.

The following is my server configuration. Is your server configuration standard or computational? In addition, how much memory? Do I need to buy an 8-core, 32g memory standard server? (Currently my sever is 4-core, 8g memory)

i am using Tencent cloud

My code which did not work is: (always 0%, software did not go forward)

docker run -it -v /home/ubuntu/pys/:/pys aertslab/pyscenic:0.10.0 \

pyscenic   ctx \

/pys/ly6cpCD64pCD206pMonomacro.tsv \

/pys/mm10__refseq-r80__10kb_up_and_down_tss.mc9nr.feather \

--annotations_fname /pys/motifs-v9-nr.mgi-m0.001-o0.0.tbl \

--expression_mtx_fname /pys/ly6cpCD64pCD206pMonomacro.loom \

--mode "dask_multiprocessing" \

--output /pys/regly6cpCD64pCD206p.csv \

--num_workers 6 \

--mask_dropouts

**Comment by ghuls** [comment]
We never run it on a machine with so little memory.

**Comment by jiangzh-coder** [comment]
Thanks. It works fine when i changed to a computer with 256GB memory. However, i have new problem as following. 
i got final loom file, but when i tried to open it in R, some errors appeared:

library(SCopeLoomR) 
loomPath <- "ALLmonomacrofinal.loom"
loom <- open_loom(loomPath, mode="r") 

Error in H5File.open(filename, mode, file_create_pl, file_access_pl) : 
  It is not possible to open the file. 
HDF5-API Errors:
    error #000: D:/a/rtools-packages/rtools-packages/mingw-w64-hdf5/src/hdf5-1.8.16/src/H5F.c in H5Fopen(): line 604: unable to open file
        class: HDF5
        major: File accessibilty
        minor: Unable to open file

    error #001: D:/a/rtools-packages/rtools-packages/mingw-w64-hdf5/src/hdf5-1.8.16/src/H5Fint.c in H5F_open(): line 992: unable to open file: time = Thu Dec 02 19:56:13 2021
, name = 'E:\1   #######\ALLmonomacrofinal.loom', tent_flags = 0
        class: HDF5
        major: File accessibilty
        minor: Unable to open file

    error #002: D:/a/rtools-packages/rtools-packages/mingw-w64-hdf5/src/hdf5-1.8.16/src/H5FD.c in H5FD_open(): line 993: open failed
        class: HDF5
        major: Virtual File Layer
        minor: Unable to initialize object

    error #003: D:/a/rtools-packages/rtools-packages/mingw-w64-hdf5/src/hdf5-1.8.16/src/H5FDsec2.c in H5FD_sec2_open(): line 339: unable to open file

Could you help me?Thanks lot

**Comment by ghuls** [comment]
We don't use Windows here as most bioinformatics tools are designed for Linux.

It can be that you have to escape your backslashes in your filename (`\` ==> `\\`) 
`'E:\\1 #######\\ALLmonomacrofinal.loom'

Using forward slashes could work too: `'E:/1 #######/ALLmonomacrofinal.loom'`.

Filepath handling of software compiled for windows that was ported from Linux can be inconsistent between different programs.

**Comment by jiangzh-coder** [comment]
Thanks lot,it works. 
However, i got 268TFs,2000cells matrix. TFs are too much!
How may i select TFs to draw heatmap? Do you know any pyscenic protocol to match my results as R code expected? 
thanks again
Jzh

**Comment by cflerin** [comment]
hi @jiangzh-coder , for these downstream steps, you could check some of the tutorials here and in the [SCENIC Protocol](https://github.com/aertslab/SCENICprotocol) repository. In particular [this one](http://htmlpreview.github.io/?https://github.com/aertslab/SCENICprotocol/blob/master/notebooks/PBMC10k_downstream-analysis.html), but possibly also look at the cancer dataset tutorial there.

Closing this since the original question seems to have been answered... For guidelines on memory and cpu requirements, it very much depends on the size of the dataset and number of cpu processes used, but this table could give some ideas (all of these timings used 20 cpu processes):
![image](https://user-images.githubusercontent.com/6509900/144460412-0c3590e7-0874-4faa-bccb-d795e30fcc8a.png)

**Comment by jiangzh-coder** [comment]
Thanks lot! 
But unfortunatelly, i do not found any tutorials using R script. What i want is to compare different conditions and different cell types. May i use wilcox test to analyze differences like DEGs analysis? i found 2 possible solutions as following, but i do not know if it is correct. Can anyone help me?

https://github.com/aet21/scira

https://saezlab.github.io/dorothea/articles/single_cell_vignette.html
