### ISSUE TITLE
ranking genes in AUCell

### ISSUE THREAD

**Issue by sherriying** [aertslab/pySCENIC#349]
Dear pySCENIC team, 

Firstly, I would like to thank you for developing this great application! 

I have a question about intermediate step of ranking genes in the AUCell algorithm. In order to calculate the activity/enrichment of a gene set/regulon, algorithm need first ranks all genes in a cell according to their expression value. My question is that how comparable of different genes in a cell when ranking them? In other words, can we rank them directly using just raw expression value? Because the different length of genes might cause bias of read counts/expression.  Will be some false negative targets miss in the top rankings in a cell? Do we need some normalisation before ranking genes? 

Many thanks and looking forward to your reply!

**Comment by SeppeDeWinter** [comment]
Hi @sherriying,

Sorry for the latish reply.

The genes are indeed ranked using the raw expression values (no normalisation etc.). This might be surprising but from experience this works great. The reason why this works with raw expression values is that you expect biases affecting read counts (e.g. as you mention gene length) to be the same across cells, this allows us to compare the rankings across cells (which what we do in a sense when we visualize AUC values). 

This being said, feel free to play around with normalisation before calculating AUC scores and assessing the effects.
