### ISSUE TITLE
What is the meaning of r.score > 8.0?

### ISSUE THREAD

**Issue by hyjforesight** [aertslab/pySCENIC#366]
Hello SCENIC,
Could you please explain a little bit about the meaning of `r.score > 8.0` in `names = list(map(op.attrgetter('name'), filter(lambda r: r.score > 8.0, regulons)))`? How shall I adjust this argument and what will be changed?
Thanks!
Best,
YJ

```python
aucell_adata = sc.AnnData(X=auc_mtx.sort_index())
aucell_adata.obs = df_obs
names = list(map(op.attrgetter('name'), filter(lambda r: r.score > 8.0, regulons)))
sc.pl.stacked_violin(aucell_adata, names, groupby='batch', use_raw=False, dendrogram=True, save=' - 4in1 - regulons.svg', cmap='Reds')
```
![image](https://user-images.githubusercontent.com/75048821/153334267-3ff63bca-990e-4722-9d1e-5dd0b88fa610.png)

**Comment by SeppeDeWinter** [comment]
Hi YJ

Sorry for the late reply.

This score relates to the motif enrichment score. 
It selects for regulons for which the motif of the TF has a score of at least 8.

Hope this helps.

Seppe

**Comment by hyjforesight** [comment]
hello @SeppeDeWinter 
Thanks for the response! Wow, you answered all my questions at once. I appreciated it! Sorry for asking a lot!
Best,
YJ
