### ISSUE TITLE
Is it reasonable to concatenate 2 different libraries and run SCENIC together?

### ISSUE THREAD

**Issue by hyjforesight** [aertslab/pySCENIC#367]
Hello SCENIC,
Because we're not familiar with the GRNBoost2 algorithm, we're wondering whether it is reasonable to concatenate 2 different libraries and run SCENIC for this concatenated dataset.
For example, I have WT and KO scRNA-seq data. I want to compare the differences of the regulatory networks between WT and KO. What is the best practice for this comparison? Run SCENIC for WT and KO individually or concatenate them first, then run SCENIC for this concatenated dataset?
Thanks!
Best,
YJ

**Comment by SeppeDeWinter** [comment]
Hi YJ

Again sorry for the late reply.
It is reasonable to concatenate the two different runs before running SCENIC, that's in fact what we also do in our automated pipelines (see: https://vsn-pipelines.readthedocs.io/en/latest/pipelines.html#harmony-scenic-harmony-scenic).

Hope this helps.

Good luck.

Seppe

**Comment by hyjforesight** [comment]
hello @SeppeDeWinter 
Thanks for the response!

**Comment by hyjforesight** [comment]
Hello @SeppeDeWinter 
Sorry for asking this question again.
I checked the VSN pipeline. For the concatenated data, the input data for SCENIC is log-transformed, HVG selected, PCA generated, and batch-effect corrected (Harmony). However, the Nature Protocol paper recommends inputting raw data. Which data is the right one I should input for SCENIC?
Thanks!
Best,
YJ

**Comment by SeppeDeWinter** [comment]
@hyjforesight 

Indeed, for concatenating two runs it might be necessary to do some of these preprocessing steps you mentioned in order to remove effect arising from technical (but not biologica) difference between the two runs.

Hope this helps.

Best,

Seppe

**Comment by cflerin** [comment]
Hi @hyjforesight ,

Just to clarify here, the VSN Pipeline does not apply the preprocessing/transformation steps to the SCENIC input for Harmony, or any of the other multi-sample pipelines. The only steps applied are basic cell and gene filtering, then concatenation of the raw counts matrices.

However, if you do apply these transformation steps, you will likely get largely similar results. Most importantly, make sure that you do not filter for highly variable genes prior to running SCENIC; you should give the entire expression matrix without feature selection applied.
