### ISSUE TITLE
GRNBoost Warning

### ISSUE THREAD

**Issue by gouinK** [aertslab/pySCENIC#37]
Greetings,

I have been successfully running this whole program and getting some nice results, but I am puzzled as to why I am getting this message when I run the GRNboost: 

/anaconda3/envs/pyscenic/lib/python3.6/site-packages/sklearn/ensemble/gradient_boosting.py:1636: RuntimeWarning: invalid value encountered in true_divide
  importances /= importances.sum()

I thought that it might be because I have some genes that have zero total counts in the whole count table, but I have removed all of those genes and am still getting this message. This error is not preventing the program from running, but I just want to make sure that I am not missing anything. Thanks so much!

**Comment by bramvds** [comment]
Dear,

For the implementation of the GRNBoost algorithm I rely on the arboreto package: https://github.com/tmoerman/arboreto . 

This warning should not affect your results: the approach to GRN reconstruction taken by GRNBoost is solving a multivariate "regression per target gene" problem. The independent variables are the expression levels of the transcription factors and this regression is solved via Gradient Boosting Trees. The solution not only gives information that there is a link between a TF and a target gene, the (variable) importance of the regression model is also assessed (and therefore also of the TF-target link). It is in the normalisation of these importances that you get this warning.

Kindest regards,
Bram
