### ISSUE TITLE
The collected transcription factors (TFs) and their target genes for training regulatory networks

### ISSUE THREAD

**Issue by gancao** [aertslab/pySCENIC#370]
I am interested in the known TFs and their targeted genes used for training in SCENIC.  Could you please provide the database and make it availabe? I would appreciate it very much.

**Comment by SeppeDeWinter** [comment]
Hi

The list of known TFs is mostly based on literature, for example for human we acquired them from this publication: 
*Lambert SA, Jolma A, Campitelli LF, Das PK, Yin Y, Albu M, Chen X, Taipale J, Hughes TR, Weirauch MT.(2018) [The Human Transcription Factors](https://www.sciencedirect.com/science/article/pii/S0092867418301065?via%3Dihub). Cell. 172(4):650-665. doi: 10.1016/j.cell.2018.01.029. Review.*

See also this commit message which explains in detail how these lists are acquired and processed:
https://github.com/aertslab/pySCENIC/commit/c74a6ebdbcd3b63be3166dbaf63f2ebbb6b218b6

As for the target genes, these are predicted from the data (that is what the SCENIC algorithm does).

Hope this helps.

Best,

Seppe

**Comment by gancao** [comment]
Thank you very much, I got it


| |
甘草
|
|
***@***.***
|
On 3/3/2022 ***@***.***> wrote：

Closed #370.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
