### ISSUE TITLE
Why does the transcription factors with the highest RSS not have high AUCell activity?

### ISSUE THREAD

**Issue by hyjforesight** [aertslab/pySCENIC#372]
Hello SCENIC,
I found that the top transcription factors determined by RSS or Z score sometimes don't have high AUCell activities. For example, among the below top 10 transcription factors determined by RSS, only STAT1 shows a significant activity (peak crossing the threshold). It looks like no significant activities are shown for the other 9 TFs. **Why does this happen?**
![image](https://user-images.githubusercontent.com/75048821/157714304-d43a4db7-9d17-476c-988a-c5b7640805dc.png)
![image](https://user-images.githubusercontent.com/75048821/157714383-7b91c27d-6c97-4ca4-b49e-bb246dd692ee.png)

In the amazing Nature Protocol paper, you mentioned picking up the TFs with multiple appearances across multiple runs. I guess maybe only top TFs with the highest RSS were checked to determine which one is the robust one?
So, shocked by only STAT1 showing the significant activity, **I'm confused about what the best practice is if we want to pick up the key TFs for a specific cell cluster. When we get the top TF list from RSS, shall we also check their AUCell binary plot one by one to confirm whether they cross the threshold, although it may be labor-consuming?** Our current practice is only checking the Regulon(gene) UMAP for top TFs determined by RSS like below.
![image](https://user-images.githubusercontent.com/75048821/157717636-057eb98b-ad63-4042-bd04-76c6c2dbea93.png)

Thanks! Appreciate it!
Best,
YJ

**Comment by SeppeDeWinter** [comment]
Hi @hyjforesight 

You are right about this. The RSS determines how _specific_ a regulon is. Specificity does not necessarily mean high AUC values.

The RSS can serve as one indicator of which regulons might be important for a certain celltype, but this score certainly is not perfect.

Checking the AUC values on a UMAP/tSNE therefore always is a good idea. There is no golden standard on methods to pick _the_ regulon for a certain celltype. 

I hope this helps a bit.

Best,

S

**Comment by hyjforesight** [comment]
Hello @SeppeDeWinter 
Thanks for the response! Appreciate it!
I found that `adata.obs` stores the AUCell activity for each cell, but we're more interested in the average AUCell activity for one specific regulon in one specific cluster. 
![image](https://user-images.githubusercontent.com/75048821/159743779-7f005e94-7dde-4e7f-b248-d67bf75d6511.png)

Is there a good way to quickly query which regulon determined by RSS has the highest AUCell value? I'm now plotting the binary plot for the top 50 regulons one by one, which is a little bit labor-consuming.

Thanks!
Best,
YJ

**Comment by SeppeDeWinter** [comment]
You could consider plotting a scatter plot with RSS values vs average AUC value per cluster.

**Comment by hyjforesight** [comment]
Thanks @SeppeDeWinter for the recommendations!
