### ISSUE TITLE
How to choose the ranking database

### ISSUE THREAD

**Issue by Tianran1** [aertslab/pySCENIC#374]
Hi, I am new to SCENIC analysis. I went through the tutorials and I noticed that for the pbmc and other cancer data analysis, you applied different ranking databases. I read the introduction about the database and the differences show in Distance parameter. I want to ask if you know how I can choose them.

**Comment by SeppeDeWinter** [comment]
Hi @Tianran1 

Actually in the tutorial multiple databases are used at the same time (i.e. information from multiple databases is merged), you can choose to do the same but this is not obliged.

These databases indeed differ in the distance that is considered around the gene to look for motifs.

Also, some databases are based on ChIP-seq data (e.g. encode_20190621__ChIP_seq_transcription_factor.hg38__refseq-r80__10kb_up_and_down_tss.max)

When picking the database also be careful that you pick a database which is compatible with the assembly for your scRNA-seq data (hg38, hg19, mm10, mm9, ...).

You can find all the databases at: https://resources.aertslab.org/cistarget/.

Hope this helps.

Let me know if you have any further specific concerns/questions.

Best

S

**Comment by SeZuNo** [comment]
Hi @SeppeDeWinter and all the SCENIC community, 

I have recently started runing different (py)SCENIC analysis and found myself asking the same question on how to select the databases. In our case 2: _500up100down_ and _10kbp_, we have run the 3 cases, both single and one combined and the results are rather mixed. 
We have not found documentation on what's the criteria behind selecting one or the other. Furthermore, have not found information on the _merging_ when multiple databases are used at the same time (as the tutorial does), could you please elaborate more on this and/or maybe point out sections of the source code that perform the merging?

Thanks in advance and best regards 

Nacho.
