### ISSUE TITLE
[results] Create custom motif .tbl file for cistarget

### ISSUE THREAD

**Issue by daxus4** [aertslab/pySCENIC#375]
Hi, first of all I want to tell you that you did a great work by implementing this tool.

I have already used `GRNBoost2` and now I have to use `cistarget`. I created my cistarget database using the tool `create_cistarget_databases` with my own custom set of motifs.

Have I to create also the .tbl that contains the information for the motifs? I do not find how to create it and which columns are necessary.

Can someone tell me those information?

Thank you!

**Comment by cbravo93** [comment]
Hi @daxus4 !

Yes, you need to create the tbl file. In this file you will indicate which TF/s are annotated to each motif, you will not get regulons for these motifs if they are not linked to the TF in the gene module (so if there is no annotation for the motifs, they will not be used in the analysis). You have an example of how it looks like here for mouse for example: https://resources.aertslab.org/cistarget/motif2tf/motifs-v9-nr.flybase-m0.001-o0.0.tbl . If you are not planning to use motif similarity or orthology based annotations (just direct motif-TF), you can add them like this:

```
#motif_id	motif_name	motif_description	source_name	source_version	gene_name	motif_similarity_qvalue	similar_motif_id	similar_motif_description	orthologous_identity	orthologous_gene_name	orthologous_species	description
bergman__Abd-B	Abd-B	Abd-B	bergman	1.1	Abd-B	0.000000	None	None	1.000000	None	None	gene is directly annotated
```

**Comment by daxus4** [comment]
Thank you for the answer @cbravo93!

I have another doub. With `create_cisTarget_databases` I have in output four databases .feather. Which one have I to give in input to `pyscenic ctx`?

**Comment by cbravo93** [comment]
Hi!

It should be *genes_vs_motifs.rankings if i remember correctly :) (otherwise try *motifs_vs_genes.rankings)

C

**Comment by daxus4** [comment]
Thank you!

**Comment by ctlshcxy** [comment]
> Hi @daxus4 !
> 
> Yes, you need to create the tbl file. In this file you will indicate which TF/s are annotated to each motif, you will not get regulons for these motifs if they are not linked to the TF in the gene module (so if there is no annotation for the motifs, they will not be used in the analysis). You have an example of how it looks like here for mouse for example: https://resources.aertslab.org/cistarget/motif2tf/motifs-v9-nr.flybase-m0.001-o0.0.tbl . If you are not planning to use motif similarity or orthology based annotations (just direct motif-TF), you can add them like this:
> 
> ```
> #motif_id	motif_name	motif_description	source_name	source_version	gene_name	motif_similarity_qvalue	similar_motif_id	similar_motif_description	orthologous_identity	orthologous_gene_name	orthologous_species	description
> bergman__Abd-B	Abd-B	Abd-B	bergman	1.1	Abd-B	0.000000	None	None	1.000000	None	None	gene is directly annotated
> ```

Well, but I still don't know how to create the tbl file...any suggestions? can I download human/mouse example from https://resources.aertslab.org/cistarget/motif2tf/ first, and then replace human/mouse gene symbols to other species gene symbols? for gene symbol replacing, could you please give me some hints of how to achieve that?
