### ISSUE TITLE
newer databases?

### ISSUE THREAD

**Issue by mfiers** [aertslab/pySCENIC#4]
Will you be able to provide databases for mm10 & GRCh38?

thanks!
Mark

**Comment by bramvds** [comment]
Hi Mark,

These databases have just been converted to feather and will soon be made available via the public webserver.

Kr,
Bram

**Comment by dschrein** [comment]
the link to the cistarget databases from the README still does not have mm10 - am I looking in the wrong place?  

thanks in advance!
