### ISSUE TITLE
Upgrade pyarrow dependency, or permit more recent versions

### ISSUE THREAD

**Issue by alexlenail** [aertslab/pySCENIC#400]
Pyarrow is on version 8.0 (https://pypi.org/project/pyarrow/#history) but this repository depends on `pyarrow<0.17.0,>=0.11.1`. Is the `<0.17.0` really necessary?

**Comment by cbravo93** [comment]
Hi!

You can now work with pyarrow 8.0.0.

Cheers!

Carmen
