### ISSUE TITLE
Fail to download resources 

### ISSUE THREAD

**Issue by FionaMoon** [aertslab/pySCENIC#410]
Hi all,
 I fail to download TF files resources and find I can't open https://resources.aertslab.org/.
I'd like to know if there are other ways to download these important feather files?

Thank you inadvance!

**Comment by ghuls** [comment]
What is the output of:
```
curl -v -O -L -R https://resources.aertslab.org/cistarget/motif2tf/motifs-v9-nr.hgnc-m0.001-o0.0.tbl
```

**Comment by FionaMoon** [comment]
Thank you for your reply!
I've download resource successfully .
Maybe network is bad sometimes so I can't connect to url of resources last week .



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Gert ***@***.***> |
| Date | 07/25/2022 16:26 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [aertslab/pySCENIC] Fail to download resources (Issue #410) |

What is the output of:

curl -v -O -L -R https://resources.aertslab.org/cistarget/motif2tf/motifs-v9-nr.hgnc-m0.001-o0.0.tbl
