### ISSUE TITLE
zero-score regulon

### ISSUE THREAD

**Issue by wangjiawen2013** [aertslab/pySCENIC#422]
Hi,
When I run clustering with sns.clustermap(), an error occurred:
FloatingPointError: NaN dissimilarity value.
It caused by an weired value in the auc matrix. Some regulons (such as Ppp2r3d(+)) auc score are zeros for all the cells !
What does that (zeros for all the genes) mean and how to solve the problem ?

**Comment by SeppeDeWinter** [comment]
Hi

I changed the label of this issue because it is likely that the error you encountered is not caused by a bug in the pyscenic code.

How many target genes do you have for these regulons with AUC value equal to 0 for all cells?

Best,

Seppe

**Comment by wangjiawen2013** [comment]
I find there are only three genes !

**Comment by SeppeDeWinter** [comment]
Three genes is probably too low to calculate the enrichment values using AUCell. You can consider excluding these regulons to be able to draw your heatmap.

Best,

Seppe
