### ISSUE TITLE
[BUG] Not clearing memory after arboreto_with_multiprocessing.py

### ISSUE THREAD

**Issue by JensFGG** [aertslab/pySCENIC#429]
**Describe the bug**
After running the arboreto function it is not clearing the memory. 
using 64 cores with 900 gig memory and after finishing it keeps using 600gig for some reason. Cannot find the process doing it. Any clues?

**Comment by SeppeDeWinter** [comment]
Hi @JensFGG 

Sorry for the late reply.

Python's carbage collector should kick in to clear memory.

Could you show the output of htop/top?

Best,

Seppe

**Comment by JensFGG** [comment]
sorry for my late reply. I was to fast pointing fingers ;). I actually don't think pySCENIC is creating the issue but something else.
