### ISSUE TITLE
Transcription factor database sources[results]

### ISSUE THREAD

**Issue by fangshansh** [aertslab/pySCENIC#433]
Hi pySCENIC team,

Thank you for providing a great tool. I am running pyscenic using my original hgnc data, and TFF3 is included in the Human transcription factor database.  Can you provide literature or website on TFF3 as a transcription factor?

Any suggestions or comments would be really appreciated.

**Comment by SeppeDeWinter** [comment]
Hi @fangshansh 

Sorry for the late reply. 
We don't have references for each individual transcription factor. The list however is obtained from curated databases.

Please see this commit for more info: https://github.com/aertslab/pySCENIC/commit/c74a6ebdbcd3b63be3166dbaf63f2ebbb6b218b6
 

Hope this helps.

Best,

Seppe
