### ISSUE TITLE
Error report: pyscenic aucell

### ISSUE THREAD

**Issue by ojikj2019** [aertslab/pySCENIC#470]
Hello, I've been getting error as described below. There were no problems until the step of pyscenic aucell. I'd appreciate if you let me know how to solve the problem. Thank you.

**Steps to reproduce the behavior**
1. Command run when the error occurred:

!pyscenic aucell \
    {f_loom_path_scenic} \
    reg.csv \
    --output {f_pyscenic_output} \
    --num_workers 8

2. Error encountered:

2023-04-20 16:15:07,072 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.

2023-04-20 16:15:07,384 - pyscenic.cli.pyscenic - INFO - Loading gene signatures.
Create regulons from a dataframe of enriched features.
Additional columns saved: []

2023-04-20 16:15:08,409 - pyscenic.cli.pyscenic - INFO - Calculating cellular enrichment.

2023-04-20 16:15:14,871 - pyscenic.cli.pyscenic - INFO - Writing results to file.
Traceback (most recent call last):
  File "/home/jk/anaconda3/envs/test_pyscenic/bin/pyscenic", line 8, in <module>
    sys.exit(main())
  File "/home/jk/anaconda3/envs/test_pyscenic/lib/python3.10/site-packages/pyscenic/cli/pyscenic.py", line 713, in main
    args.func(args)
  File "/home/jk/anaconda3/envs/test_pyscenic/lib/python3.10/site-packages/pyscenic/cli/pyscenic.py", line 296, in aucell_command
    append_auc_mtx(
  File "/home/jk/anaconda3/envs/test_pyscenic/lib/python3.10/site-packages/pyscenic/cli/utils.py", line 347, in append_auc_mtx
    for name, threshold in auc_thresholds.iteritems()
  File "/home/jk/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'iteritems'

**Expected behavior**

**Please complete the following information:**
- pySCENIC version: 0.12.1
- Installation method: pip
- Run environment: Jupyter notebook
- OS: Ubuntu 22.04
- Package versions:
anndata     0.9.1
scanpy      1.9.3
-----
MulticoreTSNE       NA
PIL                 9.5.0
asttokens           NA
backcall            0.2.0
bottleneck          1.3.7
cffi                1.15.1
cloudpickle         2.2.1
comm                0.1.3
cycler              0.10.0
cython_runtime      NA
cytoolz             0.12.1
dask                2023.4.0
dateutil            2.8.2
debugpy             1.6.7
decorator           5.1.1
defusedxml          0.7.1
executing           1.2.0
h5py                3.8.0
igraph              0.10.4
ipykernel           6.22.0
ipython_genutils    0.2.0
jedi                0.18.2
jinja2              3.1.2
joblib              1.2.0
kiwisolver          1.4.4
leidenalg           0.9.1
llvmlite            0.39.1
loompy              3.0.7
louvain             0.8.0
lz4                 4.3.2
markupsafe          2.1.2
matplotlib          3.4.0
matplotlib_inline   0.1.6
mpl_toolkits        NA
natsort             8.3.1
numba               0.56.4
numexpr             2.8.4
numpy               1.23.5
numpy_groupies      0.9.20
packaging           23.0
pandas              2.0.0
parso               0.8.3
pexpect             4.8.0
pickleshare         0.7.5
pkg_resources       NA
platformdirs        3.2.0
prompt_toolkit      3.0.38
psutil              5.9.4
ptyprocess          0.7.0
pure_eval           0.2.2
pyarrow             11.0.0
pycparser           2.21
pydev_ipython       NA
pydevconsole        NA
pydevd              2.9.5
pydevd_file_utils   NA
pydevd_plugins      NA
pydevd_tracing      NA
pygments            2.15.0
pyparsing           3.0.9
pytz                2023.3
scipy               1.10.1
session_info        1.0.0
setuptools          66.0.0
six                 1.16.0
sklearn             1.2.2
stack_data          0.6.2
tblib               1.7.0
texttable           1.6.7
threadpoolctl       3.1.0
tlz                 0.12.1
toolz               0.12.0
tornado             6.2
traitlets           5.9.0
wcwidth             0.2.6
yaml                6.0
zipp                NA
zmq                 25.0.2
zoneinfo            NA
-----
IPython             8.12.0
jupyter_client      8.1.0
jupyter_core        5.3.0
notebook            6.5.4
-----
Python 3.10.10 (main, Mar 21 2023, 18:45:11) [GCC 11.2.0]
Linux-5.19.0-40-generic-x86_64-with-glibc2.35
-----
Session information updated at 2023-04-20 15:32

**Comment by xiangyupan** [comment]
Hi @ojikj2019 
I meet the same error with you mentioned just as follow.
Have you solved this problem? Could you share your solution? 
Many thanks!
![图片](https://user-images.githubusercontent.com/20773767/233880111-ad3a2223-2306-489f-8857-7257939d444f.png)

**Comment by cpusummer-wdn** [comment]
I meet the same error.

**Comment by ojikj2019** [comment]
Hi Pan,

Actually, I didn't do anything. The error was gone after re-installing pyscenic with other packages in a new conda virtual environment. Hope it helps you.

Best,

Jinhong


Android용 Outlook<https://aka.ms/AAb9ysg> 다운로드

________________________________
보낸 사람: Xiangyu Pan ***@***.***>
보냄: 2023년 4월 23일 일요일 오후 7:34
받는 사람: aertslab/pySCENIC ***@***.***>
참조: Jin Hong Kim ***@***.***>; Mention ***@***.***>
제목: Re: [aertslab/pySCENIC] Error report: pyscenic aucell (Issue #470)

CAUTION: The Sender of this email is not from within Dalhousie.

Hi @ojikj2019<https://github.com/ojikj2019>
I meet the same error with you mentioned just as follow.
Have you solved this problem? Could you share your solution?
Many thanks!
[图片]<https://user-images.githubusercontent.com/20773767/233880111-ad3a2223-2306-489f-8857-7257939d444f.png>

**Comment by ojikj2019** [comment]
Hi Diana,

The error was gone right after re-installing pyscenic with other packages in a new conda virtual environment. Hope it helps you.

Best,

Jinhong


Android용 Outlook<https://aka.ms/AAb9ysg> 다운로드

________________________________
보낸 사람: Diana_Wang ***@***.***>
보냄: 2023년 4월 27일 목요일 오전 6:37
받는 사람: aertslab/pySCENIC ***@***.***>
참조: Jin Hong Kim ***@***.***>; Mention ***@***.***>
제목: Re: [aertslab/pySCENIC] Error report: pyscenic aucell (Issue #470)

CAUTION: The Sender of this email is not from within Dalhousie.

I meet the same error.

**Comment by Kevinckyy** [comment]
I met the same error

**Comment by ojikj2019** [comment]
Hi Kevinckyy,

The error was gone right after re-installing pyscenic with other packages in a new conda virtual environment. Hope it helps you.

Best,

Jinhong

________________________________

**Comment by xiangyupan** [comment]
Hi Jinhong,
Thanks for your reply. I have updated my python to version 3.10 and re-install pyscenic to version 0.12.1 and I also install this in a new server, the error still occured. I have no idea. Did you have any other suggestions?
Best.
Xiangyu
![图片](https://github.com/aertslab/pySCENIC/assets/20773767/8d536d13-bd29-4c39-ba8c-61319d4264e4)

**Comment by ojikj2019** [comment]
Hi Xiangyu,

Actually, I got the same error yesterday when I was running the tool even if it had been fine since I re-installed pyscenic as I mentioned before. So, I've removed only the 'Pandas' (version 2.0.1) and then re-installed it at the version of 1.5.2, then it looks like working okay. In addition, I didn't set the Pandas version 1.5.2 when I was re-installing it, i.e., it was automatically re-installed at the version. Hope this helps you.

Best,

Jinhong
________________________________

**Comment by yangjy53** [comment]
I have solved it by downgrade pandas to 1.5.3.
