### ISSUE TITLE
[BUG] 'Series' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by crotoc** [aertslab/pySCENIC#475]
**Describe the bug**

I install SCENIC through pip and the python version is 3.10.

When running the aucell step, it throws the error:

 'Series' object has no attribute 'iteritems'

After debugging, the reason is pandas has deprecated the iteritems on Series. So I replace it to item. Everything goes fine.

The file needs to be revised is cli/utils.py, line 352：
`for name, threshold in auc_thresholds.iteritems()`

revised to 

`for name, threshold in auc_thresholds.items(）` 

Please have a check. Thanks!

> Mote that most *errors* are due to the input from the user, and therefore should be treated as questions in the Discussions. Please, only report them as bugs if you are quite certain that they are not behaving as expected.

**Steps to reproduce the behavior**
1. Command run when the error occurred:

```python
...
```

2. Error encountered:

```pytb
...
```

**Expected behavior**

**Please complete the following information:**
- pySCENIC version: [e.g. 0.10.0, use `pyscenic -h` at the command line]
- Installation method: [e.g. Conda, Pip, Docker, Singularity]
- Run environment: [e.g. Jupyter notebook, CLI, Nextflow, HPC script]
- OS: [e.g. Ubuntu]
- Package versions: [obtain using `pip freeze`, `conda list`, or skip this if using Docker/Singularity]:

```
...
```

**Comment by JarningGau** [comment]
try this:
```bash
conda create -y -n pyscenic_env python=3.10
conda activate pyscenic_env
pip install pyscenic   
pip install numpy==1.23.5 
pip install pandas==1.5.3 
pip install numba==0.56.4 
```

**Comment by ghuls** [comment]
pySCENIC should be compatible with Pandas >=1.5.0 now:
https://github.com/aertslab/pySCENIC/commit/c146a2ea39242ea09cd0f43f14d9a1b84b165ba8

**Comment by jesswhitts** [comment]
Is this resolved in the latest pypi version? I'm getting the same error, and downgrading pandas causes issues with dask

**Comment by niccolovono** [comment]
I was able to solve that issue by downgrading pandas to version 1.5.1 only for that step. `pip upgrade pandas==1.5.1` and than upgrading again to version 2.2.1 following the same command but obviously changing the version.

**Comment by szhaoaf** [comment]
`pip install pandas==1.5.3 `
Downgrade pandas worked for me though giving me the error. As long as pandas was downgraded, it works.
```
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.3
    Uninstalling pandas-2.2.3:
      Successfully uninstalled pandas-2.2.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dask-expr 0.5.3 requires pandas>=2, but you have pandas 1.5.3 which is incompatible.
Successfully installed pandas-1.5.3
```

**Comment by niccolovono** [comment]
> `pip install pandas==1.5.3 ` Downgrade pandas worked for me though giving me the error. As long as pandas was downgraded, it works.
> 
> ```
> Installing collected packages: pandas
>   Attempting uninstall: pandas
>     Found existing installation: pandas 2.2.3
>     Uninstalling pandas-2.2.3:
>       Successfully uninstalled pandas-2.2.3
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> dask-expr 0.5.3 requires pandas>=2, but you have pandas 1.5.3 which is incompatible.
> Successfully installed pandas-1.5.3
> ```

I suggest to upgrade pandas again to the latest version after running the AUCell step, otherwise it could give you other errors.

**Comment by Jingheng-ZHANG-1999** [comment]
for me, replacing 'iteritems' to 'items' in /path_to_anaconda3/envs/Scenic/lib/python3.10/site-packages/pyscenic/cli/utils.py resolved the issue.
