### ISSUE TITLE
pyscenic grn in singularity: workers continuously restarting after memory warnings

### ISSUE THREAD

**Issue by kverstae** [aertslab/pySCENIC#54]
Hi,
I am trying to use pySCENIC in a singularity container (version 0.9.5) but I keep getting warnings that eventualy result in errors and workers continuously restarting (see below). 
The system I get these errors on has 22gb ram and I used 4 workers.
When I run the exact same thing (same singularity image, same inputs, same command) on a machine with more ram (64gb), everything works perfectly.

During the warnings, I checked the memory usage and it never went over 14gb.
Is there something I can do to make this also work on the machine with 22gb ram? Or is this problem caused by the 'limited' amount of ram available?

```
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 732.21 MB -- Worker memory limit: 1.03 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 732.21 MB -- Worker memory limit: 1.03 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 732.21 MB -- Worker memory limit: 1.03 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 732.21 MB -- Worker memory limit: 1.03 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 732.21 MB -- Worker memory limit: 1.03 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 732.21 MB -- Worker memory limit: 1.03 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 732.21 MB -- Worker memory limit: 1.03 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 732.21 MB -- Worker memory limit: 1.03 GB
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.nanny - WARNING - Worker process 25440 was killed by unknown signal
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 732.21 MB -- Worker memory limit: 1.03 GB
distributed.nanny - WARNING - Restarting worker
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 732.21 MB -- Worker memory limit: 1.03 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 732.21 MB -- Worker memory limit: 1.03 GB
distributed.worker - WARNING - Worker is at 95% memory usage. Pausing worker.  Process memory: 978.70 MB -- Worker memory limit: 1.03 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 732.21 MB -- Worker memory limit: 1.03 GB
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.worker - ERROR - Worker stream died during communication: tcp://127.0.0.1:36289
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py", line 181, in read
    n_frames = yield stream.read_bytes(8)
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/distributed/worker.py", line 1607, in gather_dep
    who=self.address)
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.6/site-packages/distributed/worker.py", line 2671, in get_data_from_worker
    max_connections=max_connections)
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.6/site-packages/distributed/core.py", line 457, in send_recv
    response = yield comm.read(deserializers=deserializers)
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py", line 201, in read
    convert_stream_closed_error(self, e)
  File "/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py", line 130, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc))
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closeddistributed.worker - ERROR - Worker stream died during communication: tcp://127.0.0.1:36289
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py", line 181, in read
    n_frames = yield stream.read_bytes(8)
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/distributed/worker.py", line 1607, in gather_dep
    who=self.address)
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.6/site-packages/distributed/worker.py", line 2671, in get_data_from_worker
    max_connections=max_connections)
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.6/site-packages/distributed/core.py", line 457, in send_recv
    response = yield comm.read(deserializers=deserializers)
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py", line 201, in read
    convert_stream_closed_error(self, e)
  File "/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py", line 130, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc))
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
```
This keeps going until I manualy stop the process.

**Comment by ghuls** [comment]
pySCENIC is quite memory hungry. Try to run with less threads on your 22GiB RAM machine.

The warning comes from `dask`
`distributed.nanny - WARNING - Worker process 25440 was killed by unknown signal`

If you run `dmesg` you probably will see that OOM killer killed one of the python processes (`Out of memory:` lines)

**Comment by kverstae** [comment]
Even with only 1 thread I get following output:

**Comment by Liang-BGI** [comment]
Hello, I got the same warning when running pyscenic grn function (version: 0.9.17).

**Comment by bramvds** [comment]
Dear Liang,

pySCENIC is known to be quite memory hungry. Does the process block or are you able to get results from the grn step?

Kindest regards.
Bram

**Comment by fbrundu** [comment]
Hi all,

I have a similar problem running pySCENIC through docker on a 64G machine (on AWS).

```
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.scheduler - ERROR - Couldn't gather keys {'finalize-71d032c1a1d0bee1f19ab68b246122c4': ['tcp://127.0.0.1:33991']} state: ['waiting'] workers: ['tcp://127.0.0.1:33991']
NoneType: None
distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://127.0.0.1:33991'], finalize-71d032c1a1d0bee1f19ab68b246122c4
NoneType: None
distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {'finalize-71d032c1a1d0bee1f19ab68b246122c4': ('tcp://127.0.0.1:33991',)}
distributed.nanny - WARNING - Restarting worker
```

I checked the memory usage but it seems to be constantly around 25% max. I am using 8 workers on an 8-core machine.

```
> docker stats
CONTAINER ID        NAME                 CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
70eeaf3c3c0d        quirky_ardinghelli   798.28%             22.75GiB / 62.04GiB   36.67%              14.6kB / 0B         0B / 0B             207
```

This process has been running for several days on a large count matrix (55k cells, 20k genes). I used sparse matrix support from pySCENIC to reduce the memory usage.
- How can I fine-tune the number of workers/memory limit for each worker to avoid workers rescheduling?
- When a worker is restarted, is the computation resumed on a specific task, or the task is started as new?

Thanks,
Francesco

**Comment by cflerin** [comment]
Hi @fbrundu ,

What version of pySCENIC are you using? I would recommend updating to 0.11.0 if you haven't already.

If you have problems with the Dask implementation, I would suggest trying the multiprocessing script ([see here](https://pyscenic.readthedocs.io/en/latest/faq.html#i-am-having-problems-with-dask)). From your logs it might help, unless updating to 0.11.0 fixes this.

But I think maybe the larger problem is that running 55k x 20k expression matrix is simply going to take a very long time with 8 threads. It's hard to say exactly but I would guess something like 3-6 days. You can check the dask dashboard for some kind of progress indicator ([see here](https://arboreto.readthedocs.io/en/latest/troubleshooting.html#q-how-can-i-use-the-dask-diagnostics-bokeh-dashboard) for an example, but I haven't tried to connect to a running instance in Docker. It might be tricky to access the correct port, usually 8787). If you use the multiprocessing script, it will print the progress right to the terminal.

**Comment by fbrundu** [comment]
Thanks @cflerin.

I got the pySCENIC docker image version 0.11.0 (from https://hub.docker.com/r/aertslab/pyscenic).

No ports seem to be exposed by the docker container (if I read it correctly).

```
> docker ps
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS               NAMES
70eeaf3c3c0d        aertslab/pyscenic:0.11.0   "pyscenic grn --num_…"   4 days ago          Up 4 days                               quirky_ardinghelli
```

I also checked with netstat on the AWS instance with similar results.

I'll wait for the 10-day mark, I think, then try the multiprocessing implementation.

Thanks

**Comment by fbrundu** [comment]
Hi @cflerin 

I was able to connect to the Dask dashboard at the 10-day mark:

<img width="949" alt="image" src="https://user-images.githubusercontent.com/697622/113741135-58f85b00-96cf-11eb-9f7d-e96a9a5402cc.png">

How should I read this plot? From the docs at [dask](https://docs.dask.org/en/latest/diagnostics-distributed.html) I think this indicates that the progress should be on average 1/2 - 2/3. But I am not sure which of the tasks takes more time to be executed. Am I correct? Should I expect 15-20 days of runtime?

Thanks

**Comment by cflerin** [comment]
Hi @fbrundu ,

Thanks for the detailed updates on running this in AWS and port mapping! It seems like enabling root access here could be a security issue, but in your use case on AWS it's probably fine -- perhaps I should expose port 8787 in the docker container going forward.

On the progress plot, I think you should go by the `from-delayed` progress, as this is the main function processing the data (it in turn calls `infer_partial_network` for each TF-gene combination). I'm surprised at the 20+ day run time estimate. But it is a large matrix...

**Comment by fbrundu** [comment]
Hi @cflerin,

In the end, the process ran for 13 days (probably there was a latency component at the beginning).
However, after completion of the process, the adjacency matrix in output is an empty file, and the process restarted.
I am not sure what the problem was here since I didn't have any other warnings.
I'll probably use the multiprocessing script...

**Comment by fbrundu** [comment]
Few additional considerations:

I reran the grn process on a bigger machine (16 cores and 128G vs 8 cores and 64G) - BUT I defined 8 as the number of cores available to pySCENIC. I removed the `--sparse` flag. The process completed correctly in less than 2 days (with respect to the previous ~13 days).

It is possible that the sparse configuration doesn't work properly in some circumstances (and runtime increases non-linearly with the number of genes). Or, the procedure requires more cores than declared when instantiating the docker container (therefore, there should be some additional free cores to execute it correctly).

Also, I think that the warning of workers restarting might be a good reason to stop the process earlier since probably they will make the entire procedure fail eventually (in my experience).

**Comment by cflerin** [comment]
Hi @fbrundu ,

Sorry to hear that your run failed after 13 days! That's super frustrating... It's strange that there was no error. But glad to hear that you finally got it finished. Thanks for the feedback on the sparse usage as well. I'm not sure exactly why this is the case but it's helpful to know this at least.

**Comment by cflerin** [comment]
I'm going to close this since the original issue was from an older version, and I think this is a problem with Arboreto specifically (aertslab/arboreto/issues/15).
