### ISSUE TITLE
[BUG] typeerro when import scanpy with pyscenic in conda

### ISSUE THREAD

**Issue by Quentin-bioinfo** [aertslab/pySCENIC#565]
After creating a conda and installing pyscenic:
```
conda create -y -n pyscenic python=3.10
conda activate pyscenic
pip install pyscenic
```

I installed scanpy with `pip install scanpy` 

But when I try to import the module scanpy i get an error 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[8], line 4
      2 import os
      3 import numpy as np
----> 4 import scanpy as sc
      5 import pandas as pd
      7 import loompy as lp

File ~/miniconda3/envs/pyscenic/lib/python3.10/site-packages/scanpy/__init__.py:24
     21 # the actual API
     22 # (start with settings as several tools are using it)
     23 from ._settings import settings, Verbosity
---> 24 from . import tools as tl
     25 from . import preprocessing as pp
     26 from . import plotting as pl

File ~/miniconda3/envs/pyscenic/lib/python3.10/site-packages/scanpy/tools/__init__.py:1
----> 1 from ..preprocessing import pca
      2 from ._tsne import tsne
      3 from ._umap import umap

File ~/miniconda3/envs/pyscenic/lib/python3.10/site-packages/scanpy/preprocessing/__init__.py:1
----> 1 from ._recipes import recipe_zheng17, recipe_weinreb17, recipe_seurat
      2 from ._simple import filter_cells, filter_genes
      3 from ._deprecated.highly_variable_genes import filter_genes_dispersion

File ~/miniconda3/envs/pyscenic/lib/python3.10/site-packages/scanpy/preprocessing/_recipes.py:12
      7 from .. import preprocessing as pp
      8 from ._deprecated.highly_variable_genes import (
      9     filter_genes_dispersion,
     10     filter_genes_cv_deprecated,
     11 )
---> 12 from ._normalization import normalize_total
     13 from .. import logging as logg
     14 from .._utils import AnyRandom

File ~/miniconda3/envs/pyscenic/lib/python3.10/site-packages/scanpy/preprocessing/_normalization.py:7
      5 from anndata import AnnData
      6 from scipy.sparse import issparse
----> 7 from sklearn.utils import sparsefuncs
      9 try:
     10     from dask.array import Array as DaskArray

File ~/miniconda3/envs/pyscenic/lib/python3.10/site-packages/sklearn/__init__.py:84
     70     # We are not importing the rest of scikit-learn during the build
     71     # process, as it may not be compiled yet
     72 else:
   (...)
     78     # later is linked to the OpenMP runtime to make it possible to introspect
     79     # it and importing it first would fail if the OpenMP dll cannot be found.
     80     from . import (
     81         __check_build,  # noqa: F401
     82         _distributor_init,  # noqa: F401
     83     )
---> 84     from .base import clone
     85     from .utils._show_versions import show_versions
     87     __all__ = [
     88         "calibration",
     89         "cluster",
   (...)
    130         "show_versions",
    131     ]

File ~/miniconda3/envs/pyscenic/lib/python3.10/site-packages/sklearn/base.py:19
     17 from ._config import config_context, get_config
     18 from .exceptions import InconsistentVersionWarning
---> 19 from .utils._estimator_html_repr import _HTMLDocumentationLinkMixin, estimator_html_repr
     20 from .utils._metadata_requests import _MetadataRequester, _routing_enabled
     21 from .utils._param_validation import validate_parameter_constraints

File ~/miniconda3/envs/pyscenic/lib/python3.10/site-packages/sklearn/utils/__init__.py:11
      9 from . import _joblib, metadata_routing
     10 from ._bunch import Bunch
---> 11 from ._chunking import gen_batches, gen_even_slices
     12 from ._estimator_html_repr import estimator_html_repr
     14 # Make _safe_indexing importable from here for backward compat as this particular
     15 # helper is considered semi-private and typically very useful for third-party
     16 # libraries that want to comply with scikit-learn's estimator API. In particular,
     17 # _safe_indexing was included in our public API documentation despite the leading
     18 # `_` in its name.

File ~/miniconda3/envs/pyscenic/lib/python3.10/site-packages/sklearn/utils/_chunking.py:8
      5 import numpy as np
      7 from .._config import get_config
----> 8 from ._param_validation import Interval, validate_params
     11 def chunk_generator(gen, chunksize):
     12     """Chunk generator, ``gen`` into lists of length ``chunksize``. The last
     13     chunk may have a length less than ``chunksize``."""

File ~/miniconda3/envs/pyscenic/lib/python3.10/site-packages/sklearn/utils/_param_validation.py:14
     11 from scipy.sparse import csr_matrix, issparse
     13 from .._config import config_context, get_config
---> 14 from .validation import _is_arraylike_not_scalar
     17 class InvalidParameterError(ValueError, TypeError):
     18     """Custom exception to be raised when the parameter of a class/method/function
     19     does not have a valid type or value.
     20     """

File ~/miniconda3/envs/pyscenic/lib/python3.10/site-packages/sklearn/utils/validation.py:26
     24 from .. import get_config as _get_config
     25 from ..exceptions import DataConversionWarning, NotFittedError, PositiveSpectrumWarning
---> 26 from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace
     27 from ..utils.fixes import ComplexWarning, _preserve_dia_indices_dtype
     28 from ._isfinite import FiniteStatus, cy_isfinite

File ~/miniconda3/envs/pyscenic/lib/python3.10/site-packages/sklearn/utils/_array_api.py:11
      8 import scipy.special as special
     10 from .._config import get_config
---> 11 from .fixes import parse_version
     13 _NUMPY_NAMESPACE_NAMES = {"numpy", "array_api_compat.numpy"}
     16 def yield_namespaces(include_numpy_namespaces=True):

File ~/miniconda3/envs/pyscenic/lib/python3.10/site-packages/sklearn/utils/fixes.py:20
     18 import scipy
     19 import scipy.sparse.linalg
---> 20 import scipy.stats
     22 from ..externals._packaging.version import parse as parse_version
     23 from .parallel import _get_threadpool_controller

File ~/miniconda3/envs/pyscenic/lib/python3.10/site-packages/scipy/stats/__init__.py:610
      1 """
      2 .. _statsrefmanual:
      3 
   (...)
    605 
    606 """  # noqa: E501
    608 from ._warnings_errors import (ConstantInputWarning, NearConstantInputWarning,
    609                                DegenerateDataWarning, FitError)
--> 610 from ._stats_py import *
    611 from ._variation import variation
    612 from .distributions import *

File ~/miniconda3/envs/pyscenic/lib/python3.10/site-packages/scipy/stats/_stats_py.py:49
     46 # Import unused here but needs to stay until end of deprecation periode
     47 # See https://github.com/scipy/scipy/issues/15765#issuecomment-1875564522
     48 from scipy import linalg  # noqa: F401
---> 49 from . import distributions
     50 from . import _mstats_basic as mstats_basic
     52 from ._stats_mstats_common import _find_repeats, theilslopes, siegelslopes

File ~/miniconda3/envs/pyscenic/lib/python3.10/site-packages/scipy/stats/distributions.py:10
      1 #
      2 # Author:  Travis Oliphant  2002-2011 with contributions from
      3 #          SciPy Developers 2004-2011
   (...)
      6 #       instead of `git blame -Lxxx,+x`.
      7 #
      8 from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)  # noqa: F401
---> 10 from . import _continuous_distns
     11 from . import _discrete_distns
     13 from ._continuous_distns import *  # noqa: F403

File ~/miniconda3/envs/pyscenic/lib/python3.10/site-packages/scipy/stats/_continuous_distns.py:12
     10 import numpy as np
     11 from numpy.polynomial import Polynomial
---> 12 from scipy.interpolate import BSpline
     13 from scipy._lib.doccer import (extend_notes_in_docstring,
     14                                replace_notes_in_docstring,
     15                                inherit_docstring_from)
     16 from scipy._lib._ccallback import LowLevelCallable

File ~/miniconda3/envs/pyscenic/lib/python3.10/site-packages/scipy/interpolate/__init__.py:167
      1 """
      2 ========================================
      3 Interpolation (:mod:`scipy.interpolate`)
   (...)
    165 (should not be used in new code).
    166 """
--> 167 from ._interpolate import *
    168 from ._fitpack_py import *
    170 # New interface to fitpack library:

File ~/miniconda3/envs/pyscenic/lib/python3.10/site-packages/scipy/interpolate/_interpolate.py:12
      9 from scipy._lib._util import copy_if_needed
     10 from scipy.special import comb
---> 12 from . import _fitpack_py
     13 from ._polyint import _Interpolator1D
     14 from . import _ppoly

File ~/miniconda3/envs/pyscenic/lib/python3.10/site-packages/scipy/interpolate/_fitpack_py.py:8
      5 import numpy as np
      7 # These are in the API for fitpack even if not used in fitpack.py itself.
----> 8 from ._fitpack_impl import bisplrep, bisplev, dblint  # noqa: F401
      9 from . import _fitpack_impl as _impl
     10 from ._bsplines import BSpline

File ~/miniconda3/envs/pyscenic/lib/python3.10/site-packages/scipy/interpolate/_fitpack_impl.py:103
     52 _iermess = {
     53     0: ["The spline has a residual sum of squares fp such that "
     54         "abs(fp-s)/s<=0.001", None],
   (...)
     68     'unknown': ["An error occurred", TypeError]
     69 }
     71 _iermess2 = {
     72     0: ["The spline has a residual sum of squares fp such that "
     73         "abs(fp-s)/s<=0.001", None],
   (...)
     99     'unknown': ["An error occurred", TypeError]
    100 }
    102 _parcur_cache = {'t': array([], float), 'wrk': array([], float),
--> 103                  'iwrk': array([], dfitpack_int), 'u': array([], float),
    104                  'ub': 0, 'ue': 1}
    107 def splprep(x, w=None, u=None, ub=None, ue=None, k=3, task=0, s=None, t=None,
    108             full_output=0, nest=None, per=0, quiet=1):
    109     # see the docstring of `_fitpack_py/splprep`
    110     if task <= 0:

TypeError:

I also see that i get an error just with `pyscenic -h `

 '/miniconda3/envs/pyscenic/lib/python3.10/site-packages/pyscenic/transform.py:42: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  ("Enrichment", COLUMN_NAME_ANNOTATION): np.object,
Traceback (most recent call last):
  File "/miniconda3/envs/pyscenic/bin/pyscenic", line 5, in <module>
    from pyscenic.cli.pyscenic import main
  File "/miniconda3/envs/pyscenic/lib/python3.10/site-packages/pyscenic/cli/pyscenic.py", line 26, in <module>
    from pyscenic.prune import _prepare_client, find_features, prune2df
  File "/miniconda3/envs/pyscenic/lib/python3.10/site-packages/pyscenic/prune.py", line 27, in <module>
    from .transform import (
  File "/miniconda3/envs/pyscenic/lib/python3.10/site-packages/pyscenic/transform.py", line 42, in <module>
    ("Enrichment", COLUMN_NAME_ANNOTATION): np.object,
  File "/miniconda3/envs/pyscenic/lib/python3.10/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'object_'?

any ideas ? Any good version compatibilities witht all the modules required ?
Thank you :)

**Comment by lucascolley** [comment]
the second bug should have been fixed by https://github.com/aertslab/pySCENIC/commit/eaf23eb1fdcaae79b273de56b374b71aa8afde5a, although there has not been a pySCENIC release since the fix was made.

the first bug looks suspiciously similar to https://github.com/scipy/scipy/issues/21014, although it looks like the problem there was Python 3.9, whereas you are on 3.10. What is your SciPy version?

**Comment by Quentin-bioinfo** [comment]
scipy                       1.14.0
numpy                       1.26.4

**Comment by lucascolley** [comment]
thanks @Quentin-bioinfo . Please could you try to reproduce the problem with just SciPy and NumPy calls? If you can, please open an issue on the SciPy repo.

**Comment by siriuz42** [comment]
https://github.com/scipy/scipy/issues/21289 fixed it for me with scipy==1.13.0 (and 1.14.0), numpy==1.26.4 and python==3.10

**Comment by lucascolley** [comment]
Could you submit a bug report to SciPy @siriuz42 ?

**Comment by Quentin-bioinfo** [comment]
> thanks @Quentin-bioinfo . Please could you try to reproduce the problem with just SciPy and NumPy calls? If you can, please open an issue on the SciPy repo.

I'm not sure how but after recreating a conda and installing some package individually it works as expected.
