### ISSUE TITLE
AUCell ratio calculation issue

### ISSUE THREAD

**Issue by johnnyliu1992** [aertslab/pySCENIC#57]
https://github.com/aertslab/pySCENIC/blob/1b140953375dc3633bf54bd647b2b00ff871912e/src/pyscenic/recovery.py#L111

hello,
When I used AUCell by itself, I am having a warning from this line of code. As I inspected the source code, I think `len(rnk)` should refer to the number of cells in expression matrix, not the number of genes that have expression data in expression matrix. So I think the right if condition here should be `if rnk.empty or float(len(rnk.columns))/len(regulon) < 0.80`
Let me know if I misunderstand this part of the code. Thank you! 
Pyscenic is a great work!

Johnny

**Comment by bramvds** [comment]
Hi Johnny,

Thanks for pointing this out. Much appreciated.

Commited the change. Bugfix will appear in the next release of pySCENIC.

Kindest regards,
Bram
