### ISSUE TITLE
pyscenic aucell 

### ISSUE THREAD

**Issue by zznx** [aertslab/pySCENIC#572]
Hi, at present, the task has not been finished. Can I get help ?
`pyscenic aucell adata.loom reg.csv --output pyscenic_output.loom`
python: ../nptl/pthread_mutex_lock.c:81: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
OpenBLAS warning: precompiled NUM_THREADS exceeded, adding auxiliary array for thread metadata.

**Comment by zznx** [comment]
It's the same thing.
`pyscenic aucell adata.loom reg.gmt --output pyscenic_output.loom`

**Comment by zznx** [comment]
It works for now, thanks

**Comment by DawnEve** [comment]
How do you solve the problem?

Even I run `$ export OPENBLAS_NUM_THREADS=1` before the command, the same error still occured.
