### ISSUE TITLE
Database creation for Killifish

### ISSUE THREAD

**Issue by juhi-ku** [aertslab/pySCENIC#574]
Hello,

I am working on TBI in killifish using bioinformatics approach.
I want to investigate killifish clusters and it’s subclusters as it is not very well studied. I want to discover the cell types and clusters and to do so I was planning to work on Gene Regulatory analysis using SCENIC as it has an option to make custom database. Since you and your other colleagues have made the software, I was hoping if you could help me in creating the database for killifish as well. For Killifish we have Ensemble genome (https://www.ensembl.org/Nothobranchius_furzeri/Info/Index ) and Transcription factor list (from the TFDB database) but we do not have any Motif information. Can you let me know if this information is sufficient to proceed? I had a look already into the codes on GitHub, but I still wanted to ask and confirm and seems a bit tough myself to proceed so if you could help me or let me know how it’s done, would be a great help in my research and to the killifish community as well!
Thank You!

**Comment by ghuls** [comment]
See: https://github.com/aertslab/create_cisTarget_databases/issues/53
