### ISSUE TITLE
getAUC fucntion error 

### ISSUE THREAD

**Issue by apal6** [aertslab/pySCENIC#576]
Hi,

I am having an issue with the getAUC function; 
library(AUCell)
regulonActivity_byCellType <- sapply(cellInfo,
                                     function(Cell) rowMeans(getAUC(auc_mtx_numeric)[,Cell]))

```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'rowMeans': unable to find an inherited method for function ‘getAUC’ for signature ‘"matrix"’
```
Could you someone please help?

Best regards,
Aastha

**Comment by ghuls** [comment]
The R version is deprecated.
