### ISSUE TITLE
sensitive to dropout

### ISSUE THREAD

**Issue by yuliusema4** [aertslab/pySCENIC#59]
Hi,

Here is the paper testing GENIE3's performance. 
Evaluating methods of inferring gene regulatory networks highlights their lack of performance for single cell gene expression data
BMC Bioinformatics. 2018 Jun 19;19(1):232.

![screen shot 2019-03-08 at 7 08 18 am](https://user-images.githubusercontent.com/46530497/54028062-aeb94c80-4171-11e9-8e12-2041890e68e7.png)

**Comment by bramvds** [comment]
Thanks for sharing. Much appreciated!
