### ISSUE TITLE
using scenic on bulk expression data?

### ISSUE THREAD

**Issue by yuliusema4** [aertslab/pySCENIC#60]
Hi

Can we do that? my feeling is we can, only the interpretation is different.

Best

Yu

**Comment by bramvds** [comment]
Hi Yu,

This could indeed be done. For your reference, SCENIC evolved from the following paper which applied GENIE3 to a multi-condition bulk RNAseq data set followed by pruning of indirect target using the previously published cisTarget method:

Mapping gene regulatory networks in Drosophila eye development by large-scale transcriptome perturbations and motif inference.
Delphine Potier, Kristofer Davie, Gert Hulselmans, Marina Naval Sanchez, Lotte Haagen, Vân Anh Huynh-Thu, Duygu Koldere, Arzu Celik, Pierre Geurts, Valerie Christiaens, Stein Aerts
Cell Reports 2014
https://dx.doi.org/10.1016/j.celrep.2014.11.038

Hope this helps,
Bram
