### ISSUE TITLE
question: Pavlidis Template Matching, GENIE3 and Weighted correlation network analysis (WGCNA)

### ISSUE THREAD

**Issue by yuliusema4** [aertslab/pySCENIC#62]
Hi,
Thanks for referring to the Drosophila eye development paper. I read through it. Excellent work! 
For the co-expression network construction, the paper used PTM, and GENIE3. The current version of SCENIC stop reporting the repressing TF because of the "anti-expression modules are messy and have strong noise" (I remember getting this somewhere). If we use the results from PTM instead of GENE3, from your experience, does this conclusion still hold?
another question is WGCNA is very popular for coexpression network construction, do you compare the results of GENEI3 with WGCNA? 

Best
Yu

**Comment by bramvds** [comment]
Hi Yu,

1. Regulons that capture target genes for which the expression is negatively correlated with the expression of its transcription factor can still be used. E.g. via the CLI used the parameter --all_modules of the ctx step. However, as you mentioned, use the results with caution. We assessed the relevance of these 'repressor regulons' on the Zeisel et al. data set (see example notebooks) on the known REST repressor and the results did not make biological sense (i.e. REST should be active in most cell types of non-neuronal origins - this was not the case).
2. Regarding the usage of WGCNA as a replacement of GENIE3: To my knowledge, this will be difficult as SCENIC needs a Gene Regulatory Network reconstruction step that produces directed networks (i.e. direct regulatory links between a factor and its target genes) and not (undirected) co-expression 'modules'.

Kindest regards,
Bram
