### ISSUE TITLE
PyYAML yaml.load(input) Deprecation

### ISSUE THREAD

**Issue by cflerin** [aertslab/pySCENIC#65]
With recent updates to PyYaml, pySCENIC cli has been reporting the following warning:

```
$ pyscenic -h
/home/luna.kuleuven.be/u0125489/chris/envs/pyscenic097/lib/python3.6/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/home/luna.kuleuven.be/u0125489/chris/envs/pyscenic097/lib/python3.6/site-packages/distributed/config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)
usage: pyscenic [-h] {grn,ctx,aucell} ...

Single-CEll regulatory Network Inference and Clustering (0.9.7)
[...]
```

Starting this issue as a reminder to fix this in next push of updates...

**Comment by Sophia409** [comment]
@bramvds  @cflerin Hi, how did you solve it? I have the same question.

**Comment by cflerin** [comment]
Hi, after looking at this further, this warning is actually generated from Dask and not pySCENIC itself. We're using an older version of Dask, so I don't expect this will be fixed. Seems like we can close this.

**Comment by Sophia409** [comment]
@cflerin Hi, thank you for your early response. So do you mean that i need to update my Dask version? Would this older version affect the result?

**Comment by cflerin** [comment]
No, it should not affect the results at all. It's just a warning from pyyaml. You can read more about in link from the error message: https://msg.pyyaml.org/load

**Comment by Sophia409** [comment]
@cflerin Okay, thank you !
