### ISSUE TITLE
input of scenic

### ISSUE THREAD

**Issue by yuliusema4** [aertslab/pySCENIC#66]
Hi,
We used scenic on a number of dataset, and we like the results very much!
Here is a question about the input to scenic, should the genome-wide expression be used, or only the TF targets as input to scenic? or the top 5000 variable genes? Any suggestions?

Thanks
Best
Y Leo Liu

**Comment by bramvds** [comment]
Dear Y Leo Liu,

You can add the expression matrix covering all genes and cells that passed quality control. Some of the QC rules a use are:
1. Filter out cells with number of genes below a certain threshold (cf. Seurat for R or scanpy for python).
2. Filter out genes that are expressed in a minimal number of cells (cf. Seurat or scanpy).

Hope this helps.
Bram
