### ISSUE TITLE
Load expression matrix from file generated by exportsForArboreto

### ISSUE THREAD

**Issue by snoopy-448** [aertslab/pySCENIC#67]
Hi
I want to use GRNboost to replace the GENIE3 in SCENIC R package. There is a function exportsForArboreto in SCENIC to output expression matrix and TF list for GRNboost. I find the expression matrix generated by exportsForArboreto has no rowname (cell ids) but pyscenic use pd.read_csv(header = 0, index_col = 0) to load expression matrix, so I wonder if I should add a column(rowname) in the expression matrix generated by exportsForArboreto, or the pyscenic will regard the first gene as rownames?

Thanks!

Yang

**Comment by cflerin** [comment]
Hi Yang,

I'm not sure why exportsForArboreto is giving you a file that looks that way, but here's an example of an expression matrix formatted for pySCENIC/GRNBoost2 (it should have row and column names):

```
        DICER1  EIF4EBP2        SMC1A   TSFM
CTGCGGAGTTCGCGAC-1      0       0       0       0
GAATGAACACACTGCG-1      0       0       0       0
ATGCGATTCAGCATGT-1      0       0       0       0
TTCGAAGGTAGCGATG-1      0       1       1       0
CGTAGGCGTCGGCACT-1      0       0       0       0
CCGGGATGTAAAGTCA-1      0       0       1       0
ACTTGTTTCTCTTATG-1      0       0       0       0
ATCCACCGTCGGCACT-1      0       2       1       0
GTACTTTTCGGCTACG-1      0       0       0       0
```

Chris

**Comment by Sophia409** [comment]
@snoopy-448  Hi, I also have the same question, how did you solve it?
```
> exprMat_filtered[1:5, 1:3]
              E14-2_CGCGTGACAGTTGGTT E14-2_CATGCAAGTTTCGTTT E11-1_TGGGCGTAGGCAAAGA
St18                               0                      0                      0
3110035E14Rik                      0                      0                      0
Mcm3                               0                      0                      0
Paqr8                              0                      0                      0
Khdrbs2                            0                      0                      0
> exportsForArboreto(exprMat_filtered, scenicOptions, dir = "int")
TF list written as: int/1.1_inputTFs.txt
Transposed expression matrix written as: int/1.1_exprMatrix_filtered_t.txt
> dataframe <- read.csv("int/N28/1.1_exprMatrix_filtered_t.txt")
> dataframe[1:5,1:5]
  Xkr4 Mrpl15 Lypla1 Tcea1 Rgs20
1    0      0      0     2     0
2    0      0      0     1     0
3    1      0      0     1     0
4    0      1      1     4     0
5    0      2      0     1     0
```

**Comment by Sophia409** [comment]
@cflerin Hi , I don't know how exportsForArboreto gave you a matrix with cell id. I tried it and failed.And i find  write.table format(row.names = FALSE) is wrong in exportsForArboreto function ,row.names  should be true not false.

**Comment by snoopy-448** [comment]
@Sophia409 I write the expr matrix by myself.
`allTFs <- getDbTfs(scenicOptions)
inputTFs <- allTFs[allTFs %in% rownames(exprMat_filtered)]
write.table(inputTFs, file = file.path(dir_run, "int", "1.1_inputTFs.txt"), sep = "\t", quote = FALSE, row.names = FALSE, col.names = FALSE)
message("TF list written as: ", file.path(dir_run, "int", "1.1_inputTFs.txt"))
exprMat_filtered_t <- t(exprMat_filtered)
write.table(exprMat_filtered_t, file = file.path(dir_run, "int", "1.1_exprMatrix_filtered_t.tsv"), sep = "\t", quote = FALSE, row.names = TRUE, col.names = TRUE)
message("Transposed expression matrix written as: ", file.path(dir_run, "int", "1.1_exprMatrix_filtered_t.tsv"))`

**Comment by Sophia409** [comment]
@snoopy-448  Hi, i also do the same modification for original function. The write.table format(row.names = FALSE) is wrong in exportsForArboreto function ,row.names should be true not false.
Wondering why author set row.names to false on purpose.What's the intention?
