### ISSUE TITLE
number of threading

### ISSUE THREAD

**Issue by yuliusema4** [aertslab/pySCENIC#69]
Hi, 
is there a way to set the max number of thread used by scenic? I am using a machine shared with others, so I have to set a limit for threading.

Best
Leo

**Comment by bramvds** [comment]
Dear Leo,

Via the command line this is controlled via the optional parameter -–num_workers=12 (if you want to use only 12 cores for example).

Kr,
Bram

**Comment by yuliusema4** [comment]
I am using python scripts, is there a way to do it in script?

**Comment by bramvds** [comment]
Most functions (like aucell) have a parameter that controls this: num_workers
