### ISSUE TITLE
Empty motifData

### ISSUE THREAD

**Issue by mase5** [aertslab/pySCENIC#70]
Hi,
How come that some regulons do have an empty entry for `motifData`?

![image](https://user-images.githubusercontent.com/16015936/56134890-cca77780-5f8f-11e9-9b11-e5fab5f18a89.png)

**Comment by cflerin** [comment]
I've seen this issue as well.  For example in a mouse dataset:

```
{'regulon': 'Zmiz1(+)',
   'defaultThresholdValue': 0.058765935069168634,
   'defaultThresholdName': 'guassian_mixture_split',
   'allThresholds': {'guassian_mixture_split': 0.058765935069168634},
   'motifData': ''}
```

But there should be a valid logo file for every regulon I think.  Could it be something to do with using the updated "v9" databases perhaps?

**Comment by bramvds** [comment]
Hi Chris,

That is probably the reason. 

Kindest regards,
Bram

**Comment by mase5** [comment]
Hi @bramvds, 

I don't think it's related to the version.

I checked the "Context" of the regulons table generated by the ctx command and still some are empty.
```
frozenset({'', 'activating'})
frozenset({'', 'activating'})
frozenset({'activating', 'transfac_pro__M07666.png'})
frozenset({'cisbp__M0890.png', 'activating'})
frozenset({'activating', 'jaspar__MA0168.1.png'})
frozenset({'activating', 'cisbp__M2325.png'})
frozenset({'', 'activating'})
frozenset({'', 'activating'})
frozenset({'', 'activating'})
frozenset({'activating', 'transfac_pro__M07920.png'})
frozenset({'', 'activating'})
frozenset({'activating', 'transfac_pro__M06858.png'})
frozenset({'activating', 'transfac_pro__M05851.png'})
frozenset({'hdpi__BAT4.png', 'activating'})
frozenset({'', 'activating'})
frozenset({'', 'activating'
[...]
```
motifs: `motifs-v8-nr.flybase-m0.001-o0.0.tbl` 
db: `dm6-5kb-upstream-full-tx-11species.mc8nr.feather`

Any idea why those are empty?

**Comment by mase5** [comment]
Hi @bramvds,

I think I found out why some regulons have an empty motif in the loom file. There is a filter happening on the motif logos when the enriched motifs table is converted to the regulon list. Here is the location in the source code: https://github.com/aertslab/pySCENIC/blob/ac723af79e91b79672fe78b98bd0db82fa19bc0f/src/pyscenic/transform.py#L269-L273

So it's seems that motif logo png file name is saved only if the motif is directly annotated ? Can you confirm this statement ? Could you explain also why you did this ? 

Here is an example (`zfh2(+)`) where the TF has undirected enriched motifs but it's still present in the regulon list without any motif data:

From the enriched table:
![image](https://user-images.githubusercontent.com/16015936/60726453-dc55ad00-9f3b-11e9-9f08-e34061920fdb.png)

![image](https://user-images.githubusercontent.com/16015936/60726505-06a76a80-9f3c-11e9-9e17-763b67d6bd74.png)

From the regulon list:
![image](https://user-images.githubusercontent.com/16015936/60726360-a44e6a00-9f3b-11e9-9326-ca38a0f86c4f.png)


Since there exist some regulons with enriched motifs (in the enriched motif table) that are indirectly annotated, their logo should also be saved in the loom right ?! But then in that case, we should tell the user in SCope that the motif is coming either from direction or indirect annotation.

I hope I made it clear,

Kindly regards,
Max

**Comment by bramvds** [comment]
Hi Max,

Thanks for the research! I fixed this: motif with high NES will now be taken. Will go with next release of pySCENIC.

Kr,
Bram
