### ISSUE TITLE
multiprocessing issue with grnboots

### ISSUE THREAD

**Issue by MingBit** [aertslab/pySCENIC#77]
Hallo Bram,

Thanks for the great tool.
I'm testing pyscenic with docker container with the example code shown in the main page. Here comes an issue about multiprocessing.  

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.    **kwargs

But it works with line by line testing in docker container. Any ideas?
Many thanks.

Best, Ming

**Comment by cflerin** [comment]
Hi Ming,

Can you have a look at the following issues and see if this helps:

https://github.com/tmoerman/arboreto/issues/2

https://github.com/aertslab/pySCENIC/issues/13

Feel free to reopen if this doesn't answer your question.

Chris
