### ISSUE TITLE
Error when importing pyscenic in tutorial

### ISSUE THREAD

**Issue by danielgchen** [aertslab/pySCENIC#78]
Package versions (program run in python 3.6.4):

> arboreto 0.1.5
> dask 1.0.0
> distributed 1.28.1
> pyscenic 0.9.9
> pandas 0.23.4

When I run the below code from the tutorial
```
if __name__ == '__main__':
    import os
    import glob
    import pickle
    import pandas as pd
    import numpy as np
    
    from dask.diagnostics import ProgressBar
    
    from arboreto.utils import load_tf_names
    from arboreto.algo import grnboost2
    
    from pyscenic.rnkdb import FeatherRankingDatabase as RankingDatabase
    from pyscenic.utils import modules_from_adjacencies, load_motif
    from pyscenic.prune import prune2df, df2regulons
    from pyscenic.aucell import aucell
    
    import seaborn as sns
```

This error occured
`
Assertion failed: (PassInf && "Expected all immutable passes to be initialized"), function addImmutablePass, file /Users/buildbot/miniconda3/conda-bld/llvmdev_1556270736866/work/lib/IR/LegacyPassManager.cpp, line 849.
`
Please, how do I solve this? Thank you

**Comment by bramvds** [comment]
Dear,

Has probably something to do with the latest release of llvm. Could you downgrade this version by starting from a clean miniconda environment and do a pip install llvmlite==0.28.0 before installing pyscenic via pip?

Hope this helps.
Bram
