### ISSUE TITLE
grnboost2 in tutorial won't stop running

### ISSUE THREAD

**Issue by danielgchen** [aertslab/pySCENIC#80]
package versions
```
arboreto 0.1.5
dask 1.0.0
distributed 1.28.1
pyscenic 0.9.9
pandas 0.23.4
```

In the tutorial when I run
`adjacencies = grnboost2(ex_matrix, tf_names=tf_names, verbose=True)`
it continues to run for, as of right now, six hours, I have stopped and rerun the program but it never finishes for this step, leaving only the code below
```
preparing dask client
parsing input
creating dask graph
/anaconda3/lib/python3.7/site-packages/arboreto/algo.py:214: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  expression_matrix = expression_data.as_matrix()
4 partitions
computing dask graph
```
does the tutorial just take a long time to finish this step or is there something I can do? Thank you!

**Comment by cflerin** [comment]
Hello,

The tutorial dataset is 3000 cells and 20k genes, so it's definitely possible for the GRN step (as well as the pruning step) to take quite some time to run.  You haven't given enough information on your computing environment to say for sure, but I'd expect this to take 1-2 hours using 20 dask threads (partitions) on a modern server.  One suggestion would be to use a smaller expression matrix of a few hundred cells if you're only interested in testing.  Feel free to re-open if you have further questions/issues.

Chris

**Comment by tfrudakis** [comment]
It would be great if there was a progress bar or string as it crosses each 10% completion threshold so we could see that it is working and how long it will take to finish.
