### ISSUE TITLE
"Intersection of gene_names and tf_names is empty" error when running DOCKER image

### ISSUE THREAD

**Issue by pengyu1608** [aertslab/pySCENIC#82]
Hi, I got the error when run DOCKER like this:

$docker images
REPOSITORY                                       TAG                 IMAGE ID            CREATED             SIZE
aertslab/pyscenic                                latest              bfaca50f4cb3        2 weeks ago         969.5 MB

$docker run -v /data_summary/new/SCENIC:/scenic  \
 aertslab/pyscenic pyscenic grn  \
 --num_workers 20 \
 -o /scenic/GSE60361_adjacencies.tsv \
 /scenic/GSE60361_Expression.tsv \
 /scenic/mm_mgi_tfs.txt

###the run info

preparing dask client
parsing input
not shutting down client, client was created externally
finished
Traceback (most recent call last):
  File "/usr/local/bin/pyscenic", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/pyscenic/cli/pyscenic.py", line 402, in main
    args.func(args)
  File "/usr/local/lib/python3.6/site-packages/pyscenic/cli/pyscenic.py", line 67, in find_adjacencies_command
    network = method(expression_data=ex_mtx, tf_names=tf_names, verbose=True, client_or_address=client)
  File "/usr/local/lib/python3.6/site-packages/arboreto/algo.py", line 41, in grnboost2
    early_stop_window_length=early_stop_window_length, limit=limit, seed=seed, verbose=verbose)
  File "/usr/local/lib/python3.6/site-packages/arboreto/algo.py", line 115, in diy
    expression_matrix, gene_names, tf_names = _prepare_input(expression_data, gene_names, tf_names)
  File "/usr/local/lib/python3.6/site-packages/arboreto/algo.py", line 229, in _prepare_input
    raise ValueError('Intersection of gene_names and tf_names is empty.')
ValueError: Intersection of gene_names and tf_names is empty.

Could anyone give some suggestion? Thanks.

**Comment by cflerin** [comment]
This error means that there are no genes found in common between your transcription factors and your expression matrix.  Perhaps your expression matrix is transposed? pySCENIC expects cells in rows, genes in columns; you could try using the transpose option (`--transpose`) in this case.  Otherwise, the TFs file should have one gene per line and should have at least partial overlap with the expression matrix genes.

Chris

**Comment by pengyu1608** [comment]
Thanks, Chris.--transpose is needed. I just directly used the file downloaded From GEO. Adding the notice in document will be helpful to people like me, :-)-------- 原始邮件 --------主题：Re: [aertslab/pySCENIC] "Intersection of gene_names and tf_names is empty" error when running DOCKER image (#82)发件人：Chris Campbell Flerin 收件人：aertslab/pySCENIC 抄送：Peng Yu ,Author This error means that there are no genes found in common between your transcription factors and your expression matrix.  Perhaps your expression matrix is transposed? pySCENIC expects cells in rows, genes in columns; you could try using the transpose option (--transpose) in this case.  Otherwise, the TFs file should have one gene per line and should have at least partial overlap with the expression matrix genes.
Chris

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/aertslab/pySCENIC/issues/82?email_source=notifications\u0026email_token=AFBVFT5AK6NW3YAVCZLWVVDP4R46XA5CNFSM4H3ZEYN2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYWNHXA#issuecomment-506254300",
"url": "https://github.com/aertslab/pySCENIC/issues/82?email_source=notifications\u0026email_token=AFBVFT5AK6NW3YAVCZLWVVDP4R46XA5CNFSM4H3ZEYN2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYWNHXA#issuecomment-506254300",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by cflerin** [comment]
Glad to hear this helped. We'll add this note to the docs.

**Comment by KabitaBaral1** [comment]
Hi @cflerin  my exp matrix is transposed and I still get the same error as him:
ValueError: Intersection of gene_names and tf_names is empty.

I am using pyscenic via Jupyter Notebook.

Could you please let me know if something else could cause it?
I downloaded human tf list from here :
https://github.com/aertslab/pySCENIC/blob/master/resources/hs_hgnc_tfs.txt

Here's the complete error message I get:
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}

2020-04-09 13:48:28,354 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.

2020-04-09 13:48:35,046 - pyscenic.cli.pyscenic - INFO - Inferring regulatory networks.
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
preparing dask client
parsing input
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arboreto/algo.py:214: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  expression_matrix = expression_data.as_matrix()
not shutting down client, client was created externally
finished
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/pyscenic", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 420, in main
    args.func(args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 72, in find_adjacencies_command
    network = method(expression_data=ex_mtx, tf_names=tf_names, verbose=True, client_or_address=client, seed=args.seed)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arboreto/algo.py", line 41, in grnboost2
    early_stop_window_length=early_stop_window_length, limit=limit, seed=seed, verbose=verbose)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arboreto/algo.py", line 115, in diy
    expression_matrix, gene_names, tf_names = _prepare_input(expression_data, gene_names, tf_names)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arboreto/algo.py", line 229, in _prepare_input
    raise ValueError('Intersection of gene_names and tf_names is empty.')
ValueError: Intersection of gene_names and tf_names is empty.

Thank you

**Comment by ajwilk** [comment]
I suspect I might be running into a similar issue... 
```
docker run -it --rm \
    -v /Volumes/GoogleDrive/scRNA-seq:/data \
    aertslab/pyscenic:0.10.0 pyscenic grn \
        --num_workers 6 \
        -o /data/analyses/SCENIC/outs/covid_pbn.cl_expr_mat.adjacencies.csv \
        /data/analyses/SCENIC/ins/covid_pbn.cl_expr_mat.csv \
        /data/Resources/SCENIC/hs_hgnc_tfs.txt

2020-06-24 17:41:37,462 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.
```

Completes in about 2 minutes without error, but the resulting `adjacencies.csv` is completely empty, with or without `--transpose`. Any thoughts??

**Comment by KabitaBaral1** [comment]
Thats very weird because it should not take that less time. For me the issue was related to transpose so that helped. Also, I used CLI version so not sure if it has any version issue?

**Comment by cflerin** [comment]
@ajwilk , did the grn step complete actually successfully? Two minutes doesn't sound like enough time. You should have more text after the lines you pasted above which would tell you if it completed.

A somewhat annoying feature is that pyscenic immediately creates an empty output file when starting the process, and leaves it there, even if the run has failed.

**Comment by ajwilk** [comment]
@cflerin that's really good to know, thanks! What I pasted above is the entire output from this command... any suggestions for figuring out what went wrong? there are no errors, and it appears, no verbose flag either.

**Comment by cflerin** [comment]
Hi @ajwilk , I'm not sure why it's not showing more output, there's not a good reason that I can think of, except that maybe something is killing your docker process before it can complete. Could you check memory usage while this is running? It looks like you're on MacOS (so I'm guessing a laptop?), perhaps try reducing the number of workers in this case. 

Otherwise, are your volume mounts correct? It looks you're pointing to data stored locally at `/Volumes/GoogleDrive/scRNA-seq/analyses/SCENIC/ins/covid_pbn.cl_expr_mat.csv`, does that file exist on your machine?

**Comment by nicolasverac** [comment]
"you could try using the transpose option (--transpose) in this case"

Where exactly in the code is the --transpose option to be used? I am trying to add it in several different places and it returns "pyscenic: error: unrecognized arguments: --transposed".

Thanks in advance.
