### ISSUE TITLE
dask distributed

### ISSUE THREAD

**Issue by wangjiawen2013** [aertslab/pySCENIC#84]
Dear,
when I install pyscenic with "pip install pyscenic", it prompt that "ERROR: distributed 2.0.1 has requirement dask>=2, but you'll have dask 1.0.0 which is incompatible." while it has been know that we need dask=1.0.0 to avoid some bugs. So, are there any ways to solve this problem ?

**Comment by cflerin** [comment]
Hi,

Thanks for reporting this. It seems to be caused the the recent upgrade of distributed to v2, which now requires later versions of dask.  You can solve this for now by first installing an older distributed version, then continuing with the standard pyscenic install:

```
pip install distributed==1.28.1
pip install pyscenic
```

**Comment by wangjiawen2013** [comment]
I need to set OPENBLAS_NUM_THREADS=1 and MKL_NUM_THREADS=1 to run pyscenic.
And, during the running process, it indicated that:
adjacencies = grnboost2(ex_matrix, tf_names=tf_names, verbose=True)
preparing dask client
/home/wangjw/bin/miniconda3/envs/pyscenic/lib/python3.6/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
parsing input
/home/wangjw/bin/miniconda3/envs/pyscenic/lib/python3.6/site-packages/arboreto/algo.py:214: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  expression_matrix = expression_data.as_matrix()
creating dask graph
8 partitions
computing dask graph
shutting down client and local cluster
finished
everything is ok,
but, when I ran the next step:  modules = list(modules_from_adjacencies(adjacencies, ex_matrix))
an error occurs: Segmentation fault (core dumped)
I repeated many times and the problem cannot be solved, could you give me some advices ?

**Comment by cflerin** [comment]
Recommend trying this with the newest pySCENIC version (0.11.0)
