### ISSUE TITLE
GRNBoost2 fails with no error message

### ISSUE THREAD

**Issue by rjb67** [aertslab/pySCENIC#91]
I am currently having an issue with running GRNBoost2 as part of my analysis. My expression matrices are able to load in just fine but something goes wrong when actually running it. Here is what I see:

`preparing dask client`
`parsing input`
`creating dask graph`
`FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.`
`expression_matrix = expression_data.as_matrix()`
`36 partitions`
`computing dask graph`

It stops after a minute or so and produces no output and no other error message.

I am running this on Linux Mint in Anaconda. I have tried different versions of tornado and distributed but they have not done anything different.

**Comment by cflerin** [comment]
Recommend trying this with the newest pySCENIC (0.11.0)
