### ISSUE TITLE
pySCENIC output no Loom file

### ISSUE THREAD

**Issue by gharmange** [aertslab/pySCENIC#93]
It seems to me from what I am reading I should expect a .loom life as an output of the pySCENIC pipeline shown in the tutorial, however I am only getting motifs.csv and regions.p as an output. Additionally although I am running AUcell it does not seem to produce an output file. As I look at the code I don't recognize command that would output a file from AUCell or output a .loom file. What am I missing? How to a get this .loom output so I can continue my data analysis in R?
This is the script I am running:
[SCENIC_pipeline_cluster.txt](https://github.com/aertslab/pySCENIC/files/3532238/SCENIC_pipeline_cluster.txt)

**Comment by saeedfc** [comment]
You have to add the following line at the end. This line saves the generated AUCell Matrix to file in csv format.
auc_mtx.to_csv("AUCMatrix.csv").

For making the loom file, you may try as in this notebook;
https://github.com/aertslab/pySCENIC/blob/master/notebooks/pySCENIC%20-%20Create%20loom%20file.ipynb

**Comment by yingyonghui** [comment]
@gharmange So have you solved the problem?
I just have the same questions, and any suggestions would be appreciated!
Thanks!

**Comment by gharmange** [comment]
@yingyonghui  Unfortunately I never figured it out and just move to another part of my analysis. I'm about to start trying to make it work again, have you figured it out?

**Comment by cflerin** [comment]
Hi @gharmange , @yingyonghui ,

Sorry for skipping over this earlier, but pySCENIC will produce a loom file from the `aucell` step in the CLI when you also use loom as an input **and** specify the output file with a `.loom` extension.

Ideally you would use the same loom file for all three steps (`grn`, `ctx`, `aucell`), but if you've already completed the long `grn` process using a tsv file, then it should still be possible to create a loom from that tsv, and use it for the AUCell step only. You could check out [this tutorial](http://htmlpreview.github.io/?https://github.com/aertslab/SCENICprotocol/blob/master/notebooks/PBMC10k_SCENIC-protocol-CLI.html) (or the one posted by @saeedfc) for some examples of how to create a simple loom file. I think Scanpy is the easiest way:
```
import scanpy as sc
import loompy as lp

adata = sc.read_text( 'expression.tsv', delimiter='\t', first_column_names=True )

row_attrs = { 
    "Gene": np.array(adata.var.index) ,
}
col_attrs = { 
    "CellID":  np.array(adata.obs.index) ,
    "nGene": np.array( np.sum(adata.X.transpose()>0 , axis=0)).flatten() ,
    "nUMI": np.array( np.sum(adata.X.transpose() , axis=0)).flatten() ,
}

lp.create( 'expression.loom', adata.X.transpose(), row_attrs, col_attrs )
```
Hope that helps, but feel free to reopen if you're still having problems.

**Comment by cflerin** [comment]
Also, see [this faq entry](https://pyscenic.readthedocs.io/en/latest/faq.html#how-can-i-create-a-scope-compatible-loom-file) for an example of how to take the AUC loom and add a t-SNE and UMAP to it for use in SCope (if that's your goal).
