### ISSUE TITLE
Exporting Regulons

### ISSUE THREAD

**Issue by rcw1** [aertslab/pySCENIC#96]
Hi Bram,

I have a similar request, in my case the Regulons are the most important output from this pipeline, and I need to have them in a human readable format. I've looked for the JSON export command that you reference in this thread, but it's not clear what the command is. Can you write it here, or point me to where I can find it?

Thanks,

Rob

Dear Chris,

Just released a new version (0.8.7). This version includes your suggestion. Thanks.

Kindest regards,
Bram

_Originally posted by @bramvds in https://github.com/aertslab/pySCENIC/issues/16#issuecomment-404523318_

**Comment by bramvds** [comment]
Dear,

This can be done via the Command Line Interface (CLI): the extension of the output file defines the format: GMT, CSV, JSON or YAML are available.

Hope this helps,
Bram
