### ISSUE TITLE
question: investigating why a highly expressed TF is not found in regulon list

### ISSUE THREAD

**Issue by lb15** [aertslab/pySCENIC#98]
Hi! I've run pyscenic on my samples and noticed that one of the major known TFs in my system does not appear in the regulon list. I was surprised by this, as it is highly expressed and is known to bind many targets that are also expressed in the dataset. I can see the TF in the TF list, my input matrix, and the adjacencies.tsv file. After pruning with the command line pyscenic ctx command, it's no longer found in the regulon output. I see many other known TFs, so in general I am getting results that fit the biology of the system.

Given it's at the pruning stage, is it likely that there is not an enrichment of the motifs in the genes expressed in my dataset? I'd like to figure out why exactly it's not included in the regulon list but not sure how to investigate this. I know there are thresholds set for pruning in the ctx command - is there some intermediate file that could guide how I change those thresholds to see if it becomes included? Can I check the enrichment score or threshold of the motifs in the gene list? Thanks for any advice!

**Comment by bramvds** [comment]
You need to adjust the NES threshold. Via the CLI this is done via `--nes_threshold` and is set by default to 3.0. You could lower it to 2.5. In a Jupyter notebook this can be achieved via the parameter `nes_threshold` of `pyscenic.prune.prune2df`. With the latter function, you can inspect the NEScore for your factors of interest in the returned pandas DataFrame object. Hope this helps.

**Comment by lb15** [comment]
Thank you! I now see the TF in the regulon list!
